"""
Binance Web3 Wallet REST API

Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
import pytest
import requests

from unittest.mock import MagicMock, patch
from urllib.parse import parse_qs

from binance_common.configuration import ConfigurationRestAPI
from binance_common.errors import RequiredError
from binance_common.utils import normalize_query_values, is_one_of_model, snake_to_camel

from binance_sdk_web3_wallet.rest_api.api import DefiTransactionApi
from binance_sdk_web3_wallet.rest_api.models import BuildDeFiClaimTransactionResponse
from binance_sdk_web3_wallet.rest_api.models import BuildDeFiDepositTransactionResponse
from binance_sdk_web3_wallet.rest_api.models import BuildDeFiRedeemTransactionResponse
from binance_sdk_web3_wallet.rest_api.models import BuildLpAddTransactionResponse
from binance_sdk_web3_wallet.rest_api.models import BuildLpRemoveTransactionResponse
from binance_sdk_web3_wallet.rest_api.models import CalculateLpAddPairedAmountsResponse
from binance_sdk_web3_wallet.rest_api.models import (
    BuildDeFiClaimTransactionClaimTypeEnum,
)
from binance_sdk_web3_wallet.rest_api.models import (
    BuildLpAddTransactionRequestTokenListInner,
)


class TestDefiTransactionApi:
    @pytest.fixture(autouse=True)
    def setup_client(self):
        """Setup a client instance with mocked session before each test method."""
        self.mock_session = MagicMock(spec=requests.Session)
        config = ConfigurationRestAPI(
            api_key="test-api-key",
            api_secret="test-api-secret",
        )
        self.client = DefiTransactionApi(
            configuration=config, session=self.mock_session
        )

    def set_mock_response(self, data: dict = {}, status_code=200, headers=None):
        """Helper method to setup mock response for the client's session request."""
        if headers is None:
            headers = {}

        mock_response = MagicMock()
        mock_response.status_code = status_code
        mock_response.json.return_value = data
        mock_response.text = json.dumps(data)
        mock_response.headers = headers

        self.mock_session.request.return_value = mock_response

    @patch("binance_common.utils.web3_signature")
    def test_build_de_fi_claim_transaction_success(self, mock_get_signature):
        """Test build_de_fi_claim_transaction() successfully with required parameters only."""

        params = {
            "address": "0x1234567890123456789012345678901234567890",
            "binance_chain_id": "56",
            "claim_type": "LP_FEE",
            "investment_id": "6a3522eee3f2fc4fa9cc1273603429ba95ebd9ff4d33fad8a14d39b9a0a6ce3a",
            "defi_protocol_id": "pancakeswap3",
            "nft_id": "123456",
            "redemption_id": "test-redemption-1",
            "token_address_list": ["0x55d398326f99059fF775485246999027B3197955"],
            "simulate": "True",
        }

        expected_response = {
            "code": 0,
            "msg": "success",
            "data": {
                "dataList": [
                    {
                        "callDataType": "DEPOSIT",
                        "from": "0x1234567890123456789012345678901234567890",
                        "to": "0x87870Bca3F3fF67225794148012b73643B78Ed36",
                        "value": "0x0",
                        "data": "0xa9059cbb000000000000000000000000dead00000000000000000000000000000000dead00000000000000000000000000000000000000000000000000000000000000000a",
                        "gasLimit": "200000",
                        "gasPrice": "3000000000",
                        "maxPriorityFeePerGas": "1000000000",
                        "maxFeePerGas": "3000000000",
                    }
                ],
                "preview": {
                    "success": True,
                    "balanceChange": [
                        {
                            "tokenType": "TOKEN",
                            "tokenSymbol": "USDT",
                            "tokenAddress": "0xdac17f958d2ee523a2206206994597c13d831ec7",
                            "tokenDecimals": "18",
                            "amount": "-1000",
                            "valueUsd": "1000.00",
                        }
                    ],
                    "feeAndContract": {
                        "estimatedNetworkFee": {
                            "amount": "0.000003056787",
                            "tokenSymbol": "BNB",
                            "valueUsd": "0.002002",
                            "rentFeeAmount": None,
                            "rentFeeValueUsd": None,
                            "priorityFeeAmount": None,
                        },
                        "interactWith": {
                            "address": "0xae05cd22df81871bc7cc2a04becfb516bfe332c8"
                        },
                    },
                    "healthFactor": {"before": "1.85", "after": "1.35"},
                    "warnings": [
                        {
                            "code": "HEALTH_FACTOR_WARNING",
                            "level": "WARN",
                            "message": "Health factor will drop below 1.5 after this transaction.",
                        }
                    ],
                    "errorMessage": "insufficient balance",
                },
                "redeemDelayDays": ["7", "10"],
            },
            "timestamp": 1748601600000,
            "success": True,
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.build_de_fi_claim_transaction(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs
        parsed_params = parse_qs(request_kwargs["params"])
        camel_case_params = {snake_to_camel(k): v for k, v in params.items()}
        normalized = normalize_query_values(parsed_params, camel_case_params)

        self.mock_session.request.assert_called_once()
        mock_get_signature.assert_called_once()

        assert "url" in request_kwargs
        assert "/api/v1/defi/transaction/claim" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"
        assert normalized["address"] == "0x1234567890123456789012345678901234567890"
        assert normalized["binanceChainId"] == "56"
        assert normalized["claimType"] == "LP_FEE"
        assert (
            normalized["investmentId"]
            == "6a3522eee3f2fc4fa9cc1273603429ba95ebd9ff4d33fad8a14d39b9a0a6ce3a"
        )
        assert normalized["defiProtocolId"] == "pancakeswap3"
        assert normalized["nftId"] == "123456"
        assert normalized["redemptionId"] == "test-redemption-1"
        assert (
            normalized["tokenAddressList"]
            == '["0x55d398326f99059fF775485246999027B3197955"]'
        )
        assert normalized["simulate"] == "True"

        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(BuildDeFiClaimTransactionResponse)

        if is_list and not is_flat_list:
            expected = expected_response
        elif (
            is_oneof
            or is_list
            or hasattr(BuildDeFiClaimTransactionResponse, "from_dict")
        ):
            expected = BuildDeFiClaimTransactionResponse.from_dict(expected_response)
        else:
            expected = BuildDeFiClaimTransactionResponse.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    @patch("binance_common.utils.web3_signature")
    def test_build_de_fi_claim_transaction_success_with_optional_params(
        self, mock_get_signature
    ):
        """Test build_de_fi_claim_transaction() successfully with optional parameters."""

        params = {
            "address": "address_example",
            "claim_type": BuildDeFiClaimTransactionClaimTypeEnum[
                "REWARD_PROTOCOL"
            ].value,
            "recv_window": 5000,
            "nonce": "unique-nonce-string",
            "binance_chain_id": "binance_chain_id_example",
            "investment_id": "investment_id_example",
            "defi_protocol_id": "defi_protocol_id_example",
            "nft_id": "nft_id_example",
            "redemption_id": "redemption_id_example",
            "token_address_list": [""],
            "simulate": True,
        }

        expected_response = {
            "code": 0,
            "msg": "success",
            "data": {
                "dataList": [
                    {
                        "callDataType": "DEPOSIT",
                        "from": "0x1234567890123456789012345678901234567890",
                        "to": "0x87870Bca3F3fF67225794148012b73643B78Ed36",
                        "value": "0x0",
                        "data": "0xa9059cbb000000000000000000000000dead00000000000000000000000000000000dead00000000000000000000000000000000000000000000000000000000000000000a",
                        "gasLimit": "200000",
                        "gasPrice": "3000000000",
                        "maxPriorityFeePerGas": "1000000000",
                        "maxFeePerGas": "3000000000",
                    }
                ],
                "preview": {
                    "success": True,
                    "balanceChange": [
                        {
                            "tokenType": "TOKEN",
                            "tokenSymbol": "USDT",
                            "tokenAddress": "0xdac17f958d2ee523a2206206994597c13d831ec7",
                            "tokenDecimals": "18",
                            "amount": "-1000",
                            "valueUsd": "1000.00",
                        }
                    ],
                    "feeAndContract": {
                        "estimatedNetworkFee": {
                            "amount": "0.000003056787",
                            "tokenSymbol": "BNB",
                            "valueUsd": "0.002002",
                            "rentFeeAmount": None,
                            "rentFeeValueUsd": None,
                            "priorityFeeAmount": None,
                        },
                        "interactWith": {
                            "address": "0xae05cd22df81871bc7cc2a04becfb516bfe332c8"
                        },
                    },
                    "healthFactor": {"before": "1.85", "after": "1.35"},
                    "warnings": [
                        {
                            "code": "HEALTH_FACTOR_WARNING",
                            "level": "WARN",
                            "message": "Health factor will drop below 1.5 after this transaction.",
                        }
                    ],
                    "errorMessage": "insufficient balance",
                },
                "redeemDelayDays": ["7", "10"],
            },
            "timestamp": 1748601600000,
            "success": True,
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.build_de_fi_claim_transaction(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        assert "url" in request_kwargs
        assert "/api/v1/defi/transaction/claim" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"

        self.mock_session.request.assert_called_once()
        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(BuildDeFiClaimTransactionResponse)

        if is_list and not is_flat_list:
            expected = expected_response
        elif (
            is_oneof
            or is_list
            or hasattr(BuildDeFiClaimTransactionResponse, "from_dict")
        ):
            expected = BuildDeFiClaimTransactionResponse.from_dict(expected_response)
        else:
            expected = BuildDeFiClaimTransactionResponse.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    def test_build_de_fi_claim_transaction_missing_required_param_address(self):
        """Test that build_de_fi_claim_transaction() raises RequiredError when 'address' is missing."""
        params = {
            "address": "address_example",
            "claim_type": BuildDeFiClaimTransactionClaimTypeEnum[
                "REWARD_PROTOCOL"
            ].value,
        }
        params["address"] = None

        with pytest.raises(RequiredError, match="Missing required parameter 'address'"):
            self.client.build_de_fi_claim_transaction(**params)

    def test_build_de_fi_claim_transaction_missing_required_param_claim_type(self):
        """Test that build_de_fi_claim_transaction() raises RequiredError when 'claim_type' is missing."""
        params = {
            "address": "address_example",
            "claim_type": BuildDeFiClaimTransactionClaimTypeEnum[
                "REWARD_PROTOCOL"
            ].value,
        }
        params["claim_type"] = None

        with pytest.raises(
            RequiredError, match="Missing required parameter 'claim_type'"
        ):
            self.client.build_de_fi_claim_transaction(**params)

    def test_build_de_fi_claim_transaction_server_error(self):
        """Test that build_de_fi_claim_transaction() raises an error when the server returns an error."""

        params = {
            "address": "address_example",
            "claim_type": BuildDeFiClaimTransactionClaimTypeEnum[
                "REWARD_PROTOCOL"
            ].value,
        }

        mock_error = Exception("ResponseError")
        self.client.build_de_fi_claim_transaction = MagicMock(side_effect=mock_error)

        with pytest.raises(Exception, match="ResponseError"):
            self.client.build_de_fi_claim_transaction(**params)

    @patch("binance_common.utils.web3_signature")
    def test_build_de_fi_deposit_transaction_success(self, mock_get_signature):
        """Test build_de_fi_deposit_transaction() successfully with required parameters only."""

        params = {
            "address": "0x1234567890123456789012345678901234567890",
            "investment_id": "10ab3e25d9f0b72f1f912b5d611f825bec495a74f2e1b25d8bba5fd2e56fb283",
            "token": {
                "token_address": "0x55d398326f99059fF775485246999027B3197955",
                "amount": "100",
            },
            "simulate": "True",
        }

        expected_response = {
            "code": 0,
            "msg": "success",
            "data": {
                "dataList": [
                    {
                        "callDataType": "DEPOSIT",
                        "from": "0x1234567890123456789012345678901234567890",
                        "to": "0x87870Bca3F3fF67225794148012b73643B78Ed36",
                        "value": "0x0",
                        "data": "0xa9059cbb000000000000000000000000dead00000000000000000000000000000000dead00000000000000000000000000000000000000000000000000000000000000000a",
                        "gasLimit": "200000",
                        "gasPrice": "3000000000",
                        "maxPriorityFeePerGas": "1000000000",
                        "maxFeePerGas": "3000000000",
                    }
                ],
                "preview": {
                    "success": True,
                    "balanceChange": [
                        {
                            "tokenType": "TOKEN",
                            "tokenSymbol": "USDT",
                            "tokenAddress": "0xdac17f958d2ee523a2206206994597c13d831ec7",
                            "tokenDecimals": "18",
                            "amount": "-1000",
                            "valueUsd": "1000.00",
                        }
                    ],
                    "feeAndContract": {
                        "estimatedNetworkFee": {
                            "amount": "0.000003056787",
                            "tokenSymbol": "BNB",
                            "valueUsd": "0.002002",
                            "rentFeeAmount": None,
                            "rentFeeValueUsd": None,
                            "priorityFeeAmount": None,
                        },
                        "interactWith": {
                            "address": "0xae05cd22df81871bc7cc2a04becfb516bfe332c8"
                        },
                    },
                    "healthFactor": {"before": "1.85", "after": "1.35"},
                    "warnings": [
                        {
                            "code": "HEALTH_FACTOR_WARNING",
                            "level": "WARN",
                            "message": "Health factor will drop below 1.5 after this transaction.",
                        }
                    ],
                    "errorMessage": "insufficient balance",
                },
                "redeemDelayDays": ["7", "10"],
            },
            "timestamp": 1748601600000,
            "success": True,
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.build_de_fi_deposit_transaction(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs
        parsed_params = parse_qs(request_kwargs["params"])
        camel_case_params = {snake_to_camel(k): v for k, v in params.items()}
        normalized = normalize_query_values(parsed_params, camel_case_params)

        self.mock_session.request.assert_called_once()
        mock_get_signature.assert_called_once()

        assert "url" in request_kwargs
        assert "/api/v1/defi/transaction/deposit" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"
        assert normalized["address"] == "0x1234567890123456789012345678901234567890"
        assert (
            normalized["investmentId"]
            == "10ab3e25d9f0b72f1f912b5d611f825bec495a74f2e1b25d8bba5fd2e56fb283"
        )
        assert (
            normalized["token"]
            == '{"tokenAddress":"0x55d398326f99059fF775485246999027B3197955","amount":"100"}'
        )
        assert normalized["simulate"] == "True"

        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(BuildDeFiDepositTransactionResponse)

        if is_list and not is_flat_list:
            expected = expected_response
        elif (
            is_oneof
            or is_list
            or hasattr(BuildDeFiDepositTransactionResponse, "from_dict")
        ):
            expected = BuildDeFiDepositTransactionResponse.from_dict(expected_response)
        else:
            expected = BuildDeFiDepositTransactionResponse.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    @patch("binance_common.utils.web3_signature")
    def test_build_de_fi_deposit_transaction_success_with_optional_params(
        self, mock_get_signature
    ):
        """Test build_de_fi_deposit_transaction() successfully with optional parameters."""

        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "token": (),
            "recv_window": 5000,
            "nonce": "unique-nonce-string",
            "simulate": True,
        }

        expected_response = {
            "code": 0,
            "msg": "success",
            "data": {
                "dataList": [
                    {
                        "callDataType": "DEPOSIT",
                        "from": "0x1234567890123456789012345678901234567890",
                        "to": "0x87870Bca3F3fF67225794148012b73643B78Ed36",
                        "value": "0x0",
                        "data": "0xa9059cbb000000000000000000000000dead00000000000000000000000000000000dead00000000000000000000000000000000000000000000000000000000000000000a",
                        "gasLimit": "200000",
                        "gasPrice": "3000000000",
                        "maxPriorityFeePerGas": "1000000000",
                        "maxFeePerGas": "3000000000",
                    }
                ],
                "preview": {
                    "success": True,
                    "balanceChange": [
                        {
                            "tokenType": "TOKEN",
                            "tokenSymbol": "USDT",
                            "tokenAddress": "0xdac17f958d2ee523a2206206994597c13d831ec7",
                            "tokenDecimals": "18",
                            "amount": "-1000",
                            "valueUsd": "1000.00",
                        }
                    ],
                    "feeAndContract": {
                        "estimatedNetworkFee": {
                            "amount": "0.000003056787",
                            "tokenSymbol": "BNB",
                            "valueUsd": "0.002002",
                            "rentFeeAmount": None,
                            "rentFeeValueUsd": None,
                            "priorityFeeAmount": None,
                        },
                        "interactWith": {
                            "address": "0xae05cd22df81871bc7cc2a04becfb516bfe332c8"
                        },
                    },
                    "healthFactor": {"before": "1.85", "after": "1.35"},
                    "warnings": [
                        {
                            "code": "HEALTH_FACTOR_WARNING",
                            "level": "WARN",
                            "message": "Health factor will drop below 1.5 after this transaction.",
                        }
                    ],
                    "errorMessage": "insufficient balance",
                },
                "redeemDelayDays": ["7", "10"],
            },
            "timestamp": 1748601600000,
            "success": True,
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.build_de_fi_deposit_transaction(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        assert "url" in request_kwargs
        assert "/api/v1/defi/transaction/deposit" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"

        self.mock_session.request.assert_called_once()
        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(BuildDeFiDepositTransactionResponse)

        if is_list and not is_flat_list:
            expected = expected_response
        elif (
            is_oneof
            or is_list
            or hasattr(BuildDeFiDepositTransactionResponse, "from_dict")
        ):
            expected = BuildDeFiDepositTransactionResponse.from_dict(expected_response)
        else:
            expected = BuildDeFiDepositTransactionResponse.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    def test_build_de_fi_deposit_transaction_missing_required_param_address(self):
        """Test that build_de_fi_deposit_transaction() raises RequiredError when 'address' is missing."""
        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "token": (),
        }
        params["address"] = None

        with pytest.raises(RequiredError, match="Missing required parameter 'address'"):
            self.client.build_de_fi_deposit_transaction(**params)

    def test_build_de_fi_deposit_transaction_missing_required_param_investment_id(self):
        """Test that build_de_fi_deposit_transaction() raises RequiredError when 'investment_id' is missing."""
        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "token": (),
        }
        params["investment_id"] = None

        with pytest.raises(
            RequiredError, match="Missing required parameter 'investment_id'"
        ):
            self.client.build_de_fi_deposit_transaction(**params)

    def test_build_de_fi_deposit_transaction_missing_required_param_token(self):
        """Test that build_de_fi_deposit_transaction() raises RequiredError when 'token' is missing."""
        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "token": (),
        }
        params["token"] = None

        with pytest.raises(RequiredError, match="Missing required parameter 'token'"):
            self.client.build_de_fi_deposit_transaction(**params)

    def test_build_de_fi_deposit_transaction_server_error(self):
        """Test that build_de_fi_deposit_transaction() raises an error when the server returns an error."""

        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "token": (),
        }

        mock_error = Exception("ResponseError")
        self.client.build_de_fi_deposit_transaction = MagicMock(side_effect=mock_error)

        with pytest.raises(Exception, match="ResponseError"):
            self.client.build_de_fi_deposit_transaction(**params)

    @patch("binance_common.utils.web3_signature")
    def test_build_de_fi_redeem_transaction_success(self, mock_get_signature):
        """Test build_de_fi_redeem_transaction() successfully with required parameters only."""

        params = {
            "address": "0x1234567890123456789012345678901234567890",
            "investment_id": "10ab3e25d9f0b72f1f912b5d611f825bec495a74f2e1b25d8bba5fd2e56fb283",
            "token": {
                "token_address": "0x55d398326f99059fF775485246999027B3197955",
                "amount": "100",
            },
            "ratio": "1",
            "slippage_bps": "300",
            "simulate": "True",
        }

        expected_response = {
            "code": 0,
            "msg": "success",
            "data": {
                "dataList": [
                    {
                        "callDataType": "DEPOSIT",
                        "from": "0x1234567890123456789012345678901234567890",
                        "to": "0x87870Bca3F3fF67225794148012b73643B78Ed36",
                        "value": "0x0",
                        "data": "0xa9059cbb000000000000000000000000dead00000000000000000000000000000000dead00000000000000000000000000000000000000000000000000000000000000000a",
                        "gasLimit": "200000",
                        "gasPrice": "3000000000",
                        "maxPriorityFeePerGas": "1000000000",
                        "maxFeePerGas": "3000000000",
                    }
                ],
                "preview": {
                    "success": True,
                    "balanceChange": [
                        {
                            "tokenType": "TOKEN",
                            "tokenSymbol": "USDT",
                            "tokenAddress": "0xdac17f958d2ee523a2206206994597c13d831ec7",
                            "tokenDecimals": "18",
                            "amount": "-1000",
                            "valueUsd": "1000.00",
                        }
                    ],
                    "feeAndContract": {
                        "estimatedNetworkFee": {
                            "amount": "0.000003056787",
                            "tokenSymbol": "BNB",
                            "valueUsd": "0.002002",
                            "rentFeeAmount": None,
                            "rentFeeValueUsd": None,
                            "priorityFeeAmount": None,
                        },
                        "interactWith": {
                            "address": "0xae05cd22df81871bc7cc2a04becfb516bfe332c8"
                        },
                    },
                    "healthFactor": {"before": "1.85", "after": "1.35"},
                    "warnings": [
                        {
                            "code": "HEALTH_FACTOR_WARNING",
                            "level": "WARN",
                            "message": "Health factor will drop below 1.5 after this transaction.",
                        }
                    ],
                    "errorMessage": "insufficient balance",
                },
                "redeemDelayDays": ["7", "10"],
            },
            "timestamp": 1748601600000,
            "success": True,
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.build_de_fi_redeem_transaction(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs
        parsed_params = parse_qs(request_kwargs["params"])
        camel_case_params = {snake_to_camel(k): v for k, v in params.items()}
        normalized = normalize_query_values(parsed_params, camel_case_params)

        self.mock_session.request.assert_called_once()
        mock_get_signature.assert_called_once()

        assert "url" in request_kwargs
        assert "/api/v1/defi/transaction/redeem" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"
        assert normalized["address"] == "0x1234567890123456789012345678901234567890"
        assert (
            normalized["investmentId"]
            == "10ab3e25d9f0b72f1f912b5d611f825bec495a74f2e1b25d8bba5fd2e56fb283"
        )
        assert (
            normalized["token"]
            == '{"tokenAddress":"0x55d398326f99059fF775485246999027B3197955","amount":"100"}'
        )
        assert normalized["ratio"] == "1"
        assert normalized["slippageBps"] == "300"
        assert normalized["simulate"] == "True"

        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(BuildDeFiRedeemTransactionResponse)

        if is_list and not is_flat_list:
            expected = expected_response
        elif (
            is_oneof
            or is_list
            or hasattr(BuildDeFiRedeemTransactionResponse, "from_dict")
        ):
            expected = BuildDeFiRedeemTransactionResponse.from_dict(expected_response)
        else:
            expected = BuildDeFiRedeemTransactionResponse.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    @patch("binance_common.utils.web3_signature")
    def test_build_de_fi_redeem_transaction_success_with_optional_params(
        self, mock_get_signature
    ):
        """Test build_de_fi_redeem_transaction() successfully with optional parameters."""

        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "recv_window": 5000,
            "nonce": "unique-nonce-string",
            "token": (),
            "ratio": "ratio_example",
            "slippage_bps": "slippage_bps_example",
            "simulate": True,
        }

        expected_response = {
            "code": 0,
            "msg": "success",
            "data": {
                "dataList": [
                    {
                        "callDataType": "DEPOSIT",
                        "from": "0x1234567890123456789012345678901234567890",
                        "to": "0x87870Bca3F3fF67225794148012b73643B78Ed36",
                        "value": "0x0",
                        "data": "0xa9059cbb000000000000000000000000dead00000000000000000000000000000000dead00000000000000000000000000000000000000000000000000000000000000000a",
                        "gasLimit": "200000",
                        "gasPrice": "3000000000",
                        "maxPriorityFeePerGas": "1000000000",
                        "maxFeePerGas": "3000000000",
                    }
                ],
                "preview": {
                    "success": True,
                    "balanceChange": [
                        {
                            "tokenType": "TOKEN",
                            "tokenSymbol": "USDT",
                            "tokenAddress": "0xdac17f958d2ee523a2206206994597c13d831ec7",
                            "tokenDecimals": "18",
                            "amount": "-1000",
                            "valueUsd": "1000.00",
                        }
                    ],
                    "feeAndContract": {
                        "estimatedNetworkFee": {
                            "amount": "0.000003056787",
                            "tokenSymbol": "BNB",
                            "valueUsd": "0.002002",
                            "rentFeeAmount": None,
                            "rentFeeValueUsd": None,
                            "priorityFeeAmount": None,
                        },
                        "interactWith": {
                            "address": "0xae05cd22df81871bc7cc2a04becfb516bfe332c8"
                        },
                    },
                    "healthFactor": {"before": "1.85", "after": "1.35"},
                    "warnings": [
                        {
                            "code": "HEALTH_FACTOR_WARNING",
                            "level": "WARN",
                            "message": "Health factor will drop below 1.5 after this transaction.",
                        }
                    ],
                    "errorMessage": "insufficient balance",
                },
                "redeemDelayDays": ["7", "10"],
            },
            "timestamp": 1748601600000,
            "success": True,
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.build_de_fi_redeem_transaction(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        assert "url" in request_kwargs
        assert "/api/v1/defi/transaction/redeem" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"

        self.mock_session.request.assert_called_once()
        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(BuildDeFiRedeemTransactionResponse)

        if is_list and not is_flat_list:
            expected = expected_response
        elif (
            is_oneof
            or is_list
            or hasattr(BuildDeFiRedeemTransactionResponse, "from_dict")
        ):
            expected = BuildDeFiRedeemTransactionResponse.from_dict(expected_response)
        else:
            expected = BuildDeFiRedeemTransactionResponse.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    def test_build_de_fi_redeem_transaction_missing_required_param_address(self):
        """Test that build_de_fi_redeem_transaction() raises RequiredError when 'address' is missing."""
        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
        }
        params["address"] = None

        with pytest.raises(RequiredError, match="Missing required parameter 'address'"):
            self.client.build_de_fi_redeem_transaction(**params)

    def test_build_de_fi_redeem_transaction_missing_required_param_investment_id(self):
        """Test that build_de_fi_redeem_transaction() raises RequiredError when 'investment_id' is missing."""
        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
        }
        params["investment_id"] = None

        with pytest.raises(
            RequiredError, match="Missing required parameter 'investment_id'"
        ):
            self.client.build_de_fi_redeem_transaction(**params)

    def test_build_de_fi_redeem_transaction_server_error(self):
        """Test that build_de_fi_redeem_transaction() raises an error when the server returns an error."""

        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
        }

        mock_error = Exception("ResponseError")
        self.client.build_de_fi_redeem_transaction = MagicMock(side_effect=mock_error)

        with pytest.raises(Exception, match="ResponseError"):
            self.client.build_de_fi_redeem_transaction(**params)

    @patch("binance_common.utils.web3_signature")
    def test_build_lp_add_transaction_success(self, mock_get_signature):
        """Test build_lp_add_transaction() successfully with required parameters only."""

        params = {
            "address": "0x1234567890123456789012345678901234567890",
            "investment_id": "6a3522eee3f2fc4fa9cc1273603429ba95ebd9ff4d33fad8a14d39b9a0a6ce3a",
            "token_list": [
                {
                    "token_address": "0x55d398326f99059fF775485246999027B3197955",
                    "amount": "10",
                },
                {
                    "token_address": "0xf1686b0b45114bcec963b139344a54cefae09a58",
                    "amount": "20",
                },
            ],
            "tick_lower": "-100",
            "tick_upper": "100",
            "price_range": "5",
            "nft_id": "123456",
            "slippage_bps": "300",
            "simulate": "True",
        }

        expected_response = {
            "code": 0,
            "msg": "success",
            "data": {
                "dataList": [
                    {
                        "callDataType": "DEPOSIT",
                        "from": "0x1234567890123456789012345678901234567890",
                        "to": "0x87870Bca3F3fF67225794148012b73643B78Ed36",
                        "value": "0x0",
                        "data": "0xa9059cbb000000000000000000000000dead00000000000000000000000000000000dead00000000000000000000000000000000000000000000000000000000000000000a",
                        "gasLimit": "200000",
                        "gasPrice": "3000000000",
                        "maxPriorityFeePerGas": "1000000000",
                        "maxFeePerGas": "3000000000",
                    }
                ],
                "preview": {
                    "success": True,
                    "balanceChange": [
                        {
                            "tokenType": "TOKEN",
                            "tokenSymbol": "USDT",
                            "tokenAddress": "0xdac17f958d2ee523a2206206994597c13d831ec7",
                            "tokenDecimals": "18",
                            "amount": "-1000",
                            "valueUsd": "1000.00",
                        }
                    ],
                    "feeAndContract": {
                        "estimatedNetworkFee": {
                            "amount": "0.000003056787",
                            "tokenSymbol": "BNB",
                            "valueUsd": "0.002002",
                            "rentFeeAmount": None,
                            "rentFeeValueUsd": None,
                            "priorityFeeAmount": None,
                        },
                        "interactWith": {
                            "address": "0xae05cd22df81871bc7cc2a04becfb516bfe332c8"
                        },
                    },
                    "healthFactor": {"before": "1.85", "after": "1.35"},
                    "warnings": [
                        {
                            "code": "HEALTH_FACTOR_WARNING",
                            "level": "WARN",
                            "message": "Health factor will drop below 1.5 after this transaction.",
                        }
                    ],
                    "errorMessage": "insufficient balance",
                },
                "redeemDelayDays": ["7", "10"],
            },
            "timestamp": 1748601600000,
            "success": True,
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.build_lp_add_transaction(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs
        parsed_params = parse_qs(request_kwargs["params"])
        camel_case_params = {snake_to_camel(k): v for k, v in params.items()}
        normalized = normalize_query_values(parsed_params, camel_case_params)

        self.mock_session.request.assert_called_once()
        mock_get_signature.assert_called_once()

        assert "url" in request_kwargs
        assert "/api/v1/defi/transaction/lp-add" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"
        assert normalized["address"] == "0x1234567890123456789012345678901234567890"
        assert (
            normalized["investmentId"]
            == "6a3522eee3f2fc4fa9cc1273603429ba95ebd9ff4d33fad8a14d39b9a0a6ce3a"
        )
        assert (
            normalized["tokenList"]
            == '[{"tokenAddress":"0x55d398326f99059fF775485246999027B3197955","amount":"10"},{"tokenAddress":"0xf1686b0b45114bcec963b139344a54cefae09a58","amount":"20"}]'
        )
        assert normalized["tickLower"] == "-100"
        assert normalized["tickUpper"] == "100"
        assert normalized["priceRange"] == "5"
        assert normalized["nftId"] == "123456"
        assert normalized["slippageBps"] == "300"
        assert normalized["simulate"] == "True"

        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(BuildLpAddTransactionResponse)

        if is_list and not is_flat_list:
            expected = expected_response
        elif is_oneof or is_list or hasattr(BuildLpAddTransactionResponse, "from_dict"):
            expected = BuildLpAddTransactionResponse.from_dict(expected_response)
        else:
            expected = BuildLpAddTransactionResponse.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    @patch("binance_common.utils.web3_signature")
    def test_build_lp_add_transaction_success_with_optional_params(
        self, mock_get_signature
    ):
        """Test build_lp_add_transaction() successfully with optional parameters."""

        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "token_list": [
                BuildLpAddTransactionRequestTokenListInner(
                    token_address="0x55d398326f99059fF775485246999027B3197955",
                    amount="100",
                )
            ],
            "recv_window": 5000,
            "nonce": "unique-nonce-string",
            "tick_lower": "tick_lower_example",
            "tick_upper": "tick_upper_example",
            "price_range": "price_range_example",
            "nft_id": "nft_id_example",
            "slippage_bps": "slippage_bps_example",
            "simulate": True,
        }

        expected_response = {
            "code": 0,
            "msg": "success",
            "data": {
                "dataList": [
                    {
                        "callDataType": "DEPOSIT",
                        "from": "0x1234567890123456789012345678901234567890",
                        "to": "0x87870Bca3F3fF67225794148012b73643B78Ed36",
                        "value": "0x0",
                        "data": "0xa9059cbb000000000000000000000000dead00000000000000000000000000000000dead00000000000000000000000000000000000000000000000000000000000000000a",
                        "gasLimit": "200000",
                        "gasPrice": "3000000000",
                        "maxPriorityFeePerGas": "1000000000",
                        "maxFeePerGas": "3000000000",
                    }
                ],
                "preview": {
                    "success": True,
                    "balanceChange": [
                        {
                            "tokenType": "TOKEN",
                            "tokenSymbol": "USDT",
                            "tokenAddress": "0xdac17f958d2ee523a2206206994597c13d831ec7",
                            "tokenDecimals": "18",
                            "amount": "-1000",
                            "valueUsd": "1000.00",
                        }
                    ],
                    "feeAndContract": {
                        "estimatedNetworkFee": {
                            "amount": "0.000003056787",
                            "tokenSymbol": "BNB",
                            "valueUsd": "0.002002",
                            "rentFeeAmount": None,
                            "rentFeeValueUsd": None,
                            "priorityFeeAmount": None,
                        },
                        "interactWith": {
                            "address": "0xae05cd22df81871bc7cc2a04becfb516bfe332c8"
                        },
                    },
                    "healthFactor": {"before": "1.85", "after": "1.35"},
                    "warnings": [
                        {
                            "code": "HEALTH_FACTOR_WARNING",
                            "level": "WARN",
                            "message": "Health factor will drop below 1.5 after this transaction.",
                        }
                    ],
                    "errorMessage": "insufficient balance",
                },
                "redeemDelayDays": ["7", "10"],
            },
            "timestamp": 1748601600000,
            "success": True,
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.build_lp_add_transaction(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        assert "url" in request_kwargs
        assert "/api/v1/defi/transaction/lp-add" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"

        self.mock_session.request.assert_called_once()
        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(BuildLpAddTransactionResponse)

        if is_list and not is_flat_list:
            expected = expected_response
        elif is_oneof or is_list or hasattr(BuildLpAddTransactionResponse, "from_dict"):
            expected = BuildLpAddTransactionResponse.from_dict(expected_response)
        else:
            expected = BuildLpAddTransactionResponse.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    def test_build_lp_add_transaction_missing_required_param_address(self):
        """Test that build_lp_add_transaction() raises RequiredError when 'address' is missing."""
        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "token_list": [
                BuildLpAddTransactionRequestTokenListInner(
                    token_address="0x55d398326f99059fF775485246999027B3197955",
                    amount="100",
                )
            ],
        }
        params["address"] = None

        with pytest.raises(RequiredError, match="Missing required parameter 'address'"):
            self.client.build_lp_add_transaction(**params)

    def test_build_lp_add_transaction_missing_required_param_investment_id(self):
        """Test that build_lp_add_transaction() raises RequiredError when 'investment_id' is missing."""
        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "token_list": [
                BuildLpAddTransactionRequestTokenListInner(
                    token_address="0x55d398326f99059fF775485246999027B3197955",
                    amount="100",
                )
            ],
        }
        params["investment_id"] = None

        with pytest.raises(
            RequiredError, match="Missing required parameter 'investment_id'"
        ):
            self.client.build_lp_add_transaction(**params)

    def test_build_lp_add_transaction_missing_required_param_token_list(self):
        """Test that build_lp_add_transaction() raises RequiredError when 'token_list' is missing."""
        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "token_list": [
                BuildLpAddTransactionRequestTokenListInner(
                    token_address="0x55d398326f99059fF775485246999027B3197955",
                    amount="100",
                )
            ],
        }
        params["token_list"] = None

        with pytest.raises(
            RequiredError, match="Missing required parameter 'token_list'"
        ):
            self.client.build_lp_add_transaction(**params)

    def test_build_lp_add_transaction_server_error(self):
        """Test that build_lp_add_transaction() raises an error when the server returns an error."""

        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "token_list": [
                BuildLpAddTransactionRequestTokenListInner(
                    token_address="0x55d398326f99059fF775485246999027B3197955",
                    amount="100",
                )
            ],
        }

        mock_error = Exception("ResponseError")
        self.client.build_lp_add_transaction = MagicMock(side_effect=mock_error)

        with pytest.raises(Exception, match="ResponseError"):
            self.client.build_lp_add_transaction(**params)

    @patch("binance_common.utils.web3_signature")
    def test_build_lp_remove_transaction_success(self, mock_get_signature):
        """Test build_lp_remove_transaction() successfully with required parameters only."""

        params = {
            "address": "0x1234567890123456789012345678901234567890",
            "investment_id": "6a3522eee3f2fc4fa9cc1273603429ba95ebd9ff4d33fad8a14d39b9a0a6ce3a",
            "nft_id": "123456",
            "ratio": "1",
            "slippage_bps": "300",
            "simulate": "True",
        }

        expected_response = {
            "code": 0,
            "msg": "success",
            "data": {
                "dataList": [
                    {
                        "callDataType": "DEPOSIT",
                        "from": "0x1234567890123456789012345678901234567890",
                        "to": "0x87870Bca3F3fF67225794148012b73643B78Ed36",
                        "value": "0x0",
                        "data": "0xa9059cbb000000000000000000000000dead00000000000000000000000000000000dead00000000000000000000000000000000000000000000000000000000000000000a",
                        "gasLimit": "200000",
                        "gasPrice": "3000000000",
                        "maxPriorityFeePerGas": "1000000000",
                        "maxFeePerGas": "3000000000",
                    }
                ],
                "preview": {
                    "success": True,
                    "balanceChange": [
                        {
                            "tokenType": "TOKEN",
                            "tokenSymbol": "USDT",
                            "tokenAddress": "0xdac17f958d2ee523a2206206994597c13d831ec7",
                            "tokenDecimals": "18",
                            "amount": "-1000",
                            "valueUsd": "1000.00",
                        }
                    ],
                    "feeAndContract": {
                        "estimatedNetworkFee": {
                            "amount": "0.000003056787",
                            "tokenSymbol": "BNB",
                            "valueUsd": "0.002002",
                            "rentFeeAmount": None,
                            "rentFeeValueUsd": None,
                            "priorityFeeAmount": None,
                        },
                        "interactWith": {
                            "address": "0xae05cd22df81871bc7cc2a04becfb516bfe332c8"
                        },
                    },
                    "healthFactor": {"before": "1.85", "after": "1.35"},
                    "warnings": [
                        {
                            "code": "HEALTH_FACTOR_WARNING",
                            "level": "WARN",
                            "message": "Health factor will drop below 1.5 after this transaction.",
                        }
                    ],
                    "errorMessage": "insufficient balance",
                },
                "redeemDelayDays": ["7", "10"],
            },
            "timestamp": 1748601600000,
            "success": True,
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.build_lp_remove_transaction(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs
        parsed_params = parse_qs(request_kwargs["params"])
        camel_case_params = {snake_to_camel(k): v for k, v in params.items()}
        normalized = normalize_query_values(parsed_params, camel_case_params)

        self.mock_session.request.assert_called_once()
        mock_get_signature.assert_called_once()

        assert "url" in request_kwargs
        assert "/api/v1/defi/transaction/lp-remove" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"
        assert normalized["address"] == "0x1234567890123456789012345678901234567890"
        assert (
            normalized["investmentId"]
            == "6a3522eee3f2fc4fa9cc1273603429ba95ebd9ff4d33fad8a14d39b9a0a6ce3a"
        )
        assert normalized["nftId"] == "123456"
        assert normalized["ratio"] == "1"
        assert normalized["slippageBps"] == "300"
        assert normalized["simulate"] == "True"

        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(BuildLpRemoveTransactionResponse)

        if is_list and not is_flat_list:
            expected = expected_response
        elif (
            is_oneof
            or is_list
            or hasattr(BuildLpRemoveTransactionResponse, "from_dict")
        ):
            expected = BuildLpRemoveTransactionResponse.from_dict(expected_response)
        else:
            expected = BuildLpRemoveTransactionResponse.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    @patch("binance_common.utils.web3_signature")
    def test_build_lp_remove_transaction_success_with_optional_params(
        self, mock_get_signature
    ):
        """Test build_lp_remove_transaction() successfully with optional parameters."""

        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "nft_id": "nft_id_example",
            "ratio": "ratio_example",
            "recv_window": 5000,
            "nonce": "unique-nonce-string",
            "slippage_bps": "slippage_bps_example",
            "simulate": True,
        }

        expected_response = {
            "code": 0,
            "msg": "success",
            "data": {
                "dataList": [
                    {
                        "callDataType": "DEPOSIT",
                        "from": "0x1234567890123456789012345678901234567890",
                        "to": "0x87870Bca3F3fF67225794148012b73643B78Ed36",
                        "value": "0x0",
                        "data": "0xa9059cbb000000000000000000000000dead00000000000000000000000000000000dead00000000000000000000000000000000000000000000000000000000000000000a",
                        "gasLimit": "200000",
                        "gasPrice": "3000000000",
                        "maxPriorityFeePerGas": "1000000000",
                        "maxFeePerGas": "3000000000",
                    }
                ],
                "preview": {
                    "success": True,
                    "balanceChange": [
                        {
                            "tokenType": "TOKEN",
                            "tokenSymbol": "USDT",
                            "tokenAddress": "0xdac17f958d2ee523a2206206994597c13d831ec7",
                            "tokenDecimals": "18",
                            "amount": "-1000",
                            "valueUsd": "1000.00",
                        }
                    ],
                    "feeAndContract": {
                        "estimatedNetworkFee": {
                            "amount": "0.000003056787",
                            "tokenSymbol": "BNB",
                            "valueUsd": "0.002002",
                            "rentFeeAmount": None,
                            "rentFeeValueUsd": None,
                            "priorityFeeAmount": None,
                        },
                        "interactWith": {
                            "address": "0xae05cd22df81871bc7cc2a04becfb516bfe332c8"
                        },
                    },
                    "healthFactor": {"before": "1.85", "after": "1.35"},
                    "warnings": [
                        {
                            "code": "HEALTH_FACTOR_WARNING",
                            "level": "WARN",
                            "message": "Health factor will drop below 1.5 after this transaction.",
                        }
                    ],
                    "errorMessage": "insufficient balance",
                },
                "redeemDelayDays": ["7", "10"],
            },
            "timestamp": 1748601600000,
            "success": True,
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.build_lp_remove_transaction(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        assert "url" in request_kwargs
        assert "/api/v1/defi/transaction/lp-remove" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"

        self.mock_session.request.assert_called_once()
        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(BuildLpRemoveTransactionResponse)

        if is_list and not is_flat_list:
            expected = expected_response
        elif (
            is_oneof
            or is_list
            or hasattr(BuildLpRemoveTransactionResponse, "from_dict")
        ):
            expected = BuildLpRemoveTransactionResponse.from_dict(expected_response)
        else:
            expected = BuildLpRemoveTransactionResponse.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    def test_build_lp_remove_transaction_missing_required_param_address(self):
        """Test that build_lp_remove_transaction() raises RequiredError when 'address' is missing."""
        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "nft_id": "nft_id_example",
            "ratio": "ratio_example",
        }
        params["address"] = None

        with pytest.raises(RequiredError, match="Missing required parameter 'address'"):
            self.client.build_lp_remove_transaction(**params)

    def test_build_lp_remove_transaction_missing_required_param_investment_id(self):
        """Test that build_lp_remove_transaction() raises RequiredError when 'investment_id' is missing."""
        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "nft_id": "nft_id_example",
            "ratio": "ratio_example",
        }
        params["investment_id"] = None

        with pytest.raises(
            RequiredError, match="Missing required parameter 'investment_id'"
        ):
            self.client.build_lp_remove_transaction(**params)

    def test_build_lp_remove_transaction_missing_required_param_nft_id(self):
        """Test that build_lp_remove_transaction() raises RequiredError when 'nft_id' is missing."""
        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "nft_id": "nft_id_example",
            "ratio": "ratio_example",
        }
        params["nft_id"] = None

        with pytest.raises(RequiredError, match="Missing required parameter 'nft_id'"):
            self.client.build_lp_remove_transaction(**params)

    def test_build_lp_remove_transaction_missing_required_param_ratio(self):
        """Test that build_lp_remove_transaction() raises RequiredError when 'ratio' is missing."""
        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "nft_id": "nft_id_example",
            "ratio": "ratio_example",
        }
        params["ratio"] = None

        with pytest.raises(RequiredError, match="Missing required parameter 'ratio'"):
            self.client.build_lp_remove_transaction(**params)

    def test_build_lp_remove_transaction_server_error(self):
        """Test that build_lp_remove_transaction() raises an error when the server returns an error."""

        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "nft_id": "nft_id_example",
            "ratio": "ratio_example",
        }

        mock_error = Exception("ResponseError")
        self.client.build_lp_remove_transaction = MagicMock(side_effect=mock_error)

        with pytest.raises(Exception, match="ResponseError"):
            self.client.build_lp_remove_transaction(**params)

    @patch("binance_common.utils.web3_signature")
    def test_calculate_lp_add_paired_amounts_success(self, mock_get_signature):
        """Test calculate_lp_add_paired_amounts() successfully with required parameters only."""

        params = {
            "address": "0x1234567890123456789012345678901234567890",
            "investment_id": "6a3522eee3f2fc4fa9cc1273603429ba95ebd9ff4d33fad8a14d39b9a0a6ce3a",
            "tick_lower": "-100",
            "tick_upper": "100",
            "price_range": "5",
            "nft_id": "123456",
            "input_token": {
                "token_address": "0x55d398326f99059fF775485246999027B3197955",
                "amount": "100",
            },
        }

        expected_response = {
            "code": 0,
            "msg": "success",
            "data": {
                "inputTokenAmount": "10",
                "pairedTokenAddress": "0xf1686b0b45114bcec963b139344a54cefae09a58",
                "pairedTokenAmount": "20",
            },
            "timestamp": 1748601600000,
            "success": True,
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.calculate_lp_add_paired_amounts(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs
        parsed_params = parse_qs(request_kwargs["params"])
        camel_case_params = {snake_to_camel(k): v for k, v in params.items()}
        normalized = normalize_query_values(parsed_params, camel_case_params)

        self.mock_session.request.assert_called_once()
        mock_get_signature.assert_called_once()

        assert "url" in request_kwargs
        assert "/api/v1/defi/transaction/lp-add/calculate" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"
        assert normalized["address"] == "0x1234567890123456789012345678901234567890"
        assert (
            normalized["investmentId"]
            == "6a3522eee3f2fc4fa9cc1273603429ba95ebd9ff4d33fad8a14d39b9a0a6ce3a"
        )
        assert normalized["tickLower"] == "-100"
        assert normalized["tickUpper"] == "100"
        assert normalized["priceRange"] == "5"
        assert normalized["nftId"] == "123456"
        assert (
            normalized["inputToken"]
            == '{"tokenAddress":"0x55d398326f99059fF775485246999027B3197955","amount":"100"}'
        )

        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(CalculateLpAddPairedAmountsResponse)

        if is_list and not is_flat_list:
            expected = expected_response
        elif (
            is_oneof
            or is_list
            or hasattr(CalculateLpAddPairedAmountsResponse, "from_dict")
        ):
            expected = CalculateLpAddPairedAmountsResponse.from_dict(expected_response)
        else:
            expected = CalculateLpAddPairedAmountsResponse.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    @patch("binance_common.utils.web3_signature")
    def test_calculate_lp_add_paired_amounts_success_with_optional_params(
        self, mock_get_signature
    ):
        """Test calculate_lp_add_paired_amounts() successfully with optional parameters."""

        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "input_token": (),
            "recv_window": 5000,
            "nonce": "unique-nonce-string",
            "tick_lower": "tick_lower_example",
            "tick_upper": "tick_upper_example",
            "price_range": "price_range_example",
            "nft_id": "nft_id_example",
        }

        expected_response = {
            "code": 0,
            "msg": "success",
            "data": {
                "inputTokenAmount": "10",
                "pairedTokenAddress": "0xf1686b0b45114bcec963b139344a54cefae09a58",
                "pairedTokenAmount": "20",
            },
            "timestamp": 1748601600000,
            "success": True,
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.calculate_lp_add_paired_amounts(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        assert "url" in request_kwargs
        assert "/api/v1/defi/transaction/lp-add/calculate" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"

        self.mock_session.request.assert_called_once()
        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(CalculateLpAddPairedAmountsResponse)

        if is_list and not is_flat_list:
            expected = expected_response
        elif (
            is_oneof
            or is_list
            or hasattr(CalculateLpAddPairedAmountsResponse, "from_dict")
        ):
            expected = CalculateLpAddPairedAmountsResponse.from_dict(expected_response)
        else:
            expected = CalculateLpAddPairedAmountsResponse.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    def test_calculate_lp_add_paired_amounts_missing_required_param_address(self):
        """Test that calculate_lp_add_paired_amounts() raises RequiredError when 'address' is missing."""
        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "input_token": (),
        }
        params["address"] = None

        with pytest.raises(RequiredError, match="Missing required parameter 'address'"):
            self.client.calculate_lp_add_paired_amounts(**params)

    def test_calculate_lp_add_paired_amounts_missing_required_param_investment_id(self):
        """Test that calculate_lp_add_paired_amounts() raises RequiredError when 'investment_id' is missing."""
        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "input_token": (),
        }
        params["investment_id"] = None

        with pytest.raises(
            RequiredError, match="Missing required parameter 'investment_id'"
        ):
            self.client.calculate_lp_add_paired_amounts(**params)

    def test_calculate_lp_add_paired_amounts_missing_required_param_input_token(self):
        """Test that calculate_lp_add_paired_amounts() raises RequiredError when 'input_token' is missing."""
        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "input_token": (),
        }
        params["input_token"] = None

        with pytest.raises(
            RequiredError, match="Missing required parameter 'input_token'"
        ):
            self.client.calculate_lp_add_paired_amounts(**params)

    def test_calculate_lp_add_paired_amounts_server_error(self):
        """Test that calculate_lp_add_paired_amounts() raises an error when the server returns an error."""

        params = {
            "address": "address_example",
            "investment_id": "investment_id_example",
            "input_token": (),
        }

        mock_error = Exception("ResponseError")
        self.client.calculate_lp_add_paired_amounts = MagicMock(side_effect=mock_error)

        with pytest.raises(Exception, match="ResponseError"):
            self.client.calculate_lp_add_paired_amounts(**params)
