"""
Binance Web3 Wallet REST API

Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
import pytest
import requests

from unittest.mock import MagicMock, patch
from urllib.parse import parse_qs

from binance_common.configuration import ConfigurationRestAPI
from binance_common.errors import RequiredError
from binance_common.utils import normalize_query_values, is_one_of_model, snake_to_camel

from binance_sdk_web3_wallet.rest_api.api import B402PaymentsApi
from binance_sdk_web3_wallet.rest_api.models import (
    GetB402SupportedConfigurationsV1Response,
)
from binance_sdk_web3_wallet.rest_api.models import (
    GetB402SupportedConfigurationsV2Response,
)
from binance_sdk_web3_wallet.rest_api.models import SettleB402PaymentV1Response
from binance_sdk_web3_wallet.rest_api.models import SettleB402PaymentV2Response
from binance_sdk_web3_wallet.rest_api.models import VerifyB402PaymentV1Response
from binance_sdk_web3_wallet.rest_api.models import VerifyB402PaymentV2Response


class TestB402PaymentsApi:
    @pytest.fixture(autouse=True)
    def setup_client(self):
        """Setup a client instance with mocked session before each test method."""
        self.mock_session = MagicMock(spec=requests.Session)
        config = ConfigurationRestAPI(
            api_key="test-api-key",
            api_secret="test-api-secret",
        )
        self.client = B402PaymentsApi(configuration=config, session=self.mock_session)

    def set_mock_response(self, data: dict = {}, status_code=200, headers=None):
        """Helper method to setup mock response for the client's session request."""
        if headers is None:
            headers = {}

        mock_response = MagicMock()
        mock_response.status_code = status_code
        mock_response.json.return_value = data
        mock_response.text = json.dumps(data)
        mock_response.headers = headers

        self.mock_session.request.return_value = mock_response

    @patch("binance_common.utils.web3_signature")
    def test_get_b402_supported_configurations_v1_success(self, mock_get_signature):
        """Test get_b402_supported_configurations_v1() successfully with required parameters only."""

        params = {
            "body": {},
        }

        expected_response = {
            "status": "OK",
            "type": "GENERAL",
            "code": "000000000",
            "errorData": "errorData",
            "data": {
                "kinds": [
                    {
                        "scheme": "exact",
                        "network": "eip155:56",
                        "extra": {
                            "name": "Token Name",
                            "version": "1",
                            "facilitatorAddress": "0x3333333333333333333333333333333333333333",
                        },
                    }
                ],
                "extensions": [],
                "signers": {
                    "eip155:56": ["0x3333333333333333333333333333333333333333"]
                },
            },
            "subData": {},
            "params": {},
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.get_b402_supported_configurations_v1(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        self.mock_session.request.assert_called_once()
        mock_get_signature.assert_called_once()

        assert "url" in request_kwargs
        assert "/api/v1/b402/supported" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"

        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(GetB402SupportedConfigurationsV1Response)

        if is_list and not is_flat_list:
            expected = expected_response
        elif (
            is_oneof
            or is_list
            or hasattr(GetB402SupportedConfigurationsV1Response, "from_dict")
        ):
            expected = GetB402SupportedConfigurationsV1Response.from_dict(
                expected_response
            )
        else:
            expected = GetB402SupportedConfigurationsV1Response.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    @patch("binance_common.utils.web3_signature")
    def test_get_b402_supported_configurations_v1_success_with_optional_params(
        self, mock_get_signature
    ):
        """Test get_b402_supported_configurations_v1() successfully with optional parameters."""

        params = {"body": {}, "recv_window": 5000, "nonce": "unique-nonce-string"}

        expected_response = {
            "status": "OK",
            "type": "GENERAL",
            "code": "000000000",
            "errorData": "errorData",
            "data": {
                "kinds": [
                    {
                        "scheme": "exact",
                        "network": "eip155:56",
                        "extra": {
                            "name": "Token Name",
                            "version": "1",
                            "facilitatorAddress": "0x3333333333333333333333333333333333333333",
                        },
                    }
                ],
                "extensions": [],
                "signers": {
                    "eip155:56": ["0x3333333333333333333333333333333333333333"]
                },
            },
            "subData": {},
            "params": {},
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.get_b402_supported_configurations_v1(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        assert "url" in request_kwargs
        assert "/api/v1/b402/supported" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"

        self.mock_session.request.assert_called_once()
        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(GetB402SupportedConfigurationsV1Response)

        if is_list and not is_flat_list:
            expected = expected_response
        elif (
            is_oneof
            or is_list
            or hasattr(GetB402SupportedConfigurationsV1Response, "from_dict")
        ):
            expected = GetB402SupportedConfigurationsV1Response.from_dict(
                expected_response
            )
        else:
            expected = GetB402SupportedConfigurationsV1Response.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    def test_get_b402_supported_configurations_v1_missing_required_param_body(self):
        """Test that get_b402_supported_configurations_v1() raises RequiredError when 'body' is missing."""
        params = {
            "body": {},
        }
        params["body"] = None

        with pytest.raises(RequiredError, match="Missing required parameter 'body'"):
            self.client.get_b402_supported_configurations_v1(**params)

    def test_get_b402_supported_configurations_v1_server_error(self):
        """Test that get_b402_supported_configurations_v1() raises an error when the server returns an error."""

        params = {
            "body": {},
        }

        mock_error = Exception("ResponseError")
        self.client.get_b402_supported_configurations_v1 = MagicMock(
            side_effect=mock_error
        )

        with pytest.raises(Exception, match="ResponseError"):
            self.client.get_b402_supported_configurations_v1(**params)

    @patch("binance_common.utils.web3_signature")
    def test_get_b402_supported_configurations_v2_success(self, mock_get_signature):
        """Test get_b402_supported_configurations_v2() successfully with required parameters only."""

        params = {
            "body": {},
        }

        expected_response = {
            "status": "OK",
            "type": "GENERAL",
            "code": "000000000",
            "errorData": "errorData",
            "data": {
                "kinds": [
                    {
                        "network": "eip155:56",
                        "extra": {
                            "name": "Token Name",
                            "version": "1",
                            "signerAddress": "0x3333333333333333333333333333333333333333",
                            "spenderAddress": "0x4444444444444444444444444444444444444444",
                        },
                    }
                ],
                "extensions": [],
                "signers": {"eip155:*": ["0x3333333333333333333333333333333333333333"]},
            },
            "subData": {},
            "params": {},
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.get_b402_supported_configurations_v2(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        self.mock_session.request.assert_called_once()
        mock_get_signature.assert_called_once()

        assert "url" in request_kwargs
        assert "/api/v2/b402/supported" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"

        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(GetB402SupportedConfigurationsV2Response)

        if is_list and not is_flat_list:
            expected = expected_response
        elif (
            is_oneof
            or is_list
            or hasattr(GetB402SupportedConfigurationsV2Response, "from_dict")
        ):
            expected = GetB402SupportedConfigurationsV2Response.from_dict(
                expected_response
            )
        else:
            expected = GetB402SupportedConfigurationsV2Response.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    @patch("binance_common.utils.web3_signature")
    def test_get_b402_supported_configurations_v2_success_with_optional_params(
        self, mock_get_signature
    ):
        """Test get_b402_supported_configurations_v2() successfully with optional parameters."""

        params = {"body": {}, "recv_window": 5000, "nonce": "unique-nonce-string"}

        expected_response = {
            "status": "OK",
            "type": "GENERAL",
            "code": "000000000",
            "errorData": "errorData",
            "data": {
                "kinds": [
                    {
                        "network": "eip155:56",
                        "extra": {
                            "name": "Token Name",
                            "version": "1",
                            "signerAddress": "0x3333333333333333333333333333333333333333",
                            "spenderAddress": "0x4444444444444444444444444444444444444444",
                        },
                    }
                ],
                "extensions": [],
                "signers": {"eip155:*": ["0x3333333333333333333333333333333333333333"]},
            },
            "subData": {},
            "params": {},
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.get_b402_supported_configurations_v2(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        assert "url" in request_kwargs
        assert "/api/v2/b402/supported" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"

        self.mock_session.request.assert_called_once()
        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(GetB402SupportedConfigurationsV2Response)

        if is_list and not is_flat_list:
            expected = expected_response
        elif (
            is_oneof
            or is_list
            or hasattr(GetB402SupportedConfigurationsV2Response, "from_dict")
        ):
            expected = GetB402SupportedConfigurationsV2Response.from_dict(
                expected_response
            )
        else:
            expected = GetB402SupportedConfigurationsV2Response.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    def test_get_b402_supported_configurations_v2_missing_required_param_body(self):
        """Test that get_b402_supported_configurations_v2() raises RequiredError when 'body' is missing."""
        params = {
            "body": {},
        }
        params["body"] = None

        with pytest.raises(RequiredError, match="Missing required parameter 'body'"):
            self.client.get_b402_supported_configurations_v2(**params)

    def test_get_b402_supported_configurations_v2_server_error(self):
        """Test that get_b402_supported_configurations_v2() raises an error when the server returns an error."""

        params = {
            "body": {},
        }

        mock_error = Exception("ResponseError")
        self.client.get_b402_supported_configurations_v2 = MagicMock(
            side_effect=mock_error
        )

        with pytest.raises(Exception, match="ResponseError"):
            self.client.get_b402_supported_configurations_v2(**params)

    @patch("binance_common.utils.web3_signature")
    def test_settle_b402_payment_v1_success(self, mock_get_signature):
        """Test settle_b402_payment_v1() successfully with required parameters only."""

        params = {
            "body": (),
        }

        expected_response = {
            "status": "OK",
            "type": "GENERAL",
            "code": "000000000",
            "errorData": "errorData",
            "data": {
                "success": True,
                "transaction": "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                "payer": "0x5555555555555555555555555555555555555555",
                "network": "eip155:56",
                "amount": "1000000",
                "confirmations": 1,
                "errorReason": "errorReason",
                "errorMessage": "errorMessage",
            },
            "subData": {},
            "params": {},
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.settle_b402_payment_v1(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        self.mock_session.request.assert_called_once()
        mock_get_signature.assert_called_once()

        assert "url" in request_kwargs
        assert "/api/v1/b402/settle" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"

        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(SettleB402PaymentV1Response)

        if is_list and not is_flat_list:
            expected = expected_response
        elif is_oneof or is_list or hasattr(SettleB402PaymentV1Response, "from_dict"):
            expected = SettleB402PaymentV1Response.from_dict(expected_response)
        else:
            expected = SettleB402PaymentV1Response.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    @patch("binance_common.utils.web3_signature")
    def test_settle_b402_payment_v1_success_with_optional_params(
        self, mock_get_signature
    ):
        """Test settle_b402_payment_v1() successfully with optional parameters."""

        params = {"body": (), "recv_window": 5000, "nonce": "unique-nonce-string"}

        expected_response = {
            "status": "OK",
            "type": "GENERAL",
            "code": "000000000",
            "errorData": "errorData",
            "data": {
                "success": True,
                "transaction": "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                "payer": "0x5555555555555555555555555555555555555555",
                "network": "eip155:56",
                "amount": "1000000",
                "confirmations": 1,
                "errorReason": "errorReason",
                "errorMessage": "errorMessage",
            },
            "subData": {},
            "params": {},
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.settle_b402_payment_v1(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        assert "url" in request_kwargs
        assert "/api/v1/b402/settle" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"

        self.mock_session.request.assert_called_once()
        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(SettleB402PaymentV1Response)

        if is_list and not is_flat_list:
            expected = expected_response
        elif is_oneof or is_list or hasattr(SettleB402PaymentV1Response, "from_dict"):
            expected = SettleB402PaymentV1Response.from_dict(expected_response)
        else:
            expected = SettleB402PaymentV1Response.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    def test_settle_b402_payment_v1_missing_required_param_body(self):
        """Test that settle_b402_payment_v1() raises RequiredError when 'body' is missing."""
        params = {
            "body": (),
        }
        params["body"] = None

        with pytest.raises(RequiredError, match="Missing required parameter 'body'"):
            self.client.settle_b402_payment_v1(**params)

    def test_settle_b402_payment_v1_server_error(self):
        """Test that settle_b402_payment_v1() raises an error when the server returns an error."""

        params = {
            "body": (),
        }

        mock_error = Exception("ResponseError")
        self.client.settle_b402_payment_v1 = MagicMock(side_effect=mock_error)

        with pytest.raises(Exception, match="ResponseError"):
            self.client.settle_b402_payment_v1(**params)

    @patch("binance_common.utils.web3_signature")
    def test_settle_b402_payment_v2_success(self, mock_get_signature):
        """Test settle_b402_payment_v2() successfully with required parameters only."""

        params = {
            "body": (),
        }

        expected_response = {
            "status": "OK",
            "type": "GENERAL",
            "code": "000000000",
            "errorData": "errorData",
            "data": {
                "success": True,
                "transaction": "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                "payer": "0x5555555555555555555555555555555555555555",
                "network": "eip155:56",
                "amount": "1000000",
                "errorReason": "errorReason",
                "errorMessage": "errorMessage",
                "extensions": {},
            },
            "subData": {},
            "params": {},
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.settle_b402_payment_v2(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        self.mock_session.request.assert_called_once()
        mock_get_signature.assert_called_once()

        assert "url" in request_kwargs
        assert "/api/v2/b402/settle" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"

        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(SettleB402PaymentV2Response)

        if is_list and not is_flat_list:
            expected = expected_response
        elif is_oneof or is_list or hasattr(SettleB402PaymentV2Response, "from_dict"):
            expected = SettleB402PaymentV2Response.from_dict(expected_response)
        else:
            expected = SettleB402PaymentV2Response.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    @patch("binance_common.utils.web3_signature")
    def test_settle_b402_payment_v2_success_with_optional_params(
        self, mock_get_signature
    ):
        """Test settle_b402_payment_v2() successfully with optional parameters."""

        params = {"body": (), "recv_window": 5000, "nonce": "unique-nonce-string"}

        expected_response = {
            "status": "OK",
            "type": "GENERAL",
            "code": "000000000",
            "errorData": "errorData",
            "data": {
                "success": True,
                "transaction": "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                "payer": "0x5555555555555555555555555555555555555555",
                "network": "eip155:56",
                "amount": "1000000",
                "errorReason": "errorReason",
                "errorMessage": "errorMessage",
                "extensions": {},
            },
            "subData": {},
            "params": {},
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.settle_b402_payment_v2(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        assert "url" in request_kwargs
        assert "/api/v2/b402/settle" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"

        self.mock_session.request.assert_called_once()
        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(SettleB402PaymentV2Response)

        if is_list and not is_flat_list:
            expected = expected_response
        elif is_oneof or is_list or hasattr(SettleB402PaymentV2Response, "from_dict"):
            expected = SettleB402PaymentV2Response.from_dict(expected_response)
        else:
            expected = SettleB402PaymentV2Response.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    def test_settle_b402_payment_v2_missing_required_param_body(self):
        """Test that settle_b402_payment_v2() raises RequiredError when 'body' is missing."""
        params = {
            "body": (),
        }
        params["body"] = None

        with pytest.raises(RequiredError, match="Missing required parameter 'body'"):
            self.client.settle_b402_payment_v2(**params)

    def test_settle_b402_payment_v2_server_error(self):
        """Test that settle_b402_payment_v2() raises an error when the server returns an error."""

        params = {
            "body": (),
        }

        mock_error = Exception("ResponseError")
        self.client.settle_b402_payment_v2 = MagicMock(side_effect=mock_error)

        with pytest.raises(Exception, match="ResponseError"):
            self.client.settle_b402_payment_v2(**params)

    @patch("binance_common.utils.web3_signature")
    def test_verify_b402_payment_v1_success(self, mock_get_signature):
        """Test verify_b402_payment_v1() successfully with required parameters only."""

        params = {
            "body": {
                "x402_version": "X402_VERSION_1",
                "payment_payload": {
                    "x402_version": "X402_VERSION_1",
                    "scheme": "exact",
                    "network": "eip155:56",
                    "payload": {
                        "signature": "0xabcdef...",
                        "authorization": {
                            "from": "0x5555555555555555555555555555555555555555",
                            "to": "0x2222222222222222222222222222222222222222",
                            "value": "1000000",
                            "valid_after": "0",
                            "valid_before": "1780000000",
                            "nonce": "0x0000000000000000000000000000000000000000000000000000000000000001",
                        },
                        "permit2_authorization": {
                            "permitted": {
                                "token": "0x1111111111111111111111111111111111111111",
                                "amount": "1000000",
                            },
                            "from": "0x5555555555555555555555555555555555555555",
                            "spender": "0x4444444444444444444444444444444444444444",
                            "nonce": "123456789",
                            "deadline": "1780000000",
                            "witness": {
                                "to": "0x2222222222222222222222222222222222222222",
                                "facilitator": "0x3333333333333333333333333333333333333333",
                                "valid_after": "0",
                            },
                        },
                    },
                },
                "payment_requirements": {
                    "scheme": "exact",
                    "network": "eip155:56",
                    "amount": "1000000",
                    "resource": "https://merchant.example.com/weather",
                    "description": "Premium weather report",
                    "pay_to": "0x2222222222222222222222222222222222222222",
                    "asset": "0x1111111111111111111111111111111111111111",
                    "max_timeout_seconds": "300",
                    "mime_type": "application/json",
                    "output_schema": {"type": "object"},
                    "extra": {
                        "name": "Token Name",
                        "version": "1",
                        "facilitator_address": "0x3333333333333333333333333333333333333333",
                    },
                },
            }
        }

        expected_response = {
            "status": "ERROR",
            "type": "GENERAL",
            "code": "1160401",
            "errorData": "Merchant not found",
            "data": {},
            "subData": {},
            "params": {},
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.verify_b402_payment_v1(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs
        parsed_params = parse_qs(request_kwargs["params"])
        camel_case_params = {snake_to_camel(k): v for k, v in params.items()}
        normalized = normalize_query_values(parsed_params, camel_case_params)

        self.mock_session.request.assert_called_once()
        mock_get_signature.assert_called_once()

        assert "url" in request_kwargs
        assert "/api/v1/b402/verify" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"
        assert (
            normalized["body"]
            == '{"x402Version":"X402_VERSION_1","paymentPayload":{"x402Version":"X402_VERSION_1","scheme":"exact","network":"eip155:56","payload":{"signature":"0xabcdef...","authorization":{"from":"0x5555555555555555555555555555555555555555","to":"0x2222222222222222222222222222222222222222","value":"1000000","validAfter":"0","validBefore":"1780000000","nonce":"0x0000000000000000000000000000000000000000000000000000000000000001"},"permit2Authorization":{"permitted":{"token":"0x1111111111111111111111111111111111111111","amount":"1000000"},"from":"0x5555555555555555555555555555555555555555","spender":"0x4444444444444444444444444444444444444444","nonce":"123456789","deadline":"1780000000","witness":{"to":"0x2222222222222222222222222222222222222222","facilitator":"0x3333333333333333333333333333333333333333","validAfter":"0"}}}},"paymentRequirements":{"scheme":"exact","network":"eip155:56","amount":"1000000","resource":"https://merchant.example.com/weather","description":"Premium weather report","payTo":"0x2222222222222222222222222222222222222222","asset":"0x1111111111111111111111111111111111111111","maxTimeoutSeconds":"300","mimeType":"application/json","outputSchema":{"type":"object"},"extra":{"name":"Token Name","version":"1","facilitatorAddress":"0x3333333333333333333333333333333333333333"}}}'
        )

        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(VerifyB402PaymentV1Response)

        if is_list and not is_flat_list:
            expected = expected_response
        elif is_oneof or is_list or hasattr(VerifyB402PaymentV1Response, "from_dict"):
            expected = VerifyB402PaymentV1Response.from_dict(expected_response)
        else:
            expected = VerifyB402PaymentV1Response.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    @patch("binance_common.utils.web3_signature")
    def test_verify_b402_payment_v1_success_with_optional_params(
        self, mock_get_signature
    ):
        """Test verify_b402_payment_v1() successfully with optional parameters."""

        params = {"body": (), "recv_window": 5000, "nonce": "unique-nonce-string"}

        expected_response = {
            "status": "ERROR",
            "type": "GENERAL",
            "code": "1160401",
            "errorData": "Merchant not found",
            "data": {},
            "subData": {},
            "params": {},
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.verify_b402_payment_v1(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        assert "url" in request_kwargs
        assert "/api/v1/b402/verify" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"

        self.mock_session.request.assert_called_once()
        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(VerifyB402PaymentV1Response)

        if is_list and not is_flat_list:
            expected = expected_response
        elif is_oneof or is_list or hasattr(VerifyB402PaymentV1Response, "from_dict"):
            expected = VerifyB402PaymentV1Response.from_dict(expected_response)
        else:
            expected = VerifyB402PaymentV1Response.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    def test_verify_b402_payment_v1_missing_required_param_body(self):
        """Test that verify_b402_payment_v1() raises RequiredError when 'body' is missing."""
        params = {
            "body": (),
        }
        params["body"] = None

        with pytest.raises(RequiredError, match="Missing required parameter 'body'"):
            self.client.verify_b402_payment_v1(**params)

    def test_verify_b402_payment_v1_server_error(self):
        """Test that verify_b402_payment_v1() raises an error when the server returns an error."""

        params = {
            "body": (),
        }

        mock_error = Exception("ResponseError")
        self.client.verify_b402_payment_v1 = MagicMock(side_effect=mock_error)

        with pytest.raises(Exception, match="ResponseError"):
            self.client.verify_b402_payment_v1(**params)

    @patch("binance_common.utils.web3_signature")
    def test_verify_b402_payment_v2_success(self, mock_get_signature):
        """Test verify_b402_payment_v2() successfully with required parameters only."""

        params = {
            "body": {
                "x402_version": "X402_VERSION_2",
                "payment_payload": {
                    "x402_version": "X402_VERSION_2",
                    "resource": {
                        "url": "https://merchant.example.com/weather",
                        "description": "Premium weather report",
                        "mime_type": "application/json",
                    },
                    "accepted": {
                        "network": "eip155:56",
                        "amount": "1000000",
                        "asset": "0x1111111111111111111111111111111111111111",
                        "pay_to": "0x2222222222222222222222222222222222222222",
                        "max_timeout_seconds": "300",
                    },
                    "payload": {
                        "signature": "0xabcdef...",
                        "authorization": {
                            "from": "0x5555555555555555555555555555555555555555",
                            "to": "0x2222222222222222222222222222222222222222",
                            "value": "1000000",
                            "valid_after": "0",
                            "valid_before": "1780000000",
                            "nonce": "0x0000000000000000000000000000000000000000000000000000000000000001",
                        },
                        "permit2_authorization": {
                            "permitted": {
                                "token": "0x1111111111111111111111111111111111111111",
                                "amount": "1000000",
                            },
                            "from": "0x5555555555555555555555555555555555555555",
                            "spender": "0x4444444444444444444444444444444444444444",
                            "nonce": "123456789",
                            "deadline": "1780000000",
                            "witness": {
                                "to": "0x2222222222222222222222222222222222222222",
                                "facilitator": "0x3333333333333333333333333333333333333333",
                                "valid_after": "0",
                            },
                        },
                    },
                    "extensions": {
                        "bazaar": {
                            "info": {"input": {"type": "http", "method": "GET"}},
                            "schema": {
                                "": "$schema=https://json-schema.org/draft/2020-12/schema",
                                "type": "object",
                                "properties": {
                                    "input": {
                                        "type": "object",
                                        "properties": {
                                            "type": {"const": "http"},
                                            "method": {"enum": ["GET"]},
                                        },
                                        "required": ["type", "method"],
                                    }
                                },
                                "required": ["input"],
                            },
                            "route_template": "/v1/weather/:city",
                            "description": "Hourly weather forecast by city",
                        }
                    },
                },
                "payment_requirements": {
                    "network": "eip155:56",
                    "amount": "1000000",
                    "asset": "0x1111111111111111111111111111111111111111",
                    "pay_to": "0x2222222222222222222222222222222222222222",
                    "max_timeout_seconds": "300",
                },
            }
        }

        expected_response = {
            "status": "OK",
            "type": "GENERAL",
            "code": "000000000",
            "errorData": "errorData",
            "data": {
                "isValid": True,
                "payer": "0x5555555555555555555555555555555555555555",
                "invalidReason": "invalid_payload",
                "invalidMessage": "invalidMessage",
            },
            "subData": {},
            "params": {},
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.verify_b402_payment_v2(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs
        parsed_params = parse_qs(request_kwargs["params"])
        camel_case_params = {snake_to_camel(k): v for k, v in params.items()}
        normalized = normalize_query_values(parsed_params, camel_case_params)

        self.mock_session.request.assert_called_once()
        mock_get_signature.assert_called_once()

        assert "url" in request_kwargs
        assert "/api/v2/b402/verify" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"
        assert (
            normalized["body"]
            == '{"x402Version":"X402_VERSION_2","paymentPayload":{"x402Version":"X402_VERSION_2","resource":{"url":"https://merchant.example.com/weather","description":"Premium weather report","mimeType":"application/json"},"accepted":{"network":"eip155:56","amount":"1000000","asset":"0x1111111111111111111111111111111111111111","payTo":"0x2222222222222222222222222222222222222222","maxTimeoutSeconds":"300"},"payload":{"signature":"0xabcdef...","authorization":{"from":"0x5555555555555555555555555555555555555555","to":"0x2222222222222222222222222222222222222222","value":"1000000","validAfter":"0","validBefore":"1780000000","nonce":"0x0000000000000000000000000000000000000000000000000000000000000001"},"permit2Authorization":{"permitted":{"token":"0x1111111111111111111111111111111111111111","amount":"1000000"},"from":"0x5555555555555555555555555555555555555555","spender":"0x4444444444444444444444444444444444444444","nonce":"123456789","deadline":"1780000000","witness":{"to":"0x2222222222222222222222222222222222222222","facilitator":"0x3333333333333333333333333333333333333333","validAfter":"0"}}},"extensions":{"bazaar":{"info":{"input":{"type":"http","method":"GET"}},"schema":{"":"$schema=https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"input":{"type":"object","properties":{"type":{"const":"http"},"method":{"enum":["GET"]}},"required":["type","method"]}},"required":["input"]},"routeTemplate":"/v1/weather/:city","description":"Hourly weather forecast by city"}}},"paymentRequirements":{"network":"eip155:56","amount":"1000000","asset":"0x1111111111111111111111111111111111111111","payTo":"0x2222222222222222222222222222222222222222","maxTimeoutSeconds":"300"}}'
        )

        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(VerifyB402PaymentV2Response)

        if is_list and not is_flat_list:
            expected = expected_response
        elif is_oneof or is_list or hasattr(VerifyB402PaymentV2Response, "from_dict"):
            expected = VerifyB402PaymentV2Response.from_dict(expected_response)
        else:
            expected = VerifyB402PaymentV2Response.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    @patch("binance_common.utils.web3_signature")
    def test_verify_b402_payment_v2_success_with_optional_params(
        self, mock_get_signature
    ):
        """Test verify_b402_payment_v2() successfully with optional parameters."""

        params = {"body": (), "recv_window": 5000, "nonce": "unique-nonce-string"}

        expected_response = {
            "status": "OK",
            "type": "GENERAL",
            "code": "000000000",
            "errorData": "errorData",
            "data": {
                "isValid": True,
                "payer": "0x5555555555555555555555555555555555555555",
                "invalidReason": "invalid_payload",
                "invalidMessage": "invalidMessage",
            },
            "subData": {},
            "params": {},
        }
        mock_get_signature.return_value = "mocked_signature"
        self.set_mock_response(expected_response)

        response = self.client.verify_b402_payment_v2(**params)

        actual_call_args = self.mock_session.request.call_args
        request_kwargs = actual_call_args.kwargs

        assert "url" in request_kwargs
        assert "/api/v2/b402/verify" in request_kwargs["url"]
        assert request_kwargs["method"] == "POST"

        self.mock_session.request.assert_called_once()
        assert response is not None

        is_list = isinstance(expected_response, list)
        is_flat_list = (
            is_list and not isinstance(expected_response[0], list) if is_list else False
        )
        is_oneof = is_one_of_model(VerifyB402PaymentV2Response)

        if is_list and not is_flat_list:
            expected = expected_response
        elif is_oneof or is_list or hasattr(VerifyB402PaymentV2Response, "from_dict"):
            expected = VerifyB402PaymentV2Response.from_dict(expected_response)
        else:
            expected = VerifyB402PaymentV2Response.model_validate_json(
                json.dumps(expected_response)
            )

        assert response.data() == expected

    def test_verify_b402_payment_v2_missing_required_param_body(self):
        """Test that verify_b402_payment_v2() raises RequiredError when 'body' is missing."""
        params = {
            "body": (),
        }
        params["body"] = None

        with pytest.raises(RequiredError, match="Missing required parameter 'body'"):
            self.client.verify_b402_payment_v2(**params)

    def test_verify_b402_payment_v2_server_error(self):
        """Test that verify_b402_payment_v2() raises an error when the server returns an error."""

        params = {
            "body": (),
        }

        mock_error = Exception("ResponseError")
        self.client.verify_b402_payment_v2 = MagicMock(side_effect=mock_error)

        with pytest.raises(Exception, match="ResponseError"):
            self.client.verify_b402_payment_v2(**params)
