"""
Binance Wallet REST API

Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
The version of the OpenAPI document: 1.0.0
Contact: wallet-api@binance.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from .market_api import MarketApi as MarketApi
from .trading_api import TradingApi as TradingApi
from .transaction_api import TransactionApi as TransactionApi
from .wallet_api import WalletApi as WalletApi
