"""
Binance Wallet REST API

Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
The version of the OpenAPI document: 1.0.0
Contact: wallet-api@binance.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from typing import Optional, Union
from requests import Session
from binance_common.configuration import ConfigurationRestAPI
from binance_common.errors import RequiredError
from binance_common.models import ApiResponse
from binance_common.signature import Signers
from binance_common.utils import send_request

from ..models import GetCandlesResponse
from ..models import GetHoldersRankingResponse
from ..models import GetHotTokensResponse
from ..models import GetPriceResponse
from ..models import GetPriceInfoResponse
from ..models import GetSupportedChainsResponse
from ..models import GetTokenAdvancedInfoResponse
from ..models import GetTokenBasicInfoResponse
from ..models import GetTokenTradesResponse
from ..models import GetTopLiquidityPoolsResponse
from ..models import GetTopTradersResponse
from ..models import SearchTokensResponse


from ..models import GetCandlesBarEnum
from ..models import GetHoldersRankingTagFilterEnum
from ..models import GetHotTokensRankByEnum
from ..models import GetHotTokensRankingTimeFrameEnum
from ..models import GetTokenTradesTagFilterEnum
from ..models import GetTopTradersTagFilterEnum


class MarketApi:
    """API Client for MarketApi endpoints."""

    def __init__(
        self,
        configuration: ConfigurationRestAPI = None,
        session: Session = None,
        signer: Signers = None,
    ) -> None:
        self._configuration = configuration
        self._session = session
        self._signer = signer

    def get_candles(
        self,
        binance_chain_id: Union[str, None],
        token_contract_address: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        bar: Optional[GetCandlesBarEnum] = None,
        after: Optional[int] = None,
        before: Optional[int] = None,
        limit: Optional[int] = None,
    ) -> ApiResponse[GetCandlesResponse]:
        """
        Get Candles
        GET /api/v1/dex/market/candles


        Return OHLCV candlestick data for a token. Each candle is a tuple `[timestamp, open, high, low, close, volume]`.

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
            token_contract_address (Union[str, None]): Token contract address.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            bar (Optional[GetCandlesBarEnum] = None): Candle interval. Defaults to "1m".
            after (Optional[int] = None): Optional upper bound (exclusive) on candle close time, Unix milliseconds. Returns candles strictly before this time.
            before (Optional[int] = None): Optional lower bound (exclusive) on candle close time, Unix milliseconds. Returns candles strictly after this time.
            limit (Optional[int] = None): Number of candles to return. Defaults to 100.

        Returns:
            ApiResponse[GetCandlesResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        if binance_chain_id is None:
            raise RequiredError(
                field="binance_chain_id",
                error_message="Missing required parameter 'binance_chain_id'",
            )
        if token_contract_address is None:
            raise RequiredError(
                field="token_contract_address",
                error_message="Missing required parameter 'token_contract_address'",
            )

        body = {}
        headers = {
            "recv_window": recv_window,
            "nonce": nonce,
        }
        payload = {
            "binance_chain_id": binance_chain_id,
            "token_contract_address": token_contract_address,
            "bar": bar,
            "after": after,
            "before": before,
            "limit": limit,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/api/v1/dex/market/candles",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetCandlesResponse,
            web3_headers=headers,
            is_signed=True,
            signer=self._signer,
        )

    def get_holders_ranking(
        self,
        binance_chain_id: Union[str, None],
        token_contract_address: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        tag_filter: Optional[GetHoldersRankingTagFilterEnum] = None,
    ) -> ApiResponse[GetHoldersRankingResponse]:
        """
        Get Holders Ranking
        GET /api/v1/dex/market/token/holder


        Return the holders ranking list for a token, including holding amount, holding percentage, native-token balance, average buy/sell price, realized PnL, and funding source.

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier.
            token_contract_address (Union[str, None]): Token contract address.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            tag_filter (Optional[GetHoldersRankingTagFilterEnum] = None): Optional tag filter. 1=KOL, 2=Developer, 3=Smart Money, 4=Insider, 5=Sniper, 6=Bundle.

        Returns:
            ApiResponse[GetHoldersRankingResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        if binance_chain_id is None:
            raise RequiredError(
                field="binance_chain_id",
                error_message="Missing required parameter 'binance_chain_id'",
            )
        if token_contract_address is None:
            raise RequiredError(
                field="token_contract_address",
                error_message="Missing required parameter 'token_contract_address'",
            )

        body = {}
        headers = {
            "recv_window": recv_window,
            "nonce": nonce,
        }
        payload = {
            "binance_chain_id": binance_chain_id,
            "token_contract_address": token_contract_address,
            "tag_filter": tag_filter,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/api/v1/dex/market/token/holder",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetHoldersRankingResponse,
            web3_headers=headers,
            is_signed=True,
            signer=self._signer,
        )

    def get_hot_tokens(
        self,
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        binance_chain_id: Optional[str] = None,
        rank_by: Optional[GetHotTokensRankByEnum] = None,
        ranking_time_frame: Optional[GetHotTokensRankingTimeFrameEnum] = None,
        price_change_percent_min: Optional[str] = None,
        price_change_percent_max: Optional[str] = None,
        volume_min: Optional[str] = None,
        volume_max: Optional[str] = None,
        txs_min: Optional[str] = None,
        txs_max: Optional[str] = None,
        market_cap_min: Optional[str] = None,
        market_cap_max: Optional[str] = None,
        liquidity_min: Optional[str] = None,
        liquidity_max: Optional[str] = None,
        dev_holding_percent_min: Optional[str] = None,
        dev_holding_percent_max: Optional[str] = None,
        inflow_usd_min: Optional[str] = None,
        inflow_usd_max: Optional[str] = None,
        holders_min: Optional[str] = None,
        holders_max: Optional[str] = None,
        bn_holder_count_min: Optional[str] = None,
        bn_holder_count_max: Optional[str] = None,
        top10_holding_percent_min: Optional[str] = None,
        top10_holding_percent_max: Optional[str] = None,
        sniper_holding_percent_min: Optional[str] = None,
        sniper_holding_percent_max: Optional[str] = None,
        smart_money_holding_percent_min: Optional[str] = None,
        smart_money_holding_percent_max: Optional[str] = None,
        kol_holding_percent_min: Optional[str] = None,
        kol_holding_percent_max: Optional[str] = None,
        pro_holding_percent_min: Optional[str] = None,
        pro_holding_percent_max: Optional[str] = None,
        fresh_wallet_holding_percent_min: Optional[str] = None,
        fresh_wallet_holding_percent_max: Optional[str] = None,
        insider_holding_percent_min: Optional[str] = None,
        insider_holding_percent_max: Optional[str] = None,
        bundler_holding_percent_min: Optional[str] = None,
        bundler_holding_percent_max: Optional[str] = None,
        dev_created_token_count_min: Optional[str] = None,
        dev_created_token_count_max: Optional[str] = None,
        dev_migrated_token_count_min: Optional[str] = None,
        dev_migrated_token_count_max: Optional[str] = None,
        dev_migrated_token_percent_min: Optional[str] = None,
        dev_migrated_token_percent_max: Optional[str] = None,
        is_dev_sold_all: Optional[bool] = None,
        is_dev_burned: Optional[bool] = None,
        is_mint: Optional[bool] = None,
        is_freeze: Optional[bool] = None,
        is_hide_wash_trading_tokens: Optional[bool] = None,
        is_hide_dev_wash_trading_tokens: Optional[bool] = None,
        is_hide_internal_wash_trading_tokens: Optional[bool] = None,
        page_id: Optional[int] = None,
        size: Optional[int] = None,
    ) -> ApiResponse[GetHotTokensResponse]:
        """
        Get Hot Tokens
        GET /api/v1/dex/market/token/hot-token


        Return a paginated, sorted, filterable list of hot tokens. Supports sorting by price, change, transactions, volume, market cap, liquidity, creation time, holder count, BN holder count, or net inflow, with rich numeric range filters and boolean toggles.

        Args:
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            binance_chain_id (Optional[str] = None): Chain identifier. Single value only. Omit to return mixed results across all chains.
            rank_by (Optional[GetHotTokensRankByEnum] = None): Sort field. 1=price, 2=price change, 3=tx count, 4=volume, 5=market cap, 6=liquidity, 7=creation time, 8=holder count, 9=BN holder count, 10=net inflow.
            ranking_time_frame (Optional[GetHotTokensRankingTimeFrameEnum] = None): Sort time frame. 1=1 minute, 2=5 minutes, 3=1 hour, 4=4 hours, 5=24 hours. Defaults to 3.
            price_change_percent_min (Optional[str] = None): Minimum price change percentage (no `%` suffix).
            price_change_percent_max (Optional[str] = None): Maximum price change percentage.
            volume_min (Optional[str] = None): Minimum trading volume in USD.
            volume_max (Optional[str] = None): Maximum trading volume in USD.
            txs_min (Optional[str] = None): Minimum transaction count.
            txs_max (Optional[str] = None): Maximum transaction count.
            market_cap_min (Optional[str] = None): Minimum market cap in USD.
            market_cap_max (Optional[str] = None): Maximum market cap in USD.
            liquidity_min (Optional[str] = None): Minimum liquidity in USD.
            liquidity_max (Optional[str] = None): Maximum liquidity in USD.
            dev_holding_percent_min (Optional[str] = None): Minimum developer holding percentage.
            dev_holding_percent_max (Optional[str] = None): Maximum developer holding percentage.
            inflow_usd_min (Optional[str] = None): Minimum net inflow in USD.
            inflow_usd_max (Optional[str] = None): Maximum net inflow in USD.
            holders_min (Optional[str] = None): Minimum holder count.
            holders_max (Optional[str] = None): Maximum holder count.
            bn_holder_count_min (Optional[str] = None): Minimum BN holder count.
            bn_holder_count_max (Optional[str] = None): Maximum BN holder count.
            top10_holding_percent_min (Optional[str] = None): Minimum top-10 holding percentage.
            top10_holding_percent_max (Optional[str] = None): Maximum top-10 holding percentage.
            sniper_holding_percent_min (Optional[str] = None): Minimum sniper holding percentage.
            sniper_holding_percent_max (Optional[str] = None): Maximum sniper holding percentage.
            smart_money_holding_percent_min (Optional[str] = None): Minimum smart-money holding percentage.
            smart_money_holding_percent_max (Optional[str] = None): Maximum smart-money holding percentage.
            kol_holding_percent_min (Optional[str] = None): Minimum KOL holding percentage.
            kol_holding_percent_max (Optional[str] = None): Maximum KOL holding percentage.
            pro_holding_percent_min (Optional[str] = None): Minimum pro-trader holding percentage.
            pro_holding_percent_max (Optional[str] = None): Maximum pro-trader holding percentage.
            fresh_wallet_holding_percent_min (Optional[str] = None): Minimum fresh-wallet holding percentage.
            fresh_wallet_holding_percent_max (Optional[str] = None): Maximum fresh-wallet holding percentage.
            insider_holding_percent_min (Optional[str] = None): Minimum insider holding percentage.
            insider_holding_percent_max (Optional[str] = None): Maximum insider holding percentage.
            bundler_holding_percent_min (Optional[str] = None): Minimum bundler holding percentage.
            bundler_holding_percent_max (Optional[str] = None): Maximum bundler holding percentage.
            dev_created_token_count_min (Optional[str] = None): Minimum developer-created token count.
            dev_created_token_count_max (Optional[str] = None): Maximum developer-created token count.
            dev_migrated_token_count_min (Optional[str] = None): Minimum developer-migrated token count.
            dev_migrated_token_count_max (Optional[str] = None): Maximum developer-migrated token count.
            dev_migrated_token_percent_min (Optional[str] = None): Minimum developer-migrated token percentage.
            dev_migrated_token_percent_max (Optional[str] = None): Maximum developer-migrated token percentage.
            is_dev_sold_all (Optional[bool] = None): Whether the developer has sold all holdings.
            is_dev_burned (Optional[bool] = None): Whether the developer has burned tokens.
            is_mint (Optional[bool] = None): Whether to hide mintable tokens. Defaults to false.
            is_freeze (Optional[bool] = None): Whether to hide freezable tokens. Defaults to false.
            is_hide_wash_trading_tokens (Optional[bool] = None): Whether to hide wash-trading tokens. Defaults to true.
            is_hide_dev_wash_trading_tokens (Optional[bool] = None): Whether to hide developer wash-trading tokens. Defaults to true.
            is_hide_internal_wash_trading_tokens (Optional[bool] = None): Whether to hide insider wash-trading tokens. Defaults to true.
            page_id (Optional[int] = None): Pagination identifier. Omit on the first request; pass back the previous response's `page` value to fetch the next page.
            size (Optional[int] = None): Page size. Maximum 100. Defaults to 100.

        Returns:
            ApiResponse[GetHotTokensResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        body = {}
        headers = {
            "recv_window": recv_window,
            "nonce": nonce,
        }
        payload = {
            "binance_chain_id": binance_chain_id,
            "rank_by": rank_by,
            "ranking_time_frame": ranking_time_frame,
            "price_change_percent_min": price_change_percent_min,
            "price_change_percent_max": price_change_percent_max,
            "volume_min": volume_min,
            "volume_max": volume_max,
            "txs_min": txs_min,
            "txs_max": txs_max,
            "market_cap_min": market_cap_min,
            "market_cap_max": market_cap_max,
            "liquidity_min": liquidity_min,
            "liquidity_max": liquidity_max,
            "dev_holding_percent_min": dev_holding_percent_min,
            "dev_holding_percent_max": dev_holding_percent_max,
            "inflow_usd_min": inflow_usd_min,
            "inflow_usd_max": inflow_usd_max,
            "holders_min": holders_min,
            "holders_max": holders_max,
            "bn_holder_count_min": bn_holder_count_min,
            "bn_holder_count_max": bn_holder_count_max,
            "top10_holding_percent_min": top10_holding_percent_min,
            "top10_holding_percent_max": top10_holding_percent_max,
            "sniper_holding_percent_min": sniper_holding_percent_min,
            "sniper_holding_percent_max": sniper_holding_percent_max,
            "smart_money_holding_percent_min": smart_money_holding_percent_min,
            "smart_money_holding_percent_max": smart_money_holding_percent_max,
            "kol_holding_percent_min": kol_holding_percent_min,
            "kol_holding_percent_max": kol_holding_percent_max,
            "pro_holding_percent_min": pro_holding_percent_min,
            "pro_holding_percent_max": pro_holding_percent_max,
            "fresh_wallet_holding_percent_min": fresh_wallet_holding_percent_min,
            "fresh_wallet_holding_percent_max": fresh_wallet_holding_percent_max,
            "insider_holding_percent_min": insider_holding_percent_min,
            "insider_holding_percent_max": insider_holding_percent_max,
            "bundler_holding_percent_min": bundler_holding_percent_min,
            "bundler_holding_percent_max": bundler_holding_percent_max,
            "dev_created_token_count_min": dev_created_token_count_min,
            "dev_created_token_count_max": dev_created_token_count_max,
            "dev_migrated_token_count_min": dev_migrated_token_count_min,
            "dev_migrated_token_count_max": dev_migrated_token_count_max,
            "dev_migrated_token_percent_min": dev_migrated_token_percent_min,
            "dev_migrated_token_percent_max": dev_migrated_token_percent_max,
            "is_dev_sold_all": is_dev_sold_all,
            "is_dev_burned": is_dev_burned,
            "is_mint": is_mint,
            "is_freeze": is_freeze,
            "is_hide_wash_trading_tokens": is_hide_wash_trading_tokens,
            "is_hide_dev_wash_trading_tokens": is_hide_dev_wash_trading_tokens,
            "is_hide_internal_wash_trading_tokens": is_hide_internal_wash_trading_tokens,
            "page_id": page_id,
            "size": size,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/api/v1/dex/market/token/hot-token",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetHotTokensResponse,
            web3_headers=headers,
            is_signed=True,
            signer=self._signer,
        )

    def get_price(
        self,
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetPriceResponse]:
        """
        Get Price
        POST /api/v1/dex/market/price


        Batch query the latest USD price for one or more tokens across supported chains. Up to 100 entries per request.

        Args:
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[GetPriceResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        body = {}
        headers = {"recv_window": recv_window, "nonce": nonce}
        payload = {}

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/api/v1/dex/market/price",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetPriceResponse,
            web3_headers=headers,
            is_signed=True,
            signer=self._signer,
        )

    def get_price_info(
        self,
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetPriceInfoResponse]:
        """
        Get Price Info
        POST /api/v1/dex/market/price-info


        Batch query price plus rolling market activity (volume, transactions, market cap, holders, BN MPC wallet activity) for one or more tokens. Up to 100 entries per request.

        Args:
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[GetPriceInfoResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        body = {}
        headers = {"recv_window": recv_window, "nonce": nonce}
        payload = {}

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/api/v1/dex/market/price-info",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetPriceInfoResponse,
            web3_headers=headers,
            is_signed=True,
            signer=self._signer,
        )

    def get_supported_chains(
        self,
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetSupportedChainsResponse]:
        """
        Get Supported Chains
        GET /api/v1/dex/market/supported/chain


        Return the blockchain networks for which the Market service can serve price and quote data. The list is dynamically configured server-side and may change over time.

        Args:
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[GetSupportedChainsResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        body = {}
        headers = {"recv_window": recv_window, "nonce": nonce}
        payload = {}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/api/v1/dex/market/supported/chain",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetSupportedChainsResponse,
            web3_headers=headers,
            is_signed=True,
            signer=self._signer,
        )

    def get_token_advanced_info(
        self,
        binance_chain_id: Union[str, None],
        token_contract_address: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetTokenAdvancedInfoResponse]:
        """
        Get Token Advanced Info
        GET /api/v1/dex/market/token/advanced-info


        Return advanced metrics for a token: creation metadata, dev/holder cohort breakdowns, smart-money / KOL / sniper / bundler / fresh-wallet holding percentages, and tag list.

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier.
            token_contract_address (Union[str, None]): Token contract address.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[GetTokenAdvancedInfoResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        if binance_chain_id is None:
            raise RequiredError(
                field="binance_chain_id",
                error_message="Missing required parameter 'binance_chain_id'",
            )
        if token_contract_address is None:
            raise RequiredError(
                field="token_contract_address",
                error_message="Missing required parameter 'token_contract_address'",
            )

        body = {}
        headers = {"recv_window": recv_window, "nonce": nonce}
        payload = {
            "binance_chain_id": binance_chain_id,
            "token_contract_address": token_contract_address,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/api/v1/dex/market/token/advanced-info",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetTokenAdvancedInfoResponse,
            web3_headers=headers,
            is_signed=True,
            signer=self._signer,
        )

    def get_token_basic_info(
        self,
        binance_chain_id: Union[str, None],
        token_contract_address: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetTokenBasicInfoResponse]:
        """
        Get Token Basic Info
        POST /api/v1/dex/market/token/basic-info


        Return basic metadata for a token: name, symbol, logo, decimals, creator, creation time, and tag info. Parameters are passed as query string (Spring `@RequestParam`), not a JSON body.

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier.
            token_contract_address (Union[str, None]): Token contract address.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[GetTokenBasicInfoResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        if binance_chain_id is None:
            raise RequiredError(
                field="binance_chain_id",
                error_message="Missing required parameter 'binance_chain_id'",
            )
        if token_contract_address is None:
            raise RequiredError(
                field="token_contract_address",
                error_message="Missing required parameter 'token_contract_address'",
            )

        body = {}
        headers = {"recv_window": recv_window, "nonce": nonce}
        payload = {
            "binance_chain_id": binance_chain_id,
            "token_contract_address": token_contract_address,
        }

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/api/v1/dex/market/token/basic-info",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetTokenBasicInfoResponse,
            web3_headers=headers,
            is_signed=True,
            signer=self._signer,
        )

    def get_token_trades(
        self,
        binance_chain_id: Union[str, None],
        token_contract_address: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        cursor: Optional[str] = None,
        limit: Optional[int] = None,
        tag_filter: Optional[GetTokenTradesTagFilterEnum] = None,
        wallet_address_filter: Optional[str] = None,
    ) -> ApiResponse[GetTokenTradesResponse]:
        """
        Get Token Trades
        GET /api/v1/dex/market/trades


        Return on-chain trade history for a token, sorted by trade time (descending). Supports cursor pagination, tag filtering, and wallet address filtering.

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier.
            token_contract_address (Union[str, None]): Token contract address.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            cursor (Optional[str] = None): Pagination cursor returned by the previous page. Omit on the first request.
            limit (Optional[int] = None): Page size. Range 1–500. Defaults to 100.
            tag_filter (Optional[GetTokenTradesTagFilterEnum] = None): Optional tag filter. 1=KOL, 2=Developer, 3=Smart Money, 4=Insider, 5=Sniper, 6=Bundle, 7=Whale Holder. When set, the response cursor is fixed to empty string.
            wallet_address_filter (Optional[str] = None): Optional wallet address filter. Comma-separated; up to 2 addresses.

        Returns:
            ApiResponse[GetTokenTradesResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        if binance_chain_id is None:
            raise RequiredError(
                field="binance_chain_id",
                error_message="Missing required parameter 'binance_chain_id'",
            )
        if token_contract_address is None:
            raise RequiredError(
                field="token_contract_address",
                error_message="Missing required parameter 'token_contract_address'",
            )

        body = {}
        headers = {
            "recv_window": recv_window,
            "nonce": nonce,
        }
        payload = {
            "binance_chain_id": binance_chain_id,
            "token_contract_address": token_contract_address,
            "cursor": cursor,
            "limit": limit,
            "tag_filter": tag_filter,
            "wallet_address_filter": wallet_address_filter,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/api/v1/dex/market/trades",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetTokenTradesResponse,
            web3_headers=headers,
            is_signed=True,
            signer=self._signer,
        )

    def get_top_liquidity_pools(
        self,
        binance_chain_id: Union[str, None],
        token_contract_address: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetTopLiquidityPoolsResponse]:
        """
        Get Top Liquidity Pools
        GET /api/v1/dex/market/token/top-liquidity


        Return the top liquidity pools for a token, including pool name, protocol, USD-denominated liquidity, pool address, and the token-level amounts that compose the pool.

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier.
            token_contract_address (Union[str, None]): Token contract address.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[GetTopLiquidityPoolsResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        if binance_chain_id is None:
            raise RequiredError(
                field="binance_chain_id",
                error_message="Missing required parameter 'binance_chain_id'",
            )
        if token_contract_address is None:
            raise RequiredError(
                field="token_contract_address",
                error_message="Missing required parameter 'token_contract_address'",
            )

        body = {}
        headers = {"recv_window": recv_window, "nonce": nonce}
        payload = {
            "binance_chain_id": binance_chain_id,
            "token_contract_address": token_contract_address,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/api/v1/dex/market/token/top-liquidity",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetTopLiquidityPoolsResponse,
            web3_headers=headers,
            is_signed=True,
            signer=self._signer,
        )

    def get_top_traders(
        self,
        binance_chain_id: Union[str, None],
        token_contract_address: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        tag_filter: Optional[GetTopTradersTagFilterEnum] = None,
    ) -> ApiResponse[GetTopTradersResponse]:
        """
        Get Top Traders
        GET /api/v1/dex/market/token/top-trader


        Return the top profit-making traders for a token, including holding amount, average buy/sell price, realized PnL, and funding source details.

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier.
            token_contract_address (Union[str, None]): Token contract address.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            tag_filter (Optional[GetTopTradersTagFilterEnum] = None): Optional tag filter. 1=KOL, 2=Developer, 3=Smart Money, 4=Insider, 5=Sniper, 6=Bundle, 7=Whale Holder.

        Returns:
            ApiResponse[GetTopTradersResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        if binance_chain_id is None:
            raise RequiredError(
                field="binance_chain_id",
                error_message="Missing required parameter 'binance_chain_id'",
            )
        if token_contract_address is None:
            raise RequiredError(
                field="token_contract_address",
                error_message="Missing required parameter 'token_contract_address'",
            )

        body = {}
        headers = {
            "recv_window": recv_window,
            "nonce": nonce,
        }
        payload = {
            "binance_chain_id": binance_chain_id,
            "token_contract_address": token_contract_address,
            "tag_filter": tag_filter,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/api/v1/dex/market/token/top-trader",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetTopTradersResponse,
            web3_headers=headers,
            is_signed=True,
            signer=self._signer,
        )

    def search_tokens(
        self,
        chains: Union[str, None],
        search: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[SearchTokensResponse]:
        """
        Search Tokens
        GET /api/v1/dex/market/token/search


        Search tokens across one or more chains by keyword. Returns matching tokens with metadata, 24h price change, holders, liquidity, market cap, current price, and tag info.

        Args:
            chains (Union[str, None]): Comma-separated list of chain identifiers to search across.
            search (Union[str, None]): Search keyword. Matches token name, symbol, or contract address.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[SearchTokensResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        if chains is None:
            raise RequiredError(
                field="chains", error_message="Missing required parameter 'chains'"
            )
        if search is None:
            raise RequiredError(
                field="search", error_message="Missing required parameter 'search'"
            )

        body = {}
        headers = {"recv_window": recv_window, "nonce": nonce}
        payload = {
            "chains": chains,
            "search": search,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/api/v1/dex/market/token/search",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=SearchTokensResponse,
            web3_headers=headers,
            is_signed=True,
            signer=self._signer,
        )
