# coding: utf-8

"""
Binance Web3 Wallet REST API

Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class B402SettleDataV1(BaseModel):
    """
    B402SettleDataV1
    """  # noqa: E501

    success: StrictBool
    transaction: Optional[StrictStr] = None
    payer: Optional[StrictStr] = None
    network: Optional[StrictStr] = None
    amount: Optional[StrictStr] = None
    confirmations: Optional[StrictInt] = None
    error_reason: Optional[StrictStr] = Field(default=None, alias="errorReason")
    error_message: Optional[StrictStr] = Field(default=None, alias="errorMessage")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "success",
        "transaction",
        "payer",
        "network",
        "amount",
        "confirmations",
        "errorReason",
        "errorMessage",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of B402SettleDataV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if transaction (nullable) is None
        # and model_fields_set contains the field
        if self.transaction is None and "transaction" in self.model_fields_set:
            _dict["transaction"] = None

        # set to None if payer (nullable) is None
        # and model_fields_set contains the field
        if self.payer is None and "payer" in self.model_fields_set:
            _dict["payer"] = None

        # set to None if network (nullable) is None
        # and model_fields_set contains the field
        if self.network is None and "network" in self.model_fields_set:
            _dict["network"] = None

        # set to None if amount (nullable) is None
        # and model_fields_set contains the field
        if self.amount is None and "amount" in self.model_fields_set:
            _dict["amount"] = None

        # set to None if confirmations (nullable) is None
        # and model_fields_set contains the field
        if self.confirmations is None and "confirmations" in self.model_fields_set:
            _dict["confirmations"] = None

        # set to None if error_reason (nullable) is None
        # and model_fields_set contains the field
        if self.error_reason is None and "error_reason" in self.model_fields_set:
            _dict["errorReason"] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict["errorMessage"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of B402SettleDataV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "success": obj.get("success"),
                "transaction": obj.get("transaction"),
                "payer": obj.get("payer"),
                "network": obj.get("network"),
                "amount": obj.get("amount"),
                "confirmations": obj.get("confirmations"),
                "errorReason": obj.get("errorReason"),
                "errorMessage": obj.get("errorMessage"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
