# coding: utf-8

"""
Binance Web3 Wallet REST API

Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DefiClaimType(str, Enum):
    """
    Claim routing type. Determines which companion fields are required: - `REWARD_PROTOCOL`: protocol-level rewards (e.g. Aave incentive, Radiant) — requires `defiProtocolId` + `binanceChainId` - `REWARD_INVESTMENT`: per-investment rewards — requires `investmentId` - `LP_FEE`: Uniswap V3/V4 LP fees — requires `investmentId` + `nftId` - `REDEMPTION`: redeem principal (Lista / Aster / Solv etc.) — requires `investmentId` + `redemptionId`  **Protocol constraints** — not every `claimType` is valid for every protocol; an invalid combination is rejected (`40453` or `40454`): - `REWARD_PROTOCOL` is **not** supported for LP (liquidity-pool) protocols in this release. - `REWARD_INVESTMENT` is not supported for PancakeSwap V3 farming positions; use `LP_FEE`   to claim farming incentives there. - `LP_FEE` applies only to concentrated-liquidity (V3/V4) LP positions. - `REDEMPTION` applies only to protocols with a redemption / lock-up flow (Lista, Aster, Solv).  The valid `claimType`s for a specific position are returned in that position's `positionDetail.claimTypes` (see the position list) — branch on that rather than hard-coding the mapping. Note: error messages may surface the protocol id with a chain prefix (e.g. `bsc_pancakeswap4`); the canonical id in API fields is the un-prefixed form (e.g. `pancakeswap4`).
    """

    """
    allowed enum values
    """
    REWARD_PROTOCOL = "REWARD_PROTOCOL"
    REWARD_INVESTMENT = "REWARD_INVESTMENT"
    LP_FEE = "LP_FEE"
    REDEMPTION = "REDEMPTION"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DefiClaimType from a JSON string"""
        return cls(json.loads(json_str))
