# coding: utf-8

"""
Binance Web3 Wallet REST API

Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class DefiInvestmentDto(BaseModel):
    """
    DeFi investment product summary (list item).
    """  # noqa: E501

    binance_chain_id: Optional[StrictStr] = Field(
        default=None, description="Binance chain ID.", alias="binanceChainId"
    )
    defi_protocol_id: Optional[StrictStr] = Field(
        default=None,
        description="Parent DeFi protocol identifier.",
        alias="defiProtocolId",
    )
    protocol_name: Optional[StrictStr] = Field(
        default=None, description="Protocol display name.", alias="protocolName"
    )
    investment_id: Optional[StrictStr] = Field(
        default=None,
        description="Investment product identifier (64-char hex, no `0x` prefix). Same format as the `investmentIds` returned by `POST /api/v1/defi/data/position/list` and accepted by the transaction build endpoints.",
        alias="investmentId",
    )
    investment_name: Optional[StrictStr] = Field(
        default=None, description="Investment display name.", alias="investmentName"
    )
    invest_type: Optional[StrictStr] = Field(
        default=None,
        description="Investment type of this product — a single string here (each product has exactly one). Note: the protocol-level investType (in protocol list/detail) is an array. Known values: Earn, LiquidityPool.",
        alias="investType",
    )
    apy_type: Optional[StrictStr] = Field(
        default=None,
        description="Rate yield type. Known values: APY, APR.",
        alias="apyType",
    )
    apy_bps: Optional[StrictInt] = Field(
        default=None,
        description="Annual percentage yield in basis points (1 bps = 0.01%). Integer value — use this for sorting / comparing / filtering, never the raw decimal.",
        alias="apyBps",
    )
    apy_display: Optional[StrictStr] = Field(
        default=None,
        description='Pre-formatted, human-readable APY string for display (e.g. "1,562.65%"). Quote as-is; do not re-compute or transform.',
        alias="apyDisplay",
    )
    tvl: Optional[StrictStr] = Field(
        default=None,
        description="Total value locked in this investment (USD). String, raw precision from the data source.",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "binanceChainId",
        "defiProtocolId",
        "protocolName",
        "investmentId",
        "investmentName",
        "investType",
        "apyType",
        "apyBps",
        "apyDisplay",
        "tvl",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DefiInvestmentDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DefiInvestmentDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "binanceChainId": obj.get("binanceChainId"),
                "defiProtocolId": obj.get("defiProtocolId"),
                "protocolName": obj.get("protocolName"),
                "investmentId": obj.get("investmentId"),
                "investmentName": obj.get("investmentName"),
                "investType": obj.get("investType"),
                "apyType": obj.get("apyType"),
                "apyBps": obj.get("apyBps"),
                "apyDisplay": obj.get("apyDisplay"),
                "tvl": obj.get("tvl"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
