# coding: utf-8

"""
Binance Web3 Wallet REST API

Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from binance_sdk_web3_wallet.rest_api.models.defi_preview_balance_change_inner import (
    DefiPreviewBalanceChangeInner,
)
from binance_sdk_web3_wallet.rest_api.models.defi_preview_fee_and_contract import (
    DefiPreviewFeeAndContract,
)
from binance_sdk_web3_wallet.rest_api.models.defi_preview_health_factor import (
    DefiPreviewHealthFactor,
)
from binance_sdk_web3_wallet.rest_api.models.defi_preview_warnings_inner import (
    DefiPreviewWarningsInner,
)
from typing import Set
from typing_extensions import Self


class DefiPreview(BaseModel):
    """
    Simulation result returned by the build endpoints when `simulate=true`. Includes whether the action is expected to succeed, the projected balance change, the estimated network fee, and — for lending protocols — the health-factor change. `balanceChange`, `feeAndContract`, `healthFactor`, and `warnings` each have a fixed structure (see below); the number of entries and some inner values vary by protocol.
    """  # noqa: E501

    success: Optional[StrictBool] = Field(
        default=None,
        description="Whether the simulated transaction is expected to succeed on-chain.",
    )
    balance_change: Optional[List[DefiPreviewBalanceChangeInner]] = Field(
        default=None,
        description="Signed token balance deltas from the simulation. Each entry has `tokenType`, `tokenSymbol`, `tokenAddress`, `tokenDecimals`, `amount` (positive = received, negative = spent), `valueUsd`, and an optional `tokenId`.",
        alias="balanceChange",
    )
    fee_and_contract: Optional[DefiPreviewFeeAndContract] = Field(
        default=None, alias="feeAndContract"
    )
    health_factor: Optional[DefiPreviewHealthFactor] = Field(
        default=None, alias="healthFactor"
    )
    warnings: Optional[List[DefiPreviewWarningsInner]] = Field(
        default=None,
        description="Non-blocking risk warnings. Empty array when there are no warnings.",
    )
    error_message: Optional[StrictStr] = Field(
        default=None,
        description="Error message when the simulated transaction is expected to fail.",
        alias="errorMessage",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "success",
        "balanceChange",
        "feeAndContract",
        "healthFactor",
        "warnings",
        "errorMessage",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DefiPreview from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in balance_change (list)
        _items = []
        if self.balance_change:
            for _item_balance_change in self.balance_change:
                if _item_balance_change:
                    _items.append(_item_balance_change.to_dict())
            _dict["balanceChange"] = _items
        # override the default output from pydantic by calling `to_dict()` of fee_and_contract
        if self.fee_and_contract:
            _dict["feeAndContract"] = self.fee_and_contract.to_dict()
        # override the default output from pydantic by calling `to_dict()` of health_factor
        if self.health_factor:
            _dict["healthFactor"] = self.health_factor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in warnings (list)
        _items = []
        if self.warnings:
            for _item_warnings in self.warnings:
                if _item_warnings:
                    _items.append(_item_warnings.to_dict())
            _dict["warnings"] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DefiPreview from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "success": obj.get("success"),
                "balanceChange": (
                    [
                        DefiPreviewBalanceChangeInner.from_dict(_item)
                        for _item in obj["balanceChange"]
                    ]
                    if obj.get("balanceChange") is not None
                    else None
                ),
                "feeAndContract": (
                    DefiPreviewFeeAndContract.from_dict(obj["feeAndContract"])
                    if obj.get("feeAndContract") is not None
                    else None
                ),
                "healthFactor": (
                    DefiPreviewHealthFactor.from_dict(obj["healthFactor"])
                    if obj.get("healthFactor") is not None
                    else None
                ),
                "warnings": (
                    [
                        DefiPreviewWarningsInner.from_dict(_item)
                        for _item in obj["warnings"]
                    ]
                    if obj.get("warnings") is not None
                    else None
                ),
                "errorMessage": obj.get("errorMessage"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
