# coding: utf-8

"""
Binance Web3 Wallet REST API

Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from binance_sdk_web3_wallet.rest_api.models.defi_preview_fee_and_contract_estimated_network_fee import (
    DefiPreviewFeeAndContractEstimatedNetworkFee,
)
from binance_sdk_web3_wallet.rest_api.models.defi_preview_fee_and_contract_interact_with import (
    DefiPreviewFeeAndContractInteractWith,
)
from typing import Set
from typing_extensions import Self


class DefiPreviewFeeAndContract(BaseModel):
    """
    Estimated network fee and the contract the action interacts with. Contains `estimatedNetworkFee` and `interactWith`.
    """  # noqa: E501

    estimated_network_fee: Optional[DefiPreviewFeeAndContractEstimatedNetworkFee] = (
        Field(default=None, alias="estimatedNetworkFee")
    )
    interact_with: Optional[DefiPreviewFeeAndContractInteractWith] = Field(
        default=None, alias="interactWith"
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["estimatedNetworkFee", "interactWith"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DefiPreviewFeeAndContract from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of estimated_network_fee
        if self.estimated_network_fee:
            _dict["estimatedNetworkFee"] = self.estimated_network_fee.to_dict()
        # override the default output from pydantic by calling `to_dict()` of interact_with
        if self.interact_with:
            _dict["interactWith"] = self.interact_with.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DefiPreviewFeeAndContract from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "estimatedNetworkFee": (
                    DefiPreviewFeeAndContractEstimatedNetworkFee.from_dict(
                        obj["estimatedNetworkFee"]
                    )
                    if obj.get("estimatedNetworkFee") is not None
                    else None
                ),
                "interactWith": (
                    DefiPreviewFeeAndContractInteractWith.from_dict(obj["interactWith"])
                    if obj.get("interactWith") is not None
                    else None
                ),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
