# coding: utf-8

"""
Binance Web3 Wallet REST API

Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class DefiProtocolSocialLinksDto(BaseModel):
    """
    Protocol social media links.
    """  # noqa: E501

    x: Optional[StrictStr] = Field(
        default=None, description="X (Twitter) profile URL. Null when not available."
    )
    discord: Optional[StrictStr] = Field(
        default=None, description="Discord invite URL. Null when not available."
    )
    github: Optional[StrictStr] = Field(
        default=None, description="GitHub organization URL. Null when not available."
    )
    linkedin: Optional[StrictStr] = Field(
        default=None, description="LinkedIn company URL. Null when not available."
    )
    telegram: Optional[StrictStr] = Field(
        default=None, description="Telegram channel URL. Null when not available."
    )
    gitbook: Optional[StrictStr] = Field(
        default=None,
        description="GitBook documentation URL. Empty string or null when not available.",
    )
    website: Optional[StrictStr] = Field(
        default=None, description="Official website URL."
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "x",
        "discord",
        "github",
        "linkedin",
        "telegram",
        "gitbook",
        "website",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DefiProtocolSocialLinksDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if x (nullable) is None
        # and model_fields_set contains the field
        if self.x is None and "x" in self.model_fields_set:
            _dict["x"] = None

        # set to None if discord (nullable) is None
        # and model_fields_set contains the field
        if self.discord is None and "discord" in self.model_fields_set:
            _dict["discord"] = None

        # set to None if github (nullable) is None
        # and model_fields_set contains the field
        if self.github is None and "github" in self.model_fields_set:
            _dict["github"] = None

        # set to None if linkedin (nullable) is None
        # and model_fields_set contains the field
        if self.linkedin is None and "linkedin" in self.model_fields_set:
            _dict["linkedin"] = None

        # set to None if telegram (nullable) is None
        # and model_fields_set contains the field
        if self.telegram is None and "telegram" in self.model_fields_set:
            _dict["telegram"] = None

        # set to None if gitbook (nullable) is None
        # and model_fields_set contains the field
        if self.gitbook is None and "gitbook" in self.model_fields_set:
            _dict["gitbook"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DefiProtocolSocialLinksDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "x": obj.get("x"),
                "discord": obj.get("discord"),
                "github": obj.get("github"),
                "linkedin": obj.get("linkedin"),
                "telegram": obj.get("telegram"),
                "gitbook": obj.get("gitbook"),
                "website": obj.get("website"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
