"""
Binance Wallet REST API

Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
The version of the OpenAPI document: 1.0.0
Contact: wallet-api@binance.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from enum import Enum


class GetCandlesBarEnum(Enum):
    BAR_1s = "1s"
    BAR_5s = "5s"
    BAR_30s = "30s"
    BAR_1m = "1m"
    BAR_3m = "3m"
    BAR_5m = "5m"
    BAR_15m = "15m"
    BAR_30m = "30m"
    BAR_1h = "1h"
    BAR_2h = "2h"
    BAR_4h = "4h"
    BAR_6h = "6h"
    BAR_8h = "8h"
    BAR_12h = "12h"
    BAR_1d = "1d"
    BAR_3d = "3d"
    BAR_1w = "1w"
    BAR_1M = "1M"


class GetHoldersRankingTagFilterEnum(Enum):
    TAG_FILTER_1 = "1"
    TAG_FILTER_2 = "2"
    TAG_FILTER_3 = "3"
    TAG_FILTER_4 = "4"
    TAG_FILTER_5 = "5"
    TAG_FILTER_6 = "6"


class GetHotTokensRankByEnum(Enum):
    RANK_BY_1 = "1"
    RANK_BY_2 = "2"
    RANK_BY_3 = "3"
    RANK_BY_4 = "4"
    RANK_BY_5 = "5"
    RANK_BY_6 = "6"
    RANK_BY_7 = "7"
    RANK_BY_8 = "8"
    RANK_BY_9 = "9"
    RANK_BY_10 = "10"


class GetHotTokensRankingTimeFrameEnum(Enum):
    RANKING_TIME_FRAME_1 = "1"
    RANKING_TIME_FRAME_2 = "2"
    RANKING_TIME_FRAME_3 = "3"
    RANKING_TIME_FRAME_4 = "4"
    RANKING_TIME_FRAME_5 = "5"


class GetTokenTradesTagFilterEnum(Enum):
    TAG_FILTER_1 = "1"
    TAG_FILTER_2 = "2"
    TAG_FILTER_3 = "3"
    TAG_FILTER_4 = "4"
    TAG_FILTER_5 = "5"
    TAG_FILTER_6 = "6"
    TAG_FILTER_7 = "7"


class GetTopTradersTagFilterEnum(Enum):
    TAG_FILTER_1 = "1"
    TAG_FILTER_2 = "2"
    TAG_FILTER_3 = "3"
    TAG_FILTER_4 = "4"
    TAG_FILTER_5 = "5"
    TAG_FILTER_6 = "6"
    TAG_FILTER_7 = "7"


class BuildSwapTransactionApproveTransactionEnum(Enum):
    true = "true"
    false = "false"


class BuildSwapTransactionGasLevelEnum(Enum):
    slow = "slow"
    average = "average"
    fast = "fast"


class BuildSwapTransactionAutoSlippageEnum(Enum):
    true = "true"
    false = "false"


class GetTokenBalancesByAddressExcludeRiskTokenEnum(Enum):
    EXCLUDE_RISK_TOKEN_0 = "0"
    EXCLUDE_RISK_TOKEN_1 = "1"


class GetTotalValueByAddressAssetTypeEnum(Enum):
    ASSET_TYPE_0 = "0"
    ASSET_TYPE_1 = "1"
    ASSET_TYPE_2 = "2"
