# coding: utf-8

"""
Binance Web3 Wallet REST API

Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from binance_sdk_web3_wallet.rest_api.models.get_de_fi_positions_response_data_address_list_inner_protocol_list_inner_pool_list_inner import (
    GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInner,
)
from typing import Set
from typing_extensions import Self


class GetDeFiPositionsResponseDataAddressListInnerProtocolListInner(BaseModel):
    """
    Protocol-level position summary for one address on one chain. `binanceChainId` + `defiProtocolId` uniquely identify a protocol on a chain.
    """  # noqa: E501

    binance_chain_id: Optional[StrictStr] = Field(
        default=None,
        description='Binance chain ID (e.g. "56"=BSC).',
        alias="binanceChainId",
    )
    defi_protocol_id: Optional[StrictStr] = Field(
        default=None,
        description="Protocol identifier consistent with `POST /api/v1/defi/data/protocol/list`. Use this value when calling investment/list, transaction endpoints, etc.",
        alias="defiProtocolId",
    )
    protocol_name: Optional[StrictStr] = Field(
        default=None, description="Protocol display name.", alias="protocolName"
    )
    protocol_total_value: Optional[StrictStr] = Field(
        default=None,
        description="Total position value in this protocol (USD).",
        alias="protocolTotalValue",
    )
    pool_list: Optional[
        List[GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInner]
    ] = Field(
        default=None,
        description="Pools with positions in this protocol.",
        alias="poolList",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "binanceChainId",
        "defiProtocolId",
        "protocolName",
        "protocolTotalValue",
        "poolList",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetDeFiPositionsResponseDataAddressListInnerProtocolListInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in pool_list (list)
        _items = []
        if self.pool_list:
            for _item_pool_list in self.pool_list:
                if _item_pool_list:
                    _items.append(_item_pool_list.to_dict())
            _dict["poolList"] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetDeFiPositionsResponseDataAddressListInnerProtocolListInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "binanceChainId": obj.get("binanceChainId"),
                "defiProtocolId": obj.get("defiProtocolId"),
                "protocolName": obj.get("protocolName"),
                "protocolTotalValue": obj.get("protocolTotalValue"),
                "poolList": (
                    [
                        GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInner.from_dict(
                            _item
                        )
                        for _item in obj["poolList"]
                    ]
                    if obj.get("poolList") is not None
                    else None
                ),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
