# coding: utf-8

"""
Binance Web3 Wallet REST API

Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionCollectionDetail(
    BaseModel
):
    """
    Collection metadata. Null when the collection has no metadata. Fields are null when not applicable.
    """  # noqa: E501

    collection_index: Optional[StrictStr] = Field(
        default=None,
        description="Index of this collection within the pool. For single-asset collections this is the ABI-encoded (left-padded) token address; other pools use their own index format.",
        alias="collectionIndex",
    )
    collection_display_name: Optional[StrictStr] = Field(
        default=None,
        description="Human-readable collection name.",
        alias="collectionDisplayName",
    )
    health_factor: Optional[StrictStr] = Field(
        default=None,
        description="Health factor for lending positions. Null for non-lending positions.",
        alias="healthFactor",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "collectionIndex",
        "collectionDisplayName",
        "healthFactor",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionCollectionDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if collection_index (nullable) is None
        # and model_fields_set contains the field
        if (
            self.collection_index is None
            and "collection_index" in self.model_fields_set
        ):
            _dict["collectionIndex"] = None

        # set to None if collection_display_name (nullable) is None
        # and model_fields_set contains the field
        if (
            self.collection_display_name is None
            and "collection_display_name" in self.model_fields_set
        ):
            _dict["collectionDisplayName"] = None

        # set to None if health_factor (nullable) is None
        # and model_fields_set contains the field
        if self.health_factor is None and "health_factor" in self.model_fields_set:
            _dict["healthFactor"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionCollectionDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "collectionIndex": obj.get("collectionIndex"),
                "collectionDisplayName": obj.get("collectionDisplayName"),
                "healthFactor": obj.get("healthFactor"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
