# coding: utf-8

"""
Binance Wallet REST API

Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
The version of the OpenAPI document: 1.0.0
Contact: wallet-api@binance.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Set
from typing_extensions import Self


class GetTokenAdvancedInfoResponseData(BaseModel):
    """
    GetTokenAdvancedInfoResponseData
    """  # noqa: E501

    binance_chain_id: Optional[StrictStr] = Field(
        default=None,
        description="Chain identifier echoed from the request.",
        alias="binanceChainId",
    )
    token_contract_address: Optional[StrictStr] = Field(
        default=None,
        description="Token contract address echoed from the request.",
        alias="tokenContractAddress",
    )
    is_internal: Optional[StrictInt] = Field(
        default=None,
        description="Whether the token is internal to the platform. 0 = no, 1 = yes.",
        alias="isInternal",
    )
    protocol_id: Optional[StrictInt] = Field(
        default=None,
        description="Protocol identifier the token belongs to (null when none).",
        alias="protocolId",
    )
    progress: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description='Bonding-curve launch progress (range 0–1). Applies to Pump-style tokens; graduated or non-Pump tokens return "1" or null.',
    )
    create_time: Optional[StrictInt] = Field(
        default=None,
        description="Token creation time (Unix milliseconds).",
        alias="createTime",
    )
    creator_address: Optional[StrictStr] = Field(
        default=None,
        description="Token creator wallet address.",
        alias="creatorAddress",
    )
    dev_created_token_count: Optional[StrictInt] = Field(
        default=None,
        description="Total tokens the developer has ever created.",
        alias="devCreatedTokenCount",
    )
    dev_migrated_token_count: Optional[StrictInt] = Field(
        default=None,
        description="Total tokens the developer has successfully launched (migrated).",
        alias="devMigratedTokenCount",
    )
    dev_migrated_token_percent: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Migrated-to-created ratio for the developer (0–1).",
        alias="devMigratedTokenPercent",
    )
    top10_holding_percent: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Combined holding percentage of the top 10 addresses (0–1).",
        alias="top10HoldingPercent",
    )
    dev_holding_percent: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Developer holding percentage (0–1).",
        alias="devHoldingPercent",
    )
    smart_money_holding_percent: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Smart-money holding percentage (0–1).",
        alias="smartMoneyHoldingPercent",
    )
    kol_holding_percent: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="KOL holding percentage (0–1).",
        alias="kolHoldingPercent",
    )
    bundler_holding_percent: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Bundler-address holding percentage (0–1).",
        alias="bundlerHoldingPercent",
    )
    pro_holding_percent: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Pro-trader holding percentage (0–1).",
        alias="proHoldingPercent",
    )
    fresh_wallet_holding_percent: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Fresh-wallet holding percentage (0–1).",
        alias="freshWalletHoldingPercent",
    )
    sniper_holding_percent: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Sniper holding percentage (0–1).",
        alias="sniperHoldingPercent",
    )
    insider_holding_percent: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Insider holding percentage (0–1).",
        alias="insiderHoldingPercent",
    )
    holders: Optional[StrictInt] = Field(
        default=None, description="Number of holding addresses."
    )
    bn_holder_count: Optional[StrictInt] = Field(
        default=None,
        description="Number of BN MPC wallet holders.",
        alias="bnHolderCount",
    )
    bn_trader_count7_d: Optional[StrictInt] = Field(
        default=None,
        description="Number of distinct BN MPC traders in the last 7 days.",
        alias="bnTraderCount7D",
    )
    token_tags: Optional[List[StrictStr]] = Field(
        default=None,
        description="Token tags. See server-side enum for valid values.",
        alias="tokenTags",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "binanceChainId",
        "tokenContractAddress",
        "isInternal",
        "protocolId",
        "progress",
        "createTime",
        "creatorAddress",
        "devCreatedTokenCount",
        "devMigratedTokenCount",
        "devMigratedTokenPercent",
        "top10HoldingPercent",
        "devHoldingPercent",
        "smartMoneyHoldingPercent",
        "kolHoldingPercent",
        "bundlerHoldingPercent",
        "proHoldingPercent",
        "freshWalletHoldingPercent",
        "sniperHoldingPercent",
        "insiderHoldingPercent",
        "holders",
        "bnHolderCount",
        "bnTraderCount7D",
        "tokenTags",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetTokenAdvancedInfoResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if protocol_id (nullable) is None
        # and model_fields_set contains the field
        if self.protocol_id is None and "protocol_id" in self.model_fields_set:
            _dict["protocolId"] = None

        # set to None if progress (nullable) is None
        # and model_fields_set contains the field
        if self.progress is None and "progress" in self.model_fields_set:
            _dict["progress"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetTokenAdvancedInfoResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "binanceChainId": obj.get("binanceChainId"),
                "tokenContractAddress": obj.get("tokenContractAddress"),
                "isInternal": obj.get("isInternal"),
                "protocolId": obj.get("protocolId"),
                "progress": obj.get("progress"),
                "createTime": obj.get("createTime"),
                "creatorAddress": obj.get("creatorAddress"),
                "devCreatedTokenCount": obj.get("devCreatedTokenCount"),
                "devMigratedTokenCount": obj.get("devMigratedTokenCount"),
                "devMigratedTokenPercent": obj.get("devMigratedTokenPercent"),
                "top10HoldingPercent": obj.get("top10HoldingPercent"),
                "devHoldingPercent": obj.get("devHoldingPercent"),
                "smartMoneyHoldingPercent": obj.get("smartMoneyHoldingPercent"),
                "kolHoldingPercent": obj.get("kolHoldingPercent"),
                "bundlerHoldingPercent": obj.get("bundlerHoldingPercent"),
                "proHoldingPercent": obj.get("proHoldingPercent"),
                "freshWalletHoldingPercent": obj.get("freshWalletHoldingPercent"),
                "sniperHoldingPercent": obj.get("sniperHoldingPercent"),
                "insiderHoldingPercent": obj.get("insiderHoldingPercent"),
                "holders": obj.get("holders"),
                "bnHolderCount": obj.get("bnHolderCount"),
                "bnTraderCount7D": obj.get("bnTraderCount7D"),
                "tokenTags": obj.get("tokenTags"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
