# coding: utf-8

"""
Binance Wallet REST API

Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
The version of the OpenAPI document: 1.0.0
Contact: wallet-api@binance.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from binance_sdk_web3_wallet.rest_api.models.get_aggregated_quote_response_data_inner_dex_router_list_inner import (
    GetAggregatedQuoteResponseDataInnerDexRouterListInner,
)
from binance_sdk_web3_wallet.rest_api.models.get_aggregated_quote_response_data_inner_from_token import (
    GetAggregatedQuoteResponseDataInnerFromToken,
)
from binance_sdk_web3_wallet.rest_api.models.get_aggregated_quote_response_data_inner_to_token import (
    GetAggregatedQuoteResponseDataInnerToToken,
)
from typing import Set
from typing_extensions import Self


class GetAggregatedQuoteResponseDataInner(BaseModel):
    """
    GetAggregatedQuoteResponseDataInner
    """  # noqa: E501

    quote_id: Optional[StrictStr] = Field(
        default=None,
        description="Per-route quote identifier (UUID, no dashes). Pass to the swap endpoint to lock in this route.",
        alias="quoteId",
    )
    vendor_name: Optional[StrictStr] = Field(
        default=None,
        description="Source vendor display name. Possible values include LiquidMesh, Lifi, 1inch, Pancake, Jupiter.",
        alias="vendorName",
    )
    binance_chain_id: Optional[StrictStr] = Field(
        default=None,
        description="Chain identifier echoed from the request.",
        alias="binanceChainId",
    )
    from_token_amount: Optional[StrictStr] = Field(
        default=None,
        description="Sell amount echoed from the request (smallest unit, integer string).",
        alias="fromTokenAmount",
    )
    to_token_amount: Optional[StrictStr] = Field(
        default=None,
        description="Estimated buy-token amount returned by the vendor (smallest unit, integer string).",
        alias="toTokenAmount",
    )
    trade_fee: Optional[StrictStr] = Field(
        default=None,
        description="Estimated network fee for this route in USD. Null when the vendor does not return one.",
        alias="tradeFee",
    )
    estimate_gas_fee: Optional[StrictStr] = Field(
        default=None,
        description="Estimated gas in the chain's smallest unit (e.g. wei). May be null on Solana.",
        alias="estimateGasFee",
    )
    price_impact_percent: Optional[StrictStr] = Field(
        default=None,
        description="Estimated price impact percentage. Null when the vendor does not return one.",
        alias="priceImpactPercent",
    )
    router: Optional[StrictStr] = Field(
        default=None,
        description='Routing path description, addresses joined with "--".',
    )
    from_token: Optional[GetAggregatedQuoteResponseDataInnerFromToken] = Field(
        default=None, alias="fromToken"
    )
    to_token: Optional[GetAggregatedQuoteResponseDataInnerToToken] = Field(
        default=None, alias="toToken"
    )
    dex_router_list: Optional[
        List[GetAggregatedQuoteResponseDataInnerDexRouterListInner]
    ] = Field(
        default=None,
        description="Routing path segments. Each segment corresponds to one hop on one DEX protocol; multi-DEX hops are flattened.",
        alias="dexRouterList",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "quoteId",
        "vendorName",
        "binanceChainId",
        "fromTokenAmount",
        "toTokenAmount",
        "tradeFee",
        "estimateGasFee",
        "priceImpactPercent",
        "router",
        "fromToken",
        "toToken",
        "dexRouterList",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetAggregatedQuoteResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of from_token
        if self.from_token:
            _dict["fromToken"] = self.from_token.to_dict()
        # override the default output from pydantic by calling `to_dict()` of to_token
        if self.to_token:
            _dict["toToken"] = self.to_token.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in dex_router_list (list)
        _items = []
        if self.dex_router_list:
            for _item_dex_router_list in self.dex_router_list:
                if _item_dex_router_list:
                    _items.append(_item_dex_router_list.to_dict())
            _dict["dexRouterList"] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if trade_fee (nullable) is None
        # and model_fields_set contains the field
        if self.trade_fee is None and "trade_fee" in self.model_fields_set:
            _dict["tradeFee"] = None

        # set to None if estimate_gas_fee (nullable) is None
        # and model_fields_set contains the field
        if (
            self.estimate_gas_fee is None
            and "estimate_gas_fee" in self.model_fields_set
        ):
            _dict["estimateGasFee"] = None

        # set to None if price_impact_percent (nullable) is None
        # and model_fields_set contains the field
        if (
            self.price_impact_percent is None
            and "price_impact_percent" in self.model_fields_set
        ):
            _dict["priceImpactPercent"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetAggregatedQuoteResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "quoteId": obj.get("quoteId"),
                "vendorName": obj.get("vendorName"),
                "binanceChainId": obj.get("binanceChainId"),
                "fromTokenAmount": obj.get("fromTokenAmount"),
                "toTokenAmount": obj.get("toTokenAmount"),
                "tradeFee": obj.get("tradeFee"),
                "estimateGasFee": obj.get("estimateGasFee"),
                "priceImpactPercent": obj.get("priceImpactPercent"),
                "router": obj.get("router"),
                "fromToken": (
                    GetAggregatedQuoteResponseDataInnerFromToken.from_dict(
                        obj["fromToken"]
                    )
                    if obj.get("fromToken") is not None
                    else None
                ),
                "toToken": (
                    GetAggregatedQuoteResponseDataInnerToToken.from_dict(obj["toToken"])
                    if obj.get("toToken") is not None
                    else None
                ),
                "dexRouterList": (
                    [
                        GetAggregatedQuoteResponseDataInnerDexRouterListInner.from_dict(
                            _item
                        )
                        for _item in obj["dexRouterList"]
                    ]
                    if obj.get("dexRouterList") is not None
                    else None
                ),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
