# coding: utf-8

"""
Binance Web3 Wallet REST API

Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from binance_sdk_web3_wallet.rest_api.models.get_b402_supported_configurations_v1_response1_data_kinds_inner_extra import (
    GetB402SupportedConfigurationsV1Response1DataKindsInnerExtra,
)
from typing import Set
from typing_extensions import Self


class GetB402SupportedConfigurationsV1Response1DataKindsInner(BaseModel):
    """
    GetB402SupportedConfigurationsV1Response1DataKindsInner
    """  # noqa: E501

    x402_version: Optional[StrictInt] = Field(default=None, alias="x402Version")
    scheme: Optional[StrictStr] = None
    network: Optional[StrictStr] = None
    extra: Optional[GetB402SupportedConfigurationsV1Response1DataKindsInnerExtra] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["x402Version", "scheme", "network", "extra"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetB402SupportedConfigurationsV1Response1DataKindsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of extra
        if self.extra:
            _dict["extra"] = self.extra.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetB402SupportedConfigurationsV1Response1DataKindsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "x402Version": obj.get("x402Version"),
                "scheme": obj.get("scheme"),
                "network": obj.get("network"),
                "extra": (
                    GetB402SupportedConfigurationsV1Response1DataKindsInnerExtra.from_dict(
                        obj["extra"]
                    )
                    if obj.get("extra") is not None
                    else None
                ),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
