# coding: utf-8

"""
Binance Wallet REST API

Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
The version of the OpenAPI document: 1.0.0
Contact: wallet-api@binance.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class GetHotTokensResponseDataItemsInner(BaseModel):
    """
    GetHotTokensResponseDataItemsInner
    """  # noqa: E501

    binance_chain_id: Optional[StrictStr] = Field(default=None, alias="binanceChainId")
    token_symbol: Optional[StrictStr] = Field(default=None, alias="tokenSymbol")
    token_logo_url: Optional[StrictStr] = Field(default=None, alias="tokenLogoUrl")
    token_contract_address: Optional[StrictStr] = Field(
        default=None, alias="tokenContractAddress"
    )
    market_cap: Optional[StrictStr] = Field(
        default=None, description="Market cap in USD.", alias="marketCap"
    )
    volume: Optional[StrictStr] = Field(
        default=None, description="Trading volume over the selected time frame in USD."
    )
    change: Optional[StrictStr] = Field(
        default=None,
        description="Price change percentage over the selected time frame (no `%` suffix).",
    )
    unique_traders: Optional[StrictStr] = Field(
        default=None,
        description="Number of unique traders (integer string).",
        alias="uniqueTraders",
    )
    buy_txs: Optional[StrictStr] = Field(
        default=None, description="Buy transaction count.", alias="buyTxs"
    )
    sell_txs: Optional[StrictStr] = Field(
        default=None, description="Sell transaction count.", alias="sellTxs"
    )
    txs: Optional[StrictStr] = Field(
        default=None, description="Total transaction count."
    )
    liquidity: Optional[StrictStr] = Field(
        default=None, description="Liquidity in USD."
    )
    price: Optional[StrictStr] = Field(default=None, description="Token price in USD.")
    holders: Optional[StrictStr] = Field(default=None, description="Holder count.")
    inflow_usd: Optional[StrictStr] = Field(
        default=None,
        description="Net inflow in USD (buy − sell). Positive for inflow, negative for outflow.",
        alias="inflowUsd",
    )
    risk_level: Optional[StrictStr] = Field(
        default=None,
        description="Risk level. 0=undefined, 1=low, 2=medium, 3=mid-high, 4=high, 5=very high.",
        alias="riskLevel",
    )
    dev_holding_percent: Optional[StrictStr] = Field(
        default=None,
        description="Developer holding percentage (no `%` suffix).",
        alias="devHoldingPercent",
    )
    bn_holder_count: Optional[StrictStr] = Field(
        default=None, description="BN holder count.", alias="bnHolderCount"
    )
    top10_holding_percent: Optional[StrictStr] = Field(
        default=None,
        description="Top-10 holding percentage.",
        alias="top10HoldingPercent",
    )
    sniper_holding_percent: Optional[StrictStr] = Field(
        default=None,
        description="Sniper holding percentage.",
        alias="sniperHoldingPercent",
    )
    pro_holding_percent: Optional[StrictStr] = Field(
        default=None,
        description="Pro-trader holding percentage.",
        alias="proHoldingPercent",
    )
    fresh_wallet_holding_percent: Optional[StrictStr] = Field(
        default=None,
        description="Fresh-wallet holding percentage.",
        alias="freshWalletHoldingPercent",
    )
    smart_money_holding_percent: Optional[StrictStr] = Field(
        default=None,
        description="Smart-money holding percentage.",
        alias="smartMoneyHoldingPercent",
    )
    kol_holding_percent: Optional[StrictStr] = Field(
        default=None, description="KOL holding percentage.", alias="kolHoldingPercent"
    )
    insider_holding_percent: Optional[StrictStr] = Field(
        default=None,
        description="Insider holding percentage.",
        alias="insiderHoldingPercent",
    )
    bundler_holding_percent: Optional[StrictStr] = Field(
        default=None,
        description="Bundler holding percentage.",
        alias="bundlerHoldingPercent",
    )
    dev_created_token_count: Optional[StrictStr] = Field(
        default=None,
        description="Developer-created token count.",
        alias="devCreatedTokenCount",
    )
    dev_migrated_token_count: Optional[StrictStr] = Field(
        default=None,
        description="Developer-migrated token count.",
        alias="devMigratedTokenCount",
    )
    dev_migrated_token_percent: Optional[StrictStr] = Field(
        default=None,
        description="Developer-migrated token percentage.",
        alias="devMigratedTokenPercent",
    )
    token_tags: Optional[List[StrictStr]] = Field(
        default=None, description="Token tags.", alias="tokenTags"
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "binanceChainId",
        "tokenSymbol",
        "tokenLogoUrl",
        "tokenContractAddress",
        "marketCap",
        "volume",
        "change",
        "uniqueTraders",
        "buyTxs",
        "sellTxs",
        "txs",
        "liquidity",
        "price",
        "holders",
        "inflowUsd",
        "riskLevel",
        "devHoldingPercent",
        "bnHolderCount",
        "top10HoldingPercent",
        "sniperHoldingPercent",
        "proHoldingPercent",
        "freshWalletHoldingPercent",
        "smartMoneyHoldingPercent",
        "kolHoldingPercent",
        "insiderHoldingPercent",
        "bundlerHoldingPercent",
        "devCreatedTokenCount",
        "devMigratedTokenCount",
        "devMigratedTokenPercent",
        "tokenTags",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetHotTokensResponseDataItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if token_logo_url (nullable) is None
        # and model_fields_set contains the field
        if self.token_logo_url is None and "token_logo_url" in self.model_fields_set:
            _dict["tokenLogoUrl"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetHotTokensResponseDataItemsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "binanceChainId": obj.get("binanceChainId"),
                "tokenSymbol": obj.get("tokenSymbol"),
                "tokenLogoUrl": obj.get("tokenLogoUrl"),
                "tokenContractAddress": obj.get("tokenContractAddress"),
                "marketCap": obj.get("marketCap"),
                "volume": obj.get("volume"),
                "change": obj.get("change"),
                "uniqueTraders": obj.get("uniqueTraders"),
                "buyTxs": obj.get("buyTxs"),
                "sellTxs": obj.get("sellTxs"),
                "txs": obj.get("txs"),
                "liquidity": obj.get("liquidity"),
                "price": obj.get("price"),
                "holders": obj.get("holders"),
                "inflowUsd": obj.get("inflowUsd"),
                "riskLevel": obj.get("riskLevel"),
                "devHoldingPercent": obj.get("devHoldingPercent"),
                "bnHolderCount": obj.get("bnHolderCount"),
                "top10HoldingPercent": obj.get("top10HoldingPercent"),
                "sniperHoldingPercent": obj.get("sniperHoldingPercent"),
                "proHoldingPercent": obj.get("proHoldingPercent"),
                "freshWalletHoldingPercent": obj.get("freshWalletHoldingPercent"),
                "smartMoneyHoldingPercent": obj.get("smartMoneyHoldingPercent"),
                "kolHoldingPercent": obj.get("kolHoldingPercent"),
                "insiderHoldingPercent": obj.get("insiderHoldingPercent"),
                "bundlerHoldingPercent": obj.get("bundlerHoldingPercent"),
                "devCreatedTokenCount": obj.get("devCreatedTokenCount"),
                "devMigratedTokenCount": obj.get("devMigratedTokenCount"),
                "devMigratedTokenPercent": obj.get("devMigratedTokenPercent"),
                "tokenTags": obj.get("tokenTags"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
