# coding: utf-8

"""
Binance Web3 Wallet REST API

Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from binance_sdk_web3_wallet.rest_api.models.position_resp_token_list_supply_inner import (
    PositionRespTokenListSupplyInner,
)
from typing import Set
from typing_extensions import Self


class PositionRespTokenList(BaseModel):
    """
    Token breakdown grouped by role. Keys: `supply` (supplied assets), `borrow` (borrowed assets, lending positions), `reward` (claimable rewards), `farming_reward` (MasterChef farming incentives). A key is absent when the position has no tokens in that role.
    """  # noqa: E501

    supply: Optional[List[PositionRespTokenListSupplyInner]] = None
    borrow: Optional[List[PositionRespTokenListSupplyInner]] = None
    reward: Optional[List[PositionRespTokenListSupplyInner]] = None
    farming_reward: Optional[List[PositionRespTokenListSupplyInner]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["supply", "borrow", "reward", "farming_reward"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PositionRespTokenList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in supply (list)
        _items = []
        if self.supply:
            for _item_supply in self.supply:
                if _item_supply:
                    _items.append(_item_supply.to_dict())
            _dict["supply"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in borrow (list)
        _items = []
        if self.borrow:
            for _item_borrow in self.borrow:
                if _item_borrow:
                    _items.append(_item_borrow.to_dict())
            _dict["borrow"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in reward (list)
        _items = []
        if self.reward:
            for _item_reward in self.reward:
                if _item_reward:
                    _items.append(_item_reward.to_dict())
            _dict["reward"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in farming_reward (list)
        _items = []
        if self.farming_reward:
            for _item_farming_reward in self.farming_reward:
                if _item_farming_reward:
                    _items.append(_item_farming_reward.to_dict())
            _dict["farming_reward"] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PositionRespTokenList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "supply": (
                    [
                        PositionRespTokenListSupplyInner.from_dict(_item)
                        for _item in obj["supply"]
                    ]
                    if obj.get("supply") is not None
                    else None
                ),
                "borrow": (
                    [
                        PositionRespTokenListSupplyInner.from_dict(_item)
                        for _item in obj["borrow"]
                    ]
                    if obj.get("borrow") is not None
                    else None
                ),
                "reward": (
                    [
                        PositionRespTokenListSupplyInner.from_dict(_item)
                        for _item in obj["reward"]
                    ]
                    if obj.get("reward") is not None
                    else None
                ),
                "farming_reward": (
                    [
                        PositionRespTokenListSupplyInner.from_dict(_item)
                        for _item in obj["farming_reward"]
                    ]
                    if obj.get("farming_reward") is not None
                    else None
                ),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
