# coding: utf-8

"""
Binance Web3 Wallet REST API

Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from binance_sdk_web3_wallet.rest_api.models.position_resp_position_detail import (
    PositionRespPositionDetail,
)
from binance_sdk_web3_wallet.rest_api.models.position_resp_token_list import (
    PositionRespTokenList,
)
from typing import Set
from typing_extensions import Self


class PositionCollectionRespPositionListInner(BaseModel):
    """
    A single DeFi position with underlying asset and token breakdown.
    """  # noqa: E501

    position_id: Optional[StrictStr] = Field(
        default=None,
        description="Unique position identifier (64-char hex, no `0x` prefix).",
        alias="positionId",
    )
    underlying_asset_name: Optional[StrictStr] = Field(
        default=None,
        description='Display name of the underlying asset (e.g. "USDT-USDC", "lisUSD").',
        alias="underlyingAssetName",
    )
    underlying_asset_id: Optional[StrictStr] = Field(
        default=None,
        description="Underlying asset identifier (64-char hex, no `0x` prefix). Hashed from the pool and underlying token addresses.",
        alias="underlyingAssetId",
    )
    asset_type: Optional[StrictStr] = Field(
        default=None,
        description="Asset structure type. Null for a regular position; `locked` for a locked position (e.g. locked staking — check `unlockTime` on positionDetail); `farming` for a MasterChef-style farming position (rewards accrue under the `farming_reward` token group).",
        alias="assetType",
    )
    investment_ids: Optional[List[StrictStr]] = Field(
        default=None,
        description="Related investment IDs (64-char hex, no `0x` prefix). Use with `POST /api/v1/defi/data/investment/detail`. Usually a single entry; a position can relate to several investments when the pool stacks products on top of each other (e.g. a farming position wraps the underlying LP investment plus its incentive product, or a staked vault layers a receipt token over the base deposit). When there are several, query each with investment/detail and pick by the action you want to perform — redeeming the principal uses the base investment, claiming farming incentives uses the incentive one.",
        alias="investmentIds",
    )
    position_detail: Optional[PositionRespPositionDetail] = Field(
        default=None, alias="positionDetail"
    )
    position_value: Optional[StrictStr] = Field(
        default=None,
        description="Total position value in USD (sum of all token values; may be negative for borrow positions).",
        alias="positionValue",
    )
    token_list: Optional[PositionRespTokenList] = Field(default=None, alias="tokenList")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "positionId",
        "underlyingAssetName",
        "underlyingAssetId",
        "assetType",
        "investmentIds",
        "positionDetail",
        "positionValue",
        "tokenList",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PositionCollectionRespPositionListInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of position_detail
        if self.position_detail:
            _dict["positionDetail"] = self.position_detail.to_dict()
        # override the default output from pydantic by calling `to_dict()` of token_list
        if self.token_list:
            _dict["tokenList"] = self.token_list.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if asset_type (nullable) is None
        # and model_fields_set contains the field
        if self.asset_type is None and "asset_type" in self.model_fields_set:
            _dict["assetType"] = None

        # set to None if position_detail (nullable) is None
        # and model_fields_set contains the field
        if self.position_detail is None and "position_detail" in self.model_fields_set:
            _dict["positionDetail"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PositionCollectionRespPositionListInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "positionId": obj.get("positionId"),
                "underlyingAssetName": obj.get("underlyingAssetName"),
                "underlyingAssetId": obj.get("underlyingAssetId"),
                "assetType": obj.get("assetType"),
                "investmentIds": obj.get("investmentIds"),
                "positionDetail": (
                    PositionRespPositionDetail.from_dict(obj["positionDetail"])
                    if obj.get("positionDetail") is not None
                    else None
                ),
                "positionValue": obj.get("positionValue"),
                "tokenList": (
                    PositionRespTokenList.from_dict(obj["tokenList"])
                    if obj.get("tokenList") is not None
                    else None
                ),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
