# coding: utf-8

"""
Binance Web3 Wallet REST API

Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from binance_sdk_web3_wallet.rest_api.models.pool_resp_pool_detail import (
    PoolRespPoolDetail,
)
from binance_sdk_web3_wallet.rest_api.models.pool_resp_position_collection_list_inner import (
    PoolRespPositionCollectionListInner,
)
from typing import Set
from typing_extensions import Self


class ProtocolRespPoolListInner(BaseModel):
    """
    A pool containing position collections.
    """  # noqa: E501

    bn_pool_id: Optional[StrictStr] = Field(
        default=None,
        description="Pool identifier (`0x` + 64-char hex).",
        alias="bnPoolId",
    )
    pool_ca: Optional[StrictStr] = Field(
        default=None, description="Pool contract address.", alias="poolCa"
    )
    pool_type: Optional[StrictStr] = Field(
        default=None,
        description="Pool type. Complete value set: `Lending` (supply/borrow market), `Staked` (native staking), `Yield` (yield vault / receipt token), `Deposit` (fixed deposit), `Rewards` (reward claims, e.g. PancakeSwap Infinity), `Liquidity Pool` (AMM / concentrated liquidity), `Farming` (MasterChef farming), `Locked` (locked staking with unlock time), `Vesting` (vesting schedule). Treat unknown values as generic display.",
        alias="poolType",
    )
    position_collection_list: Optional[List[PoolRespPositionCollectionListInner]] = (
        Field(default=None, alias="positionCollectionList")
    )
    pool_detail: Optional[PoolRespPoolDetail] = Field(default=None, alias="poolDetail")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "bnPoolId",
        "poolCa",
        "poolType",
        "positionCollectionList",
        "poolDetail",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def is_array(cls) -> bool:
        return False

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProtocolRespPoolListInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in position_collection_list (list)
        _items = []
        if self.position_collection_list:
            for _item_position_collection_list in self.position_collection_list:
                if _item_position_collection_list:
                    _items.append(_item_position_collection_list.to_dict())
            _dict["positionCollectionList"] = _items
        # override the default output from pydantic by calling `to_dict()` of pool_detail
        if self.pool_detail:
            _dict["poolDetail"] = self.pool_detail.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if pool_detail (nullable) is None
        # and model_fields_set contains the field
        if self.pool_detail is None and "pool_detail" in self.model_fields_set:
            _dict["poolDetail"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProtocolRespPoolListInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "bnPoolId": obj.get("bnPoolId"),
                "poolCa": obj.get("poolCa"),
                "poolType": obj.get("poolType"),
                "positionCollectionList": (
                    [
                        PoolRespPositionCollectionListInner.from_dict(_item)
                        for _item in obj["positionCollectionList"]
                    ]
                    if obj.get("positionCollectionList") is not None
                    else None
                ),
                "poolDetail": (
                    PoolRespPoolDetail.from_dict(obj["poolDetail"])
                    if obj.get("poolDetail") is not None
                    else None
                ),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
