"""
Binance Web3 WebSocket Streams

Real-time on-chain data streaming over WebSocket for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from binance_common.errors import RequiredError
from binance_web3_common.utils import ws_streams_placeholder
from binance_web3_common.websocket import (
    WebSocketStreamBase,
    RequestStream,
    RequestStreamHandle,
)

from ..models import CandlestickStreamResponse
from ..models import MarketStatsStreamResponse
from ..models import PriceStreamResponse
from ..models import RealTimeTradesStreamResponse


from typing import Optional, Union


class MarketApi:
    """Client for MarketApi endpoints."""

    def __init__(self, websocket_base: WebSocketStreamBase) -> None:
        self.websocket_base = websocket_base

    async def candlestick_stream(
        self,
        bar: Union[str, None],
        chain_id: Union[str, None],
        contract_address: Union[str, None],
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            Candlestick Stream
            /w3w@onchainos@pub@candles@<bar>@<chainId>@<contractAddress>
            https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/ws-streams/market#candlestick-stream

            Push token candlestick (K-line) data in real time. The current (unclosed) candle keeps updating as new trades occur.

        Update Speed: Real-time

            Args:
                    bar (Union[str, None]): K-line interval. Enum: 1s, 5s, 30s, 1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M.
                    chain_id (Union[str, None]): Chain identifier, e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana. Full supported-chain list: same as the ["supported/chain"](/catalog/web3-wallet/api/rest-api/general-data#get-supported-chains) endpoint.
                    contract_address (Union[str, None]): Token contract address.
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if bar is None:
            raise RequiredError(
                field="bar", error_message="Missing required parameter 'bar'"
            )
        if chain_id is None:
            raise RequiredError(
                field="chain_id", error_message="Missing required parameter 'chain_id'"
            )
        if contract_address is None:
            raise RequiredError(
                field="contract_address",
                error_message="Missing required parameter 'contract_address'",
            )

        stream = ws_streams_placeholder(
            "/w3w@onchainos@pub@candles@<bar>@<chainId>@<contractAddress>".replace(
                "/", "", 1
            ),
            {
                "bar": bar,
                "chain_id": chain_id,
                "contract_address": contract_address,
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=CandlestickStreamResponse,
            stream_url="",
        )

    async def market_stats_stream(
        self,
        chain_id: Union[str, None],
        contract_address: Union[str, None],
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            Market Stats Stream
            /w3w@onchainos@pub@tx-data@<chainId>@<contractAddress>
            https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/ws-streams/market#market-stats-stream

            Push token market data. Rate-limited to at most once per second per token: if a token's data changes within a 1-second window, the latest snapshot is pushed once (multiple changes are coalesced into the latest value); if there is no change, nothing is pushed.

        Update Speed: Real-time

            Args:
                    chain_id (Union[str, None]): Chain identifier, e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana. Full supported-chain list: same as the ["supported/chain"](/catalog/web3-wallet/api/rest-api/general-data#get-supported-chains) endpoint.
                    contract_address (Union[str, None]): Token contract address.
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if chain_id is None:
            raise RequiredError(
                field="chain_id", error_message="Missing required parameter 'chain_id'"
            )
        if contract_address is None:
            raise RequiredError(
                field="contract_address",
                error_message="Missing required parameter 'contract_address'",
            )

        stream = ws_streams_placeholder(
            "/w3w@onchainos@pub@tx-data@<chainId>@<contractAddress>".replace(
                "/", "", 1
            ),
            {
                "chain_id": chain_id,
                "contract_address": contract_address,
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=MarketStatsStreamResponse,
            stream_url="",
        )

    async def price_stream(
        self,
        chain_id: Union[str, None],
        contract_address: Union[str, None],
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            Price Stream
            /w3w@onchainos@pub@price@<chainId>@<contractAddress>
            https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/ws-streams/market#price-stream

            Push token price updates. Triggered every time a token's price changes.

        Update Speed: Real-time

            Args:
                    chain_id (Union[str, None]): Chain identifier, e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana. Full supported-chain list: same as the ["supported/chain"](/catalog/web3-wallet/api/rest-api/general-data#get-supported-chains) endpoint.
                    contract_address (Union[str, None]): Token contract address.
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if chain_id is None:
            raise RequiredError(
                field="chain_id", error_message="Missing required parameter 'chain_id'"
            )
        if contract_address is None:
            raise RequiredError(
                field="contract_address",
                error_message="Missing required parameter 'contract_address'",
            )

        stream = ws_streams_placeholder(
            "/w3w@onchainos@pub@price@<chainId>@<contractAddress>".replace("/", "", 1),
            {
                "chain_id": chain_id,
                "contract_address": contract_address,
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=PriceStreamResponse,
            stream_url="",
        )

    async def real_time_trades_stream(
        self,
        chain_id: Union[str, None],
        contract_address: Union[str, None],
        id: Optional[str] = None,
    ) -> RequestStreamHandle:
        r"""
            Real-Time Trades Stream
            /w3w@onchainos@pub@tx@<chainId>@<contractAddress>
            https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/ws-streams/market#real-time-trades-stream

            Push real-time token trade history. Triggered on every new transaction.

        Update Speed: Real-time

            Args:
                    chain_id (Union[str, None]): Chain identifier, e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana. Full supported-chain list: same as the ["supported/chain"](/catalog/web3-wallet/api/rest-api/general-data#get-supported-chains) endpoint.
                    contract_address (Union[str, None]): Token contract address.
                    id (Optional[str] = None): Unique WebSocket request ID.

            Returns:
                RequestStreamHandle

            Raises:
                RequiredError: If a required parameter is missing.

        """

        if chain_id is None:
            raise RequiredError(
                field="chain_id", error_message="Missing required parameter 'chain_id'"
            )
        if contract_address is None:
            raise RequiredError(
                field="contract_address",
                error_message="Missing required parameter 'contract_address'",
            )

        stream = ws_streams_placeholder(
            "/w3w@onchainos@pub@tx@<chainId>@<contractAddress>".replace("/", "", 1),
            {
                "chain_id": chain_id,
                "contract_address": contract_address,
                "id": id,
            },
        )

        return await RequestStream(
            self.websocket_base,
            stream=stream,
            response_model=RealTimeTradesStreamResponse,
            stream_url="",
        )
