"""
Binance Web3 Wallet REST API

Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import requests
from typing import Optional, List, TypeVar, Union
from binance_common.configuration import ConfigurationRestAPI
from binance_common.models import ApiResponse
from binance_common.signature import Signers
from binance_common.utils import send_request
from .api.market_api import MarketApi
from .api.trading_api import TradingApi
from .api.transaction_api import TransactionApi
from .api.wallet_api import WalletApi

from .models import GetCandlesResponse
from .models import GetHoldersRankingResponse
from .models import GetHotTokenListResponse
from .models import GetSupportedChainsResponse
from .models import GetTokenAdvancedInfoResponse
from .models import GetTokenBasicInfoResponse
from .models import GetTokenPriceResponse
from .models import GetTokenTradesResponse
from .models import GetTokenTradingInfoResponse
from .models import GetTopLiquidityPoolsResponse
from .models import GetTopTradersResponse
from .models import SearchTokenResponse
from .models import GetCandlesBarEnum
from .models import GetHoldersRankingTagFilterEnum
from .models import GetHotTokenListRankByEnum
from .models import GetHotTokenListRankingTimeFrameEnum
from .models import GetTokenTradesTagFilterEnum
from .models import GetTopTradersTagFilterEnum
from .models import BuildSwapTransactionResponse
from .models import GetAggregatedQuoteResponse
from .models import GetAggregatorSupportedChainsResponse
from .models import GetErc20ApproveTransactionResponse
from .models import GetTransactionStatusResponse
from .models import BuildSwapTransactionApproveTransactionEnum
from .models import BuildSwapTransactionGasLevelEnum
from .models import BuildSwapTransactionAutoSlippageEnum
from .models import BroadcastTransactionsResponse
from .models import GetBroadcastOrdersResponse
from .models import GetGasLimitResponse
from .models import GetGasPriceResponse
from .models import GetTransactionSupportedChainsResponse
from .models import SimulateTransactionsResponse
from .models import GetGasLimitRequestEvmTx
from .models import GetGasLimitRequestSolTx
from .models import SimulateTransactionsRequestEvmTx
from .models import SimulateTransactionsRequestSolTx
from .models import GetAllTokenBalancesByAddressResponse
from .models import GetTokenBalancesByAddressResponse
from .models import GetTransactionDetailByHashResponse
from .models import GetTransactionsByAddressResponse
from .models import GetWalletSupportedChainsResponse
from .models import GetTokenBalancesByAddressRequestTokenContractAddressesInner
from .models import GetTokenBalancesByAddressExcludeRiskTokenEnum


T = TypeVar("T")


class Web3WalletRestAPI:
    def __init__(
        self,
        configuration: ConfigurationRestAPI,
    ) -> None:
        self.configuration = configuration
        self._session = requests.Session()
        self._signer = (
            Signers.get_signer(
                configuration.private_key, configuration.private_key_passphrase
            )
            if configuration.private_key is not None
            else None
        )

        self._marketApi = MarketApi(self.configuration, self._session, self._signer)
        self._tradingApi = TradingApi(self.configuration, self._session, self._signer)
        self._transactionApi = TransactionApi(
            self.configuration, self._session, self._signer
        )
        self._walletApi = WalletApi(self.configuration, self._session, self._signer)

    def send_request(
        self,
        endpoint: str,
        method: str,
        query_params: Optional[dict] = None,
        body_params: Optional[dict] = None,
    ) -> ApiResponse[T]:
        """
        Sends an request to the Binance REST API.

        Args:
            endpoint (str): The API endpoint path to send the request to.
            method (str): The HTTP method to use for the request (e.g. "GET", "POST", "PUT", "DELETE").
            query_params (Optional[dict]): The request payload as a dictionary, or None if no payload is required.
            body_params (Optional[dict]): The request body as a dictionary, or None if no body is required.

        Returns:
            ApiResponse[T]: The API response, where T is the expected response type.
        """
        return send_request[T](
            self._session,
            self.configuration,
            method,
            endpoint,
            query_params,
            body_params,
        )

    def send_signed_request(
        self,
        endpoint: str,
        method: str,
        query_params: Optional[dict] = None,
        body_params: Optional[dict] = None,
    ) -> ApiResponse[T]:
        """
        Sends a signed request to the Binance REST API.

        Args:
            endpoint (str): The API endpoint path to send the request to.
            method (str): The HTTP method to use for the request (e.g. "GET", "POST", "PUT", "DELETE").
            query_params (Optional[dict]): The request payload as a dictionary, or None if no payload is required.
            body_params (Optional[dict]): The request body as a dictionary, or None if no body is required.

        Returns:
            ApiResponse[T]: The API response, where T is the expected response type.
        """
        return send_request[T](
            self._session,
            self.configuration,
            method,
            endpoint,
            query_params,
            body_params,
            is_signed=True,
            signer=self._signer,
        )

    def get_candles(
        self,
        binance_chain_id: Union[str, None],
        token_contract_address: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        bar: Optional[GetCandlesBarEnum] = None,
        after: Optional[int] = None,
        before: Optional[int] = None,
        limit: Optional[int] = None,
    ) -> ApiResponse[GetCandlesResponse]:
        """
        Get Candles

        Return candlestick (K-line) data for a token.

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
            token_contract_address (Union[str, None]): Token contract address.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            bar (Optional[GetCandlesBarEnum] = None): Candlestick time granularity, default "1m" (1 minute). Available values: 1s (1 second), 5s (5 seconds), 30s (30 seconds), 1m (1 minute), 3m (3 minutes), 5m (5 minutes), 15m (15 minutes), 30m (30 minutes), 1h (1 hour), 2h (2 hours), 4h (4 hours), 6h (6 hours), 8h (8 hours), 12h (12 hours), 1d (1 day), 3d (3 days), 1w (1 week), 1M (1 month).
            after (Optional[int] = None): End time for the query, Unix millisecond timestamp. Returns candles earlier than this time (exclusive).
            before (Optional[int] = None): Start time for the query, Unix millisecond timestamp. Returns candles later than this time (exclusive).
            limit (Optional[int] = None): Number of candles to return. Defaults to 100.

        Returns:
            ApiResponse[GetCandlesResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._marketApi.get_candles(
            binance_chain_id,
            token_contract_address,
            recv_window,
            nonce,
            bar,
            after,
            before,
            limit,
        )

    def get_holders_ranking(
        self,
        binance_chain_id: Union[str, None],
        token_contract_address: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        tag_filter: Optional[GetHoldersRankingTagFilterEnum] = None,
    ) -> ApiResponse[GetHoldersRankingResponse]:
        """
        Get Holders Ranking

        Return the holders ranking list for a token, including holding amount, holding percentage, native-token balance, average buy/sell price, realized PnL, and funding source. Up to 100 records. Pagination is not supported.

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier.
            token_contract_address (Union[str, None]): Token contract address.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            tag_filter (Optional[GetHoldersRankingTagFilterEnum] = None): Address tag filter, single selection only. Returns all holder addresses (by holding amount descending) when omitted; returns addresses matching the specified tag when provided. Mapping: 1=KOL, 2=Developer, 3=Smart Money, 4=Insider, 5=Sniper, 6=Bundler.

        Returns:
            ApiResponse[GetHoldersRankingResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._marketApi.get_holders_ranking(
            binance_chain_id, token_contract_address, recv_window, nonce, tag_filter
        )

    def get_hot_token_list(
        self,
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        binance_chain_id: Optional[str] = None,
        rank_by: Optional[GetHotTokenListRankByEnum] = None,
        ranking_time_frame: Optional[GetHotTokenListRankingTimeFrameEnum] = None,
        price_change_percent_min: Optional[str] = None,
        price_change_percent_max: Optional[str] = None,
        volume_min: Optional[str] = None,
        volume_max: Optional[str] = None,
        txs_min: Optional[str] = None,
        txs_max: Optional[str] = None,
        market_cap_min: Optional[str] = None,
        market_cap_max: Optional[str] = None,
        liquidity_min: Optional[str] = None,
        liquidity_max: Optional[str] = None,
        dev_holding_percent_min: Optional[str] = None,
        dev_holding_percent_max: Optional[str] = None,
        inflow_usd_min: Optional[str] = None,
        inflow_usd_max: Optional[str] = None,
        holders_min: Optional[str] = None,
        holders_max: Optional[str] = None,
        bn_holder_count_min: Optional[str] = None,
        bn_holder_count_max: Optional[str] = None,
        top10_holding_percent_min: Optional[str] = None,
        top10_holding_percent_max: Optional[str] = None,
        sniper_holding_percent_min: Optional[str] = None,
        sniper_holding_percent_max: Optional[str] = None,
        smart_money_holding_percent_min: Optional[str] = None,
        smart_money_holding_percent_max: Optional[str] = None,
        kol_holding_percent_min: Optional[str] = None,
        kol_holding_percent_max: Optional[str] = None,
        pro_holding_percent_min: Optional[str] = None,
        pro_holding_percent_max: Optional[str] = None,
        fresh_wallet_holding_percent_min: Optional[str] = None,
        fresh_wallet_holding_percent_max: Optional[str] = None,
        insider_holding_percent_min: Optional[str] = None,
        insider_holding_percent_max: Optional[str] = None,
        bundler_holding_percent_min: Optional[str] = None,
        bundler_holding_percent_max: Optional[str] = None,
        dev_created_token_count_min: Optional[str] = None,
        dev_created_token_count_max: Optional[str] = None,
        dev_migrated_token_count_min: Optional[str] = None,
        dev_migrated_token_count_max: Optional[str] = None,
        dev_migrated_token_percent_min: Optional[str] = None,
        dev_migrated_token_percent_max: Optional[str] = None,
        is_dev_sold_all: Optional[bool] = None,
        is_dev_burned: Optional[bool] = None,
        is_mint: Optional[bool] = None,
        is_freeze: Optional[bool] = None,
        is_hide_wash_trading_tokens: Optional[bool] = None,
        is_hide_dev_wash_trading_tokens: Optional[bool] = None,
        is_hide_internal_wash_trading_tokens: Optional[bool] = None,
        page_id: Optional[int] = None,
        size: Optional[int] = None,
    ) -> ApiResponse[GetHotTokenListResponse]:
        """
        Get Hot Token List

        Get hot token ranking list. Supports sorting by volume, price change, market cap, etc., with filters for holding distribution, developer behavior, liquidity, and more.

        Args:
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            binance_chain_id (Optional[str] = None): Chain identifier. Single value only. Omit to return mixed results across all chains.
            rank_by (Optional[GetHotTokenListRankByEnum] = None): Ranking field. 1=price, 2=price change, 3=transactions, 4=volume, 5=market cap, 6=liquidity, 7=creation time, 8=holders, 9=Binance MPC wallet holders, 10=net inflow.
            ranking_time_frame (Optional[GetHotTokenListRankingTimeFrameEnum] = None): Data time range. 1=1 min, 2=5 min, 3=1 hour, 4=4 hours, 5=24 hours. Default 1 hour.
            price_change_percent_min (Optional[str] = None): Minimum price change filter. "5" means 5%.
            price_change_percent_max (Optional[str] = None): Maximum price change filter. "100" means 100%.
            volume_min (Optional[str] = None): Minimum volume filter, denominated in USD.
            volume_max (Optional[str] = None): Maximum volume filter, denominated in USD.
            txs_min (Optional[str] = None): Minimum transaction count.
            txs_max (Optional[str] = None): Maximum transaction count.
            market_cap_min (Optional[str] = None): Minimum market cap filter, denominated in USD.
            market_cap_max (Optional[str] = None): Maximum market cap filter, denominated in USD.
            liquidity_min (Optional[str] = None): Minimum liquidity filter, denominated in USD.
            liquidity_max (Optional[str] = None): Maximum liquidity filter, denominated in USD.
            dev_holding_percent_min (Optional[str] = None): Minimum developer holding percentage filter. "5" means 5%.
            dev_holding_percent_max (Optional[str] = None): Maximum developer holding percentage filter. "5" means 5%.
            inflow_usd_min (Optional[str] = None): Minimum net inflow filter, denominated in USD.
            inflow_usd_max (Optional[str] = None): Maximum net inflow filter, denominated in USD.
            holders_min (Optional[str] = None): Minimum holder count.
            holders_max (Optional[str] = None): Maximum holder count.
            bn_holder_count_min (Optional[str] = None): Minimum Binance MPC wallet holders.
            bn_holder_count_max (Optional[str] = None): Maximum Binance MPC wallet holders.
            top10_holding_percent_min (Optional[str] = None): Minimum top-10 holding percentage. "5" means 5%.
            top10_holding_percent_max (Optional[str] = None): Maximum top-10 holding percentage. "5" means 5%.
            sniper_holding_percent_min (Optional[str] = None): Minimum sniper holding percentage. "5" means 5%.
            sniper_holding_percent_max (Optional[str] = None): Maximum sniper holding percentage. "5" means 5%.
            smart_money_holding_percent_min (Optional[str] = None): Minimum smart-money holding percentage. "5" means 5%.
            smart_money_holding_percent_max (Optional[str] = None): Maximum smart-money holding percentage. "5" means 5%.
            kol_holding_percent_min (Optional[str] = None): Minimum KOL holding percentage. "5" means 5%.
            kol_holding_percent_max (Optional[str] = None): Maximum KOL holding percentage. "5" means 5%.
            pro_holding_percent_min (Optional[str] = None): Minimum pro-trader holding percentage. "5" means 5%.
            pro_holding_percent_max (Optional[str] = None): Maximum pro-trader holding percentage. "5" means 5%.
            fresh_wallet_holding_percent_min (Optional[str] = None): Minimum fresh-wallet holding percentage. "5" means 5%.
            fresh_wallet_holding_percent_max (Optional[str] = None): Maximum fresh-wallet holding percentage. "5" means 5%.
            insider_holding_percent_min (Optional[str] = None): Minimum insider holding percentage. "5" means 5%.
            insider_holding_percent_max (Optional[str] = None): Maximum insider holding percentage. "5" means 5%.
            bundler_holding_percent_min (Optional[str] = None): Minimum bundler holding percentage. "5" means 5%.
            bundler_holding_percent_max (Optional[str] = None): Maximum bundler holding percentage. "5" means 5%.
            dev_created_token_count_min (Optional[str] = None): Minimum developer-created token count.
            dev_created_token_count_max (Optional[str] = None): Maximum developer-created token count.
            dev_migrated_token_count_min (Optional[str] = None): Minimum developer-migrated token count.
            dev_migrated_token_count_max (Optional[str] = None): Maximum developer-migrated token count.
            dev_migrated_token_percent_min (Optional[str] = None): Minimum developer-migrated token percentage. "5" means 5%.
            dev_migrated_token_percent_max (Optional[str] = None): Maximum developer-migrated token percentage. "5" means 5%.
            is_dev_sold_all (Optional[bool] = None): When set to true, returns only tokens where the developer has sold all holdings. Not filtered when omitted or false.
            is_dev_burned (Optional[bool] = None): When set to true, returns only tokens where the developer has burned tokens. Not filtered when omitted or false.
            is_mint (Optional[bool] = None): When set to true, excludes tokens with minting capability. Default false.
            is_freeze (Optional[bool] = None): When set to true, excludes tokens with freeze capability. Default false.
            is_hide_wash_trading_tokens (Optional[bool] = None): When set to true, excludes tokens with wash trading behavior. Default true.
            is_hide_dev_wash_trading_tokens (Optional[bool] = None): When set to true, excludes tokens where the developer has wash trading behavior. Default true.
            is_hide_internal_wash_trading_tokens (Optional[bool] = None): When set to true, excludes tokens where insiders have wash trading behavior. Default true.
            page_id (Optional[int] = None): Pagination identifier. Do not pass on the first request; pass the page value from the previous response to get the next page.
            size (Optional[int] = None): Page size. Maximum 100. Defaults to 100.

        Returns:
            ApiResponse[GetHotTokenListResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._marketApi.get_hot_token_list(
            recv_window,
            nonce,
            binance_chain_id,
            rank_by,
            ranking_time_frame,
            price_change_percent_min,
            price_change_percent_max,
            volume_min,
            volume_max,
            txs_min,
            txs_max,
            market_cap_min,
            market_cap_max,
            liquidity_min,
            liquidity_max,
            dev_holding_percent_min,
            dev_holding_percent_max,
            inflow_usd_min,
            inflow_usd_max,
            holders_min,
            holders_max,
            bn_holder_count_min,
            bn_holder_count_max,
            top10_holding_percent_min,
            top10_holding_percent_max,
            sniper_holding_percent_min,
            sniper_holding_percent_max,
            smart_money_holding_percent_min,
            smart_money_holding_percent_max,
            kol_holding_percent_min,
            kol_holding_percent_max,
            pro_holding_percent_min,
            pro_holding_percent_max,
            fresh_wallet_holding_percent_min,
            fresh_wallet_holding_percent_max,
            insider_holding_percent_min,
            insider_holding_percent_max,
            bundler_holding_percent_min,
            bundler_holding_percent_max,
            dev_created_token_count_min,
            dev_created_token_count_max,
            dev_migrated_token_count_min,
            dev_migrated_token_count_max,
            dev_migrated_token_percent_min,
            dev_migrated_token_percent_max,
            is_dev_sold_all,
            is_dev_burned,
            is_mint,
            is_freeze,
            is_hide_wash_trading_tokens,
            is_hide_dev_wash_trading_tokens,
            is_hide_internal_wash_trading_tokens,
            page_id,
            size,
        )

    def get_supported_chains(
        self,
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetSupportedChainsResponse]:
        """
        Get Supported Chains

        Return the list of blockchains supported by the market service.

        Args:
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[GetSupportedChainsResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._marketApi.get_supported_chains(recv_window, nonce)

    def get_token_advanced_info(
        self,
        binance_chain_id: Union[str, None],
        token_contract_address: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetTokenAdvancedInfoResponse]:
        """
        Get Token Advanced Info

        Return comprehensive metrics for a token, including creator and launch info, holding percentages by address type (smart money, KOL, sniper, bundler, fresh wallet, etc.), and token tags.

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier.
            token_contract_address (Union[str, None]): Token contract address.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[GetTokenAdvancedInfoResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._marketApi.get_token_advanced_info(
            binance_chain_id, token_contract_address, recv_window, nonce
        )

    def get_token_basic_info(
        self,
        binance_chain_id: Union[str, None],
        token_contract_address: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetTokenBasicInfoResponse]:
        """
        Get Token Basic Info

        Return basic metadata for a token: name, symbol, logo, decimals, creator address, creation time, and tag info.

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier.
            token_contract_address (Union[str, None]): Token contract address.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[GetTokenBasicInfoResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._marketApi.get_token_basic_info(
            binance_chain_id, token_contract_address, recv_window, nonce
        )

    def get_token_price(
        self,
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetTokenPriceResponse]:
        """
        Get Token Price

        Get the latest price for tokens. Supports batch queries, up to 100 tokens per request.

        Args:
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[GetTokenPriceResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._marketApi.get_token_price(recv_window, nonce)

    def get_token_trades(
        self,
        binance_chain_id: Union[str, None],
        token_contract_address: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        cursor: Optional[str] = None,
        limit: Optional[int] = None,
        tag_filter: Optional[GetTokenTradesTagFilterEnum] = None,
        wallet_address_filter: Optional[str] = None,
    ) -> ApiResponse[GetTokenTradesResponse]:
        """
        Get Token Trades

        Return on-chain trade history for a token. Supports tag filtering and wallet address filtering.

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier.
            token_contract_address (Union[str, None]): Token contract address.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            cursor (Optional[str] = None): Pagination cursor. Do not pass on the first request; pass the cursor value from the previous response to get the next page.
            limit (Optional[int] = None): Number of results per page, maximum 500, defaults to 100.
            tag_filter (Optional[GetTokenTradesTagFilterEnum] = None): Address tag filter, single selection only. Returns all trades with pagination when omitted; returns only the latest 100 trades for the specified tag's addresses when provided (cursor and limit are ignored). Mapping: 1=KOL, 2=Developer, 3=Smart Money, 4=Insider, 5=Sniper, 6=Bundler, 7=Whale Holder.
            wallet_address_filter (Optional[str] = None): Filter by specific wallet addresses. Separate multiple addresses with commas. Up to 2 addresses.

        Returns:
            ApiResponse[GetTokenTradesResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._marketApi.get_token_trades(
            binance_chain_id,
            token_contract_address,
            recv_window,
            nonce,
            cursor,
            limit,
            tag_filter,
            wallet_address_filter,
        )

    def get_token_trading_info(
        self,
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetTokenTradingInfoResponse]:
        """
        Get Token Trading Info

        Get token price and trading data (volume, transactions, market cap, holders, etc.). Supports batch queries for up to 100 tokens.

        Args:
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[GetTokenTradingInfoResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._marketApi.get_token_trading_info(recv_window, nonce)

    def get_top_liquidity_pools(
        self,
        binance_chain_id: Union[str, None],
        token_contract_address: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetTopLiquidityPoolsResponse]:
        """
        Get Top Liquidity Pools

        Return the top liquidity pools for a token, including pool name, protocol, liquidity in USD, pool address, and per-token composition.

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier.
            token_contract_address (Union[str, None]): Token contract address.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[GetTopLiquidityPoolsResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._marketApi.get_top_liquidity_pools(
            binance_chain_id, token_contract_address, recv_window, nonce
        )

    def get_top_traders(
        self,
        binance_chain_id: Union[str, None],
        token_contract_address: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        tag_filter: Optional[GetTopTradersTagFilterEnum] = None,
    ) -> ApiResponse[GetTopTradersResponse]:
        """
        Get Top Traders

        Return the top profit-making addresses for a token, ranked by realized PnL descending. Includes holding amount, average buy/sell price, realized PnL, and funding source. Up to 100 records. Pagination is not supported.

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier.
            token_contract_address (Union[str, None]): Token contract address.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            tag_filter (Optional[GetTopTradersTagFilterEnum] = None): Address tag filter, single selection only. Returns all top profit addresses (by realized PnL descending) when omitted; returns addresses matching the specified tag when provided. Mapping: 1=KOL, 2=Developer, 3=Smart Money, 4=Insider, 5=Sniper, 6=Bundler, 7=Whale Holder.

        Returns:
            ApiResponse[GetTopTradersResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._marketApi.get_top_traders(
            binance_chain_id, token_contract_address, recv_window, nonce, tag_filter
        )

    def search_token(
        self,
        chains: Union[str, None],
        search: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[SearchTokenResponse]:
        """
        Search Token

        Search tokens by symbol or contract address.

        Args:
            chains (Union[str, None]): List of chain IDs to search, comma-separated.
            search (Union[str, None]): Search keyword. Can be a token address or token symbol.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[SearchTokenResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._marketApi.search_token(chains, search, recv_window, nonce)

    def build_swap_transaction(
        self,
        binance_chain_id: Union[str, None],
        amount: Union[str, None],
        from_token_address: Union[str, None],
        to_token_address: Union[str, None],
        slippage_percent: Union[str, None],
        user_wallet_address: Union[str, None],
        quote_id: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        approve_transaction: Optional[
            BuildSwapTransactionApproveTransactionEnum
        ] = None,
        approve_amount: Optional[str] = None,
        gas_limit: Optional[str] = None,
        gas_level: Optional[BuildSwapTransactionGasLevelEnum] = None,
        price_impact_protection_percent: Optional[str] = None,
        auto_slippage: Optional[BuildSwapTransactionAutoSlippageEnum] = None,
        max_auto_slippage_percent: Optional[str] = None,
        compute_unit_limit: Optional[str] = None,
        compute_unit_price: Optional[str] = None,
        tips: Optional[str] = None,
    ) -> ApiResponse[BuildSwapTransactionResponse]:
        """
        Build Swap Transaction

        Build the on-chain swap calldata for a previously quoted route. The request is matched against the cached quote by `quoteId` (TTL ~30s); if the entry has expired, `QUOTE_EXPIRED` (40401) is returned, and if the request parameters disagree with the cached quote, `SWAP_QUOTE_MISMATCH` (40462) is returned.

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier (e.g. "56"=BSC, "1"=Ethereum, "CT_501"=Solana).
            amount (Union[str, None]): Sell-token amount in the token's smallest unit (positive integer string, no decimals).
            from_token_address (Union[str, None]): Sell-token contract address.
            to_token_address (Union[str, None]): Buy-token contract address.
            slippage_percent (Union[str, None]): Maximum slippage as a percentage. EVM range 0–100; Solana range 0 to less than 100. "0.5" means 0.5%.
            user_wallet_address (Union[str, None]): User wallet address (transaction sender).
            quote_id (Union[str, None]): quoteId returned from `/quote` for the route to execute. TTL ~30s; expired entries return `QUOTE_EXPIRED` (40401).
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            approve_transaction (Optional[BuildSwapTransactionApproveTransactionEnum] = None): When "true", `signatureData` includes the spender address and approve calldata so the client can submit it before the swap. Defaults to false.
            approve_amount (Optional[str] = None): Override approve amount (smallest unit, positive integer string). Defaults to the swap amount.
            gas_limit (Optional[str] = None): Gas limit override (positive integer string). EVM only.
            gas_level (Optional[BuildSwapTransactionGasLevelEnum] = None): Gas price tier. Defaults to "average".
            price_impact_protection_percent (Optional[str] = None): Maximum allowed price impact percentage (0–100). Defaults to 90; set to 100 to disable.
            auto_slippage (Optional[BuildSwapTransactionAutoSlippageEnum] = None): When "true", slippage is auto-derived from market data and overrides `slippagePercent`. Defaults to false.
            max_auto_slippage_percent (Optional[str] = None): Cap on auto-derived slippage (only applies when `autoSlippage=true`).
            compute_unit_limit (Optional[str] = None): Solana only — maximum compute units the transaction may consume (analogous to EVM gasLimit). Applies only when `binanceChainId=CT_501`.
            compute_unit_price (Optional[str] = None): Solana only — priority fee per compute unit (micro-lamports), analogous to EVM gasPrice. When omitted, the platform computes a value dynamically. Applies only when `binanceChainId=CT_501`.
            tips (Optional[str] = None): Solana only — Jito tips in SOL for MEV protection. Valid range [0.000000001, 2] (minimum 1 lamport). When specified, it is recommended to set `computeUnitPrice=0`. Applies only when `binanceChainId=CT_501`.

        Returns:
            ApiResponse[BuildSwapTransactionResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._tradingApi.build_swap_transaction(
            binance_chain_id,
            amount,
            from_token_address,
            to_token_address,
            slippage_percent,
            user_wallet_address,
            quote_id,
            recv_window,
            nonce,
            approve_transaction,
            approve_amount,
            gas_limit,
            gas_level,
            price_impact_protection_percent,
            auto_slippage,
            max_auto_slippage_percent,
            compute_unit_limit,
            compute_unit_price,
            tips,
        )

    def get_aggregated_quote(
        self,
        binance_chain_id: Union[str, None],
        amount: Union[str, None],
        from_token_address: Union[str, None],
        to_token_address: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetAggregatedQuoteResponse]:
        """
        Get Aggregated Quote

        Query multiple DEX vendors in parallel and return the priced routes sorted by `toTokenAmount` (descending). Each route carries an independent `quoteId` (TTL ~30s) that the swap endpoint consumes to construct calldata for the chosen route.

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier (e.g. "56"=BSC, "1"=Ethereum, "CT_501"=Solana).
            amount (Union[str, None]): Sell-token amount in the token's smallest unit (positive integer string, no decimals). Example "1000000" = 1 USDT (decimals=6).
            from_token_address (Union[str, None]): Sell-token contract address. EVM chains require 0x + 40 hex chars; non-EVM chains use the chain's native address format.
            to_token_address (Union[str, None]): Buy-token contract address. Must differ from `fromTokenAddress`.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[GetAggregatedQuoteResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._tradingApi.get_aggregated_quote(
            binance_chain_id,
            amount,
            from_token_address,
            to_token_address,
            recv_window,
            nonce,
        )

    def get_aggregator_supported_chains(
        self,
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        binance_chain_id: Optional[str] = None,
    ) -> ApiResponse[GetAggregatorSupportedChainsResponse]:
        """
                Get Aggregator Supported Chains

                Return blockchain networks supported by the DEX aggregator. The supported list is dynamically configured server-side and may change over time.
        Pass `binanceChainId` to filter to a single chain; omit it to get the full list.

                Args:
                    recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
                    nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
                    binance_chain_id (Optional[str] = None): Optional chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana). When set, only that chain is returned.

                Returns:
                    ApiResponse[GetAggregatorSupportedChainsResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        return self._tradingApi.get_aggregator_supported_chains(
            recv_window, nonce, binance_chain_id
        )

    def get_erc20_approve_transaction(
        self,
        binance_chain_id: Union[str, None],
        token_contract_address: Union[str, None],
        approve_amount: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetErc20ApproveTransactionResponse]:
        """
        Get ERC-20 Approve Transaction

        Build the on-chain transaction data needed to approve the DEX router to spend a user's ERC-20 token before a swap. Calldata is encoded per the ERC-20 ABI standard (`approve()` selector + spender + amount).

        Args:
            binance_chain_id (Union[str, None]): Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC).
            token_contract_address (Union[str, None]): ERC-20 token contract address to approve (0x + 40 hex chars).
            approve_amount (Union[str, None]): Approval amount in the token's smallest unit (positive integer string). Example "1000000" = 1 USDT (decimals=6).
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[GetErc20ApproveTransactionResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._tradingApi.get_erc20_approve_transaction(
            binance_chain_id, token_contract_address, approve_amount, recv_window, nonce
        )

    def get_transaction_status(
        self,
        binance_chain_id: Union[str, None],
        tx_hash: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetTransactionStatusResponse]:
        """
                Get Transaction Status

                Look up the on-chain status of a DEX swap by `binanceChainId` + `txHash`.
        Response semantics:
        - Transaction not found: `data` is `null` (not HTTP 404).
        - Transaction failed: `status=failed` with `errorMsg`; aggregator
          business fields (`txType`, `dexRouter`, `fromTokenDetails`,
          `toTokenDetails`) are `null`.

        - Transaction succeeded: `status=success` with full token details
          when an aggregator event is present.

                Args:
                    binance_chain_id (Union[str, None]): Unique chain identifier (e.g. "56"=BSC, "1"=Ethereum, "CT_501"=Solana).
                    tx_hash (Union[str, None]): On-chain transaction hash.
                    recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
                    nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

                Returns:
                    ApiResponse[GetTransactionStatusResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        return self._tradingApi.get_transaction_status(
            binance_chain_id, tx_hash, recv_window, nonce
        )

    def broadcast_transactions(
        self,
        binance_chain_id: Union[str, None],
        signed_transaction: Union[str, None],
        address: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        enable_mev_protection: Optional[bool] = None,
    ) -> ApiResponse[BroadcastTransactionsResponse]:
        """
                Broadcast Transactions

                Broadcast a client-signed transaction to the chain via the OnchainOS relay. Returns the transaction hash and an internal `orderId` you can use to track on-chain status via the post-transaction service.
        Optional MEV protection (EVM chains only) routes the transaction through a private mempool to mitigate front-running and sandwich attacks.

                Args:
                    binance_chain_id (Union[str, None]): Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
                    signed_transaction (Union[str, None]): Client-signed raw transaction. EVM chains use a hex-encoded RLP transaction; Solana uses a base64-encoded signed transaction.
                    address (Union[str, None]): Sender wallet address. Used for status attribution and signature verification.
                    recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
                    nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
                    enable_mev_protection (Optional[bool] = None): When true, route the transaction through a private mempool for MEV protection.

                Returns:
                    ApiResponse[BroadcastTransactionsResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        return self._transactionApi.broadcast_transactions(
            binance_chain_id,
            signed_transaction,
            address,
            recv_window,
            nonce,
            enable_mev_protection,
        )

    def get_broadcast_orders(
        self,
        address: Union[str, None],
        binance_chain_id: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        tx_status: Optional[str] = None,
        order_id: Optional[str] = None,
        cursor: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> ApiResponse[GetBroadcastOrdersResponse]:
        """
        Get Broadcast Orders

        Look up broadcast orders previously submitted via `/pre-transaction/broadcast-transaction`. Filter by `txStatus` or `orderId`, paginate with `cursor`.

        Args:
            address (Union[str, None]): Sender wallet address whose orders to list.
            binance_chain_id (Union[str, None]): Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            tx_status (Optional[str] = None): Optional filter on transaction status (server-defined string, e.g. "pending", "success", "fail").
            order_id (Optional[str] = None): Optional filter to fetch a single order by its internal order ID.
            cursor (Optional[str] = None): Pagination cursor returned by the previous page. Omit on the first request.
            limit (Optional[int] = None): Page size. Defaults to 20.

        Returns:
            ApiResponse[GetBroadcastOrdersResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._transactionApi.get_broadcast_orders(
            address,
            binance_chain_id,
            recv_window,
            nonce,
            tx_status,
            order_id,
            cursor,
            limit,
        )

    def get_gas_limit(
        self,
        binance_chain_id: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        evm_tx: Optional[GetGasLimitRequestEvmTx] = None,
        sol_tx: Optional[GetGasLimitRequestSolTx] = None,
    ) -> ApiResponse[GetGasLimitResponse]:
        """
                Get Gas Limit

                Estimate the gas limit (or compute-unit ceiling on Solana) for an unsigned transaction.
        Provide either `evmTx` for EVM chains or `solTx` for Solana, matching the value of `binanceChainId`.

                Args:
                    binance_chain_id (Union[str, None]): Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
                    recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
                    nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
                    evm_tx (Optional[GetGasLimitRequestEvmTx] = None):
                    sol_tx (Optional[GetGasLimitRequestSolTx] = None):

                Returns:
                    ApiResponse[GetGasLimitResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        return self._transactionApi.get_gas_limit(
            binance_chain_id, recv_window, nonce, evm_tx, sol_tx
        )

    def get_gas_price(
        self,
        binance_chain_id: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetGasPriceResponse]:
        """
                Get Gas Price

                Query the current network gas price for the specified chain. The response shape varies by chain family:
        - EVM chains return both `evmLegacyGasPrice` (legacy gasPrice) and
          `eip1559GasPrice` (baseFee + priority/max fees) when EIP-1559 is supported.
        - Solana returns `solanaGasPrice` (compute-unit prices and Jito tips).
        Fields not applicable to the chain family are returned as `null`.

                Args:
                    binance_chain_id (Union[str, None]): Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
                    recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
                    nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

                Returns:
                    ApiResponse[GetGasPriceResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        return self._transactionApi.get_gas_price(binance_chain_id, recv_window, nonce)

    def get_transaction_supported_chains(
        self,
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
    ) -> ApiResponse[GetTransactionSupportedChainsResponse]:
        """
        Get Transaction Supported Chains

        Return the blockchain networks supported by the Transaction service for gas estimation, simulation, and broadcasting. The list is dynamically configured server-side and may change over time.

        Args:
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.

        Returns:
            ApiResponse[GetTransactionSupportedChainsResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._transactionApi.get_transaction_supported_chains(recv_window, nonce)

    def simulate_transactions(
        self,
        binance_chain_id: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        evm_tx: Optional[SimulateTransactionsRequestEvmTx] = None,
        sol_tx: Optional[SimulateTransactionsRequestSolTx] = None,
    ) -> ApiResponse[SimulateTransactionsResponse]:
        """
                Simulate Transactions

                Simulate transaction execution off-chain to predict its outcome before broadcasting. The response includes the predicted execution status, balance changes per affected account/token, and ERC-20 allowance changes (EVM chains).
        Provide either `evmTx` (EVM chains) or `solTx` (Solana) matching `binanceChainId`.

                Args:
                    binance_chain_id (Union[str, None]): Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
                    recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
                    nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
                    evm_tx (Optional[SimulateTransactionsRequestEvmTx] = None):
                    sol_tx (Optional[SimulateTransactionsRequestSolTx] = None):

                Returns:
                    ApiResponse[SimulateTransactionsResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        return self._transactionApi.simulate_transactions(
            binance_chain_id, recv_window, nonce, evm_tx, sol_tx
        )

    def get_all_token_balances_by_address(
        self,
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        address: Optional[str] = None,
        chains: Optional[str] = None,
        exclude_risk_token: Optional[bool] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse[GetAllTokenBalancesByAddressResponse]:
        """
        Get All Token Balances by Address

        Return all token balances held by an address across one or more chains, with pagination support. Set `excludeRiskToken=true` to filter out airdrop-risk and honeypot tokens (honeypot detection currently applies only to ETH / BSC / SOL / BASE).

        Args:
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            address (Optional[str] = None): Wallet address to query.
            chains (Optional[str] = None): Comma-separated list of chain identifiers.
            exclude_risk_token (Optional[bool] = None): Whether to exclude risk-flagged tokens.
            page (Optional[int] = None): Page number. Defaults to 1.
            page_size (Optional[int] = None): Page size. Range 1–100. Defaults to 20.

        Returns:
            ApiResponse[GetAllTokenBalancesByAddressResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._walletApi.get_all_token_balances_by_address(
            recv_window, nonce, address, chains, exclude_risk_token, page, page_size
        )

    def get_token_balances_by_address(
        self,
        address: Union[str, None],
        token_contract_addresses: Union[
            List[GetTokenBalancesByAddressRequestTokenContractAddressesInner], None
        ],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        exclude_risk_token: Optional[
            GetTokenBalancesByAddressExcludeRiskTokenEnum
        ] = None,
    ) -> ApiResponse[GetTokenBalancesByAddressResponse]:
        """
        Get Token Balances by Address

        Return token balances for a specific list of (chain, contract) pairs. Up to 20 entries per request. Set `excludeRiskToken="0"` to exclude risk-flagged tokens (default), or `"1"` to include them.

        Args:
            address (Union[str, None]): Wallet address to query.
            token_contract_addresses (Union[List[GetTokenBalancesByAddressRequestTokenContractAddressesInner], None]): Tokens to query, up to 20 entries.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            exclude_risk_token (Optional[GetTokenBalancesByAddressExcludeRiskTokenEnum] = None): Risk-token filter. "0"=exclude (default), "1"=include. Honeypot detection currently applies only to ETH / BSC / SOL / BASE.

        Returns:
            ApiResponse[GetTokenBalancesByAddressResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._walletApi.get_token_balances_by_address(
            address, token_contract_addresses, recv_window, nonce, exclude_risk_token
        )

    def get_transaction_detail_by_hash(
        self,
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        binance_chain_id: Optional[str] = None,
        tx_hash: Optional[str] = None,
        itype: Optional[str] = None,
    ) -> ApiResponse[GetTransactionDetailByHashResponse]:
        """
        Get Transaction Detail by Hash

        Look up the full on-chain transaction detail by `binanceChainId` + `txHash`. Returns one or more entries describing transaction inputs, outputs, internal calls, and token transfers.

        Args:
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            binance_chain_id (Optional[str] = None): Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
            tx_hash (Optional[str] = None): On-chain transaction hash.
            itype (Optional[str] = None): Transaction-type filter (UTXO chains). Reserved — currently has no effect. Values: "0"=outer native-token, "1"=internal contract native-token, "2"=token transfer.

        Returns:
            ApiResponse[GetTransactionDetailByHashResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._walletApi.get_transaction_detail_by_hash(
            recv_window, nonce, binance_chain_id, tx_hash, itype
        )

    def get_transactions_by_address(
        self,
        address: Union[str, None],
        chains: Union[str, None],
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        token_contract_address: Optional[str] = None,
        begin: Optional[int] = None,
        end: Optional[int] = None,
        cursor: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> ApiResponse[GetTransactionsByAddressResponse]:
        """
        Get Transactions by Address

        Return on-chain transaction history for a wallet address across one or more chains. Results are limited to the most recent 6 months and sorted by time (descending). Supports cursor pagination, time-range filtering, and token-contract filtering.

        Args:
            address (Union[str, None]): Wallet address to query.
            chains (Union[str, None]): Comma-separated list of chain identifiers.
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            token_contract_address (Optional[str] = None): Optional token contract address filter.
            begin (Optional[int] = None): Optional start timestamp (Unix milliseconds, inclusive).
            end (Optional[int] = None): Optional end timestamp (Unix milliseconds, inclusive).
            cursor (Optional[str] = None): Pagination cursor returned by the previous page.
            limit (Optional[int] = None): Page size. Range 1–100. Defaults to 20.

        Returns:
            ApiResponse[GetTransactionsByAddressResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._walletApi.get_transactions_by_address(
            address,
            chains,
            recv_window,
            nonce,
            token_contract_address,
            begin,
            end,
            cursor,
            limit,
        )

    def get_wallet_supported_chains(
        self,
        recv_window: Optional[int] = None,
        nonce: Optional[str] = None,
        binance_chain_id: Optional[str] = None,
    ) -> ApiResponse[GetWalletSupportedChainsResponse]:
        """
        Get Wallet Supported Chains

        Return blockchain networks for which the Wallet service can return balances. The supported list is dynamically configured server-side and may change over time. Pass `binanceChainId` to filter to a single chain; omit to get the full list.

        Args:
            recv_window (Optional[int] = None): Allowed time deviation in milliseconds (default: 5000, max: 60000).
            nonce (Optional[str] = None): Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
            binance_chain_id (Optional[str] = None): Optional chain identifier. When set, only that chain is returned.

        Returns:
            ApiResponse[GetWalletSupportedChainsResponse]

        Raises:
            RequiredError: If a required parameter is missing.

        """

        return self._walletApi.get_wallet_supported_chains(
            recv_window, nonce, binance_chain_id
        )
