"""
Binance Web3 WebSocket Streams

Real-time on-chain data streaming over WebSocket for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""
