# coding: utf-8

"""
Binance Web3 WebSocket Streams

Real-time on-chain data streaming over WebSocket for the Binance Web3 API platform.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class MarketStatsStreamResponse(BaseModel):
    """
    TX data event payload.
    """  # noqa: E501

    p: Optional[StrictStr] = Field(default=None, description="Latest price in USD.")
    t: Optional[StrictInt] = Field(
        default=None, description="Price timestamp in milliseconds."
    )
    pc5m: Optional[StrictStr] = Field(
        default=None,
        description='5-minute price change, as a percentage (e.g. "1.25" means +1.25%).',
    )
    pc1h: Optional[StrictStr] = Field(
        default=None,
        description='1-hour price change, as a percentage (e.g. "1.25" means +1.25%).',
    )
    pc4h: Optional[StrictStr] = Field(
        default=None,
        description='4-hour price change, as a percentage (e.g. "1.25" means +1.25%).',
    )
    pc24h: Optional[StrictStr] = Field(
        default=None,
        description='24-hour price change, as a percentage (e.g. "1.25" means +1.25%).',
    )
    vol5m: Optional[StrictStr] = Field(
        default=None, description="5-minute total trading volume in USD."
    )
    vol1h: Optional[StrictStr] = Field(
        default=None, description="1-hour total trading volume in USD."
    )
    vol4h: Optional[StrictStr] = Field(
        default=None, description="4-hour total trading volume in USD."
    )
    vol24h: Optional[StrictStr] = Field(
        default=None, description="24-hour total trading volume in USD."
    )
    vol_b5m: Optional[StrictStr] = Field(
        default=None, description="5-minute buy volume in USD.", alias="volB5m"
    )
    vol_s5m: Optional[StrictStr] = Field(
        default=None, description="5-minute sell volume in USD.", alias="volS5m"
    )
    vol_b1h: Optional[StrictStr] = Field(
        default=None, description="1-hour buy volume in USD.", alias="volB1h"
    )
    vol_s1h: Optional[StrictStr] = Field(
        default=None, description="1-hour sell volume in USD.", alias="volS1h"
    )
    vol_b4h: Optional[StrictStr] = Field(
        default=None, description="4-hour buy volume in USD.", alias="volB4h"
    )
    vol_s4h: Optional[StrictStr] = Field(
        default=None, description="4-hour sell volume in USD.", alias="volS4h"
    )
    vol_b24h: Optional[StrictStr] = Field(
        default=None, description="24-hour buy volume in USD.", alias="volB24h"
    )
    vol_s24h: Optional[StrictStr] = Field(
        default=None, description="24-hour sell volume in USD.", alias="volS24h"
    )
    txs5m: Optional[StrictInt] = Field(
        default=None, description="5-minute total transaction count."
    )
    txs1h: Optional[StrictInt] = Field(
        default=None, description="1-hour total transaction count."
    )
    txs4h: Optional[StrictInt] = Field(
        default=None, description="4-hour total transaction count."
    )
    txs24h: Optional[StrictInt] = Field(
        default=None, description="24-hour total transaction count."
    )
    txs_b5m: Optional[StrictInt] = Field(
        default=None, description="5-minute buy transaction count.", alias="txsB5m"
    )
    txs_s5m: Optional[StrictInt] = Field(
        default=None, description="5-minute sell transaction count.", alias="txsS5m"
    )
    txs_b1h: Optional[StrictInt] = Field(
        default=None, description="1-hour buy transaction count.", alias="txsB1h"
    )
    txs_s1h: Optional[StrictInt] = Field(
        default=None, description="1-hour sell transaction count.", alias="txsS1h"
    )
    txs_b4h: Optional[StrictInt] = Field(
        default=None, description="4-hour buy transaction count.", alias="txsB4h"
    )
    txs_s4h: Optional[StrictInt] = Field(
        default=None, description="4-hour sell transaction count.", alias="txsS4h"
    )
    txs_b24h: Optional[StrictInt] = Field(
        default=None, description="24-hour buy transaction count.", alias="txsB24h"
    )
    txs_s24h: Optional[StrictInt] = Field(
        default=None, description="24-hour sell transaction count.", alias="txsS24h"
    )
    cs: Optional[StrictStr] = Field(default=None, description="Circulating supply.")
    mc: Optional[StrictStr] = Field(default=None, description="Market cap in USD.")
    liq: Optional[StrictStr] = Field(default=None, description="Liquidity in USD.")
    holders: Optional[StrictInt] = Field(
        default=None, description="Number of holder addresses."
    )
    bn_vol5m: Optional[StrictStr] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 5-minute total volume in USD.",
        alias="bnVol5m",
    )
    bn_vol1h: Optional[StrictStr] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 1-hour total volume in USD.",
        alias="bnVol1h",
    )
    bn_vol4h: Optional[StrictStr] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 4-hour total volume in USD.",
        alias="bnVol4h",
    )
    bn_vol24h: Optional[StrictStr] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 24-hour total volume in USD.",
        alias="bnVol24h",
    )
    bn_vol_b5m: Optional[StrictStr] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 5-minute buy volume in USD.",
        alias="bnVolB5m",
    )
    bn_vol_s5m: Optional[StrictStr] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 5-minute sell volume in USD.",
        alias="bnVolS5m",
    )
    bn_vol_b1h: Optional[StrictStr] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 1-hour buy volume in USD.",
        alias="bnVolB1h",
    )
    bn_vol_s1h: Optional[StrictStr] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 1-hour sell volume in USD.",
        alias="bnVolS1h",
    )
    bn_vol_b4h: Optional[StrictStr] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 4-hour buy volume in USD.",
        alias="bnVolB4h",
    )
    bn_vol_s4h: Optional[StrictStr] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 4-hour sell volume in USD.",
        alias="bnVolS4h",
    )
    bn_vol_b24h: Optional[StrictStr] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 24-hour buy volume in USD.",
        alias="bnVolB24h",
    )
    bn_vol_s24h: Optional[StrictStr] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 24-hour sell volume in USD.",
        alias="bnVolS24h",
    )
    bn_txs5m: Optional[StrictInt] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 5-minute total transaction count.",
        alias="bnTxs5m",
    )
    bn_txs1h: Optional[StrictInt] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 1-hour total transaction count.",
        alias="bnTxs1h",
    )
    bn_txs4h: Optional[StrictInt] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 4-hour total transaction count.",
        alias="bnTxs4h",
    )
    bn_txs24h: Optional[StrictInt] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 24-hour total transaction count.",
        alias="bnTxs24h",
    )
    bn_txs_b5m: Optional[StrictInt] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 5-minute buy transaction count.",
        alias="bnTxsB5m",
    )
    bn_txs_s5m: Optional[StrictInt] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 5-minute sell transaction count.",
        alias="bnTxsS5m",
    )
    bn_txs_b1h: Optional[StrictInt] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 1-hour buy transaction count.",
        alias="bnTxsB1h",
    )
    bn_txs_s1h: Optional[StrictInt] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 1-hour sell transaction count.",
        alias="bnTxsS1h",
    )
    bn_txs_b4h: Optional[StrictInt] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 4-hour buy transaction count.",
        alias="bnTxsB4h",
    )
    bn_txs_s4h: Optional[StrictInt] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 4-hour sell transaction count.",
        alias="bnTxsS4h",
    )
    bn_txs_b24h: Optional[StrictInt] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 24-hour buy transaction count.",
        alias="bnTxsB24h",
    )
    bn_txs_s24h: Optional[StrictInt] = Field(
        default=None,
        description="Binance MPC wallet (trading via Binance Web3 DEX) 24-hour sell transaction count.",
        alias="bnTxsS24h",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "p",
        "t",
        "pc5m",
        "pc1h",
        "pc4h",
        "pc24h",
        "vol5m",
        "vol1h",
        "vol4h",
        "vol24h",
        "vol_b5m",
        "vol_s5m",
        "vol_b1h",
        "vol_s1h",
        "vol_b4h",
        "vol_s4h",
        "vol_b24h",
        "vol_s24h",
        "txs5m",
        "txs1h",
        "txs4h",
        "txs24h",
        "txs_b5m",
        "txs_s5m",
        "txs_b1h",
        "txs_s1h",
        "txs_b4h",
        "txs_s4h",
        "txs_b24h",
        "txs_s24h",
        "cs",
        "mc",
        "liq",
        "holders",
        "bn_vol5m",
        "bn_vol1h",
        "bn_vol4h",
        "bn_vol24h",
        "bn_vol_b5m",
        "bn_vol_s5m",
        "bn_vol_b1h",
        "bn_vol_s1h",
        "bn_vol_b4h",
        "bn_vol_s4h",
        "bn_vol_b24h",
        "bn_vol_s24h",
        "bn_txs5m",
        "bn_txs1h",
        "bn_txs4h",
        "bn_txs24h",
        "bn_txs_b5m",
        "bn_txs_s5m",
        "bn_txs_b1h",
        "bn_txs_s1h",
        "bn_txs_b4h",
        "bn_txs_s4h",
        "bn_txs_b24h",
        "bn_txs_s24h",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MarketStatsStreamResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MarketStatsStreamResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "p": obj.get("p"),
                "t": obj.get("t"),
                "pc5m": obj.get("pc5m"),
                "pc1h": obj.get("pc1h"),
                "pc4h": obj.get("pc4h"),
                "pc24h": obj.get("pc24h"),
                "vol5m": obj.get("vol5m"),
                "vol1h": obj.get("vol1h"),
                "vol4h": obj.get("vol4h"),
                "vol24h": obj.get("vol24h"),
                "volB5m": obj.get("volB5m"),
                "volS5m": obj.get("volS5m"),
                "volB1h": obj.get("volB1h"),
                "volS1h": obj.get("volS1h"),
                "volB4h": obj.get("volB4h"),
                "volS4h": obj.get("volS4h"),
                "volB24h": obj.get("volB24h"),
                "volS24h": obj.get("volS24h"),
                "txs5m": obj.get("txs5m"),
                "txs1h": obj.get("txs1h"),
                "txs4h": obj.get("txs4h"),
                "txs24h": obj.get("txs24h"),
                "txsB5m": obj.get("txsB5m"),
                "txsS5m": obj.get("txsS5m"),
                "txsB1h": obj.get("txsB1h"),
                "txsS1h": obj.get("txsS1h"),
                "txsB4h": obj.get("txsB4h"),
                "txsS4h": obj.get("txsS4h"),
                "txsB24h": obj.get("txsB24h"),
                "txsS24h": obj.get("txsS24h"),
                "cs": obj.get("cs"),
                "mc": obj.get("mc"),
                "liq": obj.get("liq"),
                "holders": obj.get("holders"),
                "bnVol5m": obj.get("bnVol5m"),
                "bnVol1h": obj.get("bnVol1h"),
                "bnVol4h": obj.get("bnVol4h"),
                "bnVol24h": obj.get("bnVol24h"),
                "bnVolB5m": obj.get("bnVolB5m"),
                "bnVolS5m": obj.get("bnVolS5m"),
                "bnVolB1h": obj.get("bnVolB1h"),
                "bnVolS1h": obj.get("bnVolS1h"),
                "bnVolB4h": obj.get("bnVolB4h"),
                "bnVolS4h": obj.get("bnVolS4h"),
                "bnVolB24h": obj.get("bnVolB24h"),
                "bnVolS24h": obj.get("bnVolS24h"),
                "bnTxs5m": obj.get("bnTxs5m"),
                "bnTxs1h": obj.get("bnTxs1h"),
                "bnTxs4h": obj.get("bnTxs4h"),
                "bnTxs24h": obj.get("bnTxs24h"),
                "bnTxsB5m": obj.get("bnTxsB5m"),
                "bnTxsS5m": obj.get("bnTxsS5m"),
                "bnTxsB1h": obj.get("bnTxsB1h"),
                "bnTxsS1h": obj.get("bnTxsS1h"),
                "bnTxsB4h": obj.get("bnTxsB4h"),
                "bnTxsS4h": obj.get("bnTxsS4h"),
                "bnTxsB24h": obj.get("bnTxsB24h"),
                "bnTxsS24h": obj.get("bnTxsS24h"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
